// Language display names in native script
const languageNames = {
  en: "English",
  hi: "हिन्दी",
  mr: "मराठी",
  ta: "தமிழ்",
  te: "తెలుగు",
  pa: "ਪੰਜਾਬੀ"
};

// Language translations for multi-language support
const translations = {
  en: {
    // Navigation
    home: "Home",
    product: "Product",
    technology: "Technology",
    team: "Team",
    investors: "Investors",
    blog: "Blog",
    contact: "Contact",
    // Hero
    tag: "⚡ AI-Powered Smart Farming",
    title: "AI Powered Future of Farming",
    subtitle: "AgriRover is a smart robotic farming system designed to help small farmers automate their agricultural work — bringing precision, efficiency, and intelligence.",
    exploreProduct: "Explore Product →",
    contactUs: "Contact Us",
    lessChemical: "Less Chemical Use",
    fasterOps: "Faster Operations",
    wirelessRange: "Wireless Range",
    cropCompat: "Crop Compatibility",
    // Features
    coreCapabilities: "CORE CAPABILITIES",
    whatCanDo: "What AgriRover Can Do",
    featuresSub: "Four powerful farming modules that work together to automate your entire crop cycle.",
    smartSpraying: "Smart Spraying",
    sprayingDesc: "Automated pesticide spraying with precision targeting — reducing chemical waste by up to 40%.",
    seedSowing: "Seed Sowing",
    sowingDesc: "Accurate seed planting with robotic precision, ensuring optimal spacing and depth every time.",
    fertilizerSpreading: "Fertilizer Spreading",
    fertilizerDesc: "Uniform fertilizer distribution across the field — maximizing yield and minimizing waste.",
    aiNavigation: "AI Navigation",
    aiDesc: "Upcoming autonomous farming with AI-powered path planning and obstacle avoidance.",
    // Vision
    ourVision: "OUR VISION",
    visionTitle: "Building the Future of Indian Agriculture",
    visionDesc: "India has over 100 million small farmers. AgriRover is here to give each of them the power of automation — affordable, rugged, and made for every field.",
    ecoFriendly: "🌱 Eco-friendly operation",
    durable: "🛡 Durable for rough terrain",
    lowPower: "⚡ Low power consumption",
    // Technology
    technology: "TECHNOLOGY",
    engineered: "Engineered for the Fields",
    techDesc: "AgriRover integrates robotics, embedded systems, and wireless technology to create a compact smart farming machine that thrives in real-world Indian agricultural conditions.",
    embedded: "Embedded Control",
    wireless: "Wireless Comms",
    mechanical: "Mechanical",
    futureTech: "Future Tech",
    fullSpecs: "Full Tech Specs →",
    systemsOnline: "⚡ Systems Online",
    // Footer
    smartAgri: "SMART AGRICULTURE ROBOTICS",
    footerDesc: "Empowering India's small farmers with intelligent robotic automation. Building the future of precision agriculture, one field at a time.",
    email: "info.aiagrirover@gmail.com",
    location: "India",
    company: "COMPANY",
    resources: "RESOURCES",
    copyright: "© 2026 AI AgriRover | Smart Agriculture Robotics",
    statusOnline: "Systems Online"
  },
  hi: {
    // Hindi translations
    home: "होम",
    product: "उत्पाद",
    technology: "प्रौद्योगिकी",
    team: "टीम",
    investors: "निवेशक",
    blog: "ब्लॉग",
    contact: "संपर्क",
    tag: "⚡ एआई-संचालित स्मार्ट कृषि",
    title: "एआई संचालित कृषि का भविष्य",
    subtitle: "एग्रीरोवर एक स्मार्ट रोबोटिक कृषि प्रणाली है जो छोटे किसानों को उनकी कृषि कार्यों को स्वचालित करने में मदद करती है — सटीकता, दक्षता और बुद्धिमत्ता लाती है।",
    exploreProduct: "उत्पाद देखें →",
    contactUs: "हमसे संपर्क करें",
    lessChemical: "कम रासायनिक उपयोग",
    fasterOps: "तेजी से संचालन",
    wirelessRange: "वायरलेस रेंज",
    cropCompat: "फसल अनुकूलता",
    coreCapabilities: "कोर क्षमताएं",
    whatCanDo: "एग्रीरोवर क्या कर सकता है",
    featuresSub: "चार शक्तिशाली कृषि मॉड्यूल जो आपके पूरे फसल चक्र को स्वचालित करने के लिए एक साथ काम करते हैं।",
    smartSpraying: "स्मार्ट स्प्रेइंग",
    sprayingDesc: "स्वचालित कीटनाशक स्प्रेइंग सटीक लक्ष्यीकरण के साथ — रासायनिक अपशिष्ट को 40% तक कम करता है।",
    seedSowing: "बीज बोना",
    sowingDesc: "रोबोटिक सटीकता के साथ सटीक बीज रोपण, हर समय इष्टतम अंतर और गहराई सुनिश्चित करता है।",
    fertilizerSpreading: "उर्वरक फैलाना",
    fertilizerDesc: "खेत में समान उर्वरक वितरण — उपज को अधिकतम करता है और अपशिष्ट को कम करता है।",
    aiNavigation: "एआई नेविगेशन",
    aiDesc: "एआई-संचालित पथ योजना और बाधा से बचने के साथ आगामी स्वायत्त कृषि।",
    ourVision: "हमारा विजन",
    visionTitle: "भारतीय कृषि का भविष्य बनाना",
    visionDesc: "भारत में 100 मिलियन से अधिक छोटे किसान हैं। एग्रीरोवर यहां प्रत्येक को स्वचालन की शक्ति देने के लिए है — किफायती, मजबूत, और हर खेत के लिए बनाया गया।",
    ecoFriendly: "🌱 पर्यावरण-अनुकूल संचालन",
    durable: "🛡 खुरदरे इलाकों के लिए टिकाऊ",
    lowPower: "⚡ कम बिजली खपत",
    technology: "प्रौद्योगिकी",
    engineered: "खेतों के लिए इंजीनियर्ड",
    techDesc: "एग्रीरोवर रोबोटिक्स, एम्बेडेड सिस्टम और वायरलेस तकनीक को एकीकृत करता है ताकि वास्तविक दुनिया की भारतीय कृषि स्थितियों में पनपने वाली एक कॉम्पैक्ट स्मार्ट कृषि मशीन बनाई जा सके।",
    embedded: "एम्बेडेड नियंत्रण",
    wireless: "वायरलेस कम्युनिकेशन",
    mechanical: "यांत्रिक",
    futureTech: "भविष्य की तकनीक",
    fullSpecs: "पूर्ण टेक स्पेक्स →",
    systemsOnline: "⚡ सिस्टम ऑनलाइन",
    smartAgri: "स्मार्ट कृषि रोबोटिक्स",
    footerDesc: "बुद्धिमान रोबोटिक स्वचालन के साथ भारत के छोटे किसानों को सशक्त बनाना। एक समय में एक खेत, सटीक कृषि का भविष्य बनाना।",
    email: "info.aiagrirover@gmail.com",
    location: "भारत",
    company: "कंपनी",
    resources: "संसाधन",
    copyright: "© 2026 एआई एग्रीरोवर | स्मार्ट कृषि रोबोटिक्स",
    statusOnline: "सिस्टम ऑनलाइन"
  },
  mr: {
    // Marathi translations (similar structure)
    home: "मुख्यपृष्ठ",
    product: "उत्पादन",
    technology: "तंत्रज्ञान",
    team: "संघ",
    investors: "गुंतवणूकदार",
    blog: "ब्लॉग",
    contact: "संपर्क",
    tag: "⚡ एआय-चालित स्मार्ट शेती",
    title: "एआय चालित शेतीचे भविष्य",
    subtitle: "एग्रीरोवर ही स्मार्ट रोबोटिक शेती प्रणाली आहे जी लहान शेतकऱ्यांना त्यांच्या शेती कामांना स्वयंचलित करण्यात मदत करते — अचूकता, कार्यक्षमता आणि बुद्धिमत्ता आणते.",
    exploreProduct: "उत्पादन पहा →",
    contactUs: "आमच्याशी संपर्क साधा",
    lessChemical: "कमी रासायनिक वापर",
    fasterOps: "वेगवान ऑपरेशन्स",
    wirelessRange: "वायरलेस रेंज",
    cropCompat: "पीक सुसंगतता",
    coreCapabilities: "कोर क्षमता",
    whatCanDo: "एग्रीरोवर काय करू शकते",
    featuresSub: "चार शक्तिशाली शेती मॉड्यूल्स जी तुमच्या संपूर्ण पीक चक्राला स्वयंचलित करण्यासाठी एकत्र काम करतात.",
    smartSpraying: "स्मार्ट स्प्रेइंग",
    sprayingDesc: "स्वयंचलित कीटकनाशक स्प्रेइंग अचूक लक्ष्यीकरणासह — रासायनिक कचरा 40% पर्यंत कमी करते.",
    seedSowing: "बियाणे पेरणी",
    sowingDesc: "रोबोटिक अचूकतेसह अचूक बियाणे रोपण, प्रत्येक वेळी इष्टतम अंतर आणि खोली सुनिश्चित करते.",
    fertilizerSpreading: "खत पसरवणे",
    fertilizerDesc: "शेतात समान खत वितरण — उत्पादन वाढवते आणि कचरा कमी करते.",
    aiNavigation: "एआय नेव्हिगेशन",
    aiDesc: "एआय-चालित मार्ग नियोजन आणि अडथळा टाळण्यासह येणारे स्वयंचलित शेती.",
    ourVision: "आमचा दृष्टिकोन",
    visionTitle: "भारतीय शेतीचे भविष्य बांधणे",
    visionDesc: "भारतात 100 दशलक्षाहून अधिक लहान शेतकरी आहेत. एग्रीरोवर प्रत्येकाला स्वयंचलनाची शक्ती देण्यासाठी येथे आहे — परवडणारे, मजबूत आणि प्रत्येक शेतासाठी बनवलेले.",
    ecoFriendly: "🌱 पर्यावरण-अनुकूल ऑपरेशन",
    durable: "🛡 खडतर भूभागासाठी टिकाऊ",
    lowPower: "⚡ कमी पॉवर खपत",
    technology: "तंत्रज्ञान",
    engineered: "शेतांसाठी इंजिनियर्ड",
    techDesc: "एग्रीरोवर रोबोटिक्स, एम्बेडेड सिस्टम आणि वायरलेस तंत्रज्ञान एकत्रित करते जेणेकरून वास्तविक जगातील भारतीय शेती परिस्थितींमध्ये वाढणारी कॉम्पॅक्ट स्मार्ट शेती मशीन तयार करता येईल.",
    embedded: "एम्बेडेड कंट्रोल",
    wireless: "वायरलेस कम्युनिकेशन्स",
    mechanical: "यांत्रिक",
    futureTech: "भविष्याचे तंत्रज्ञान",
    fullSpecs: "पूर्ण टेक स्पेक्स →",
    systemsOnline: "⚡ सिस्टम ऑनलाइन",
    smartAgri: "स्मार्ट कृषी रोबोटिक्स",
    footerDesc: "बुद्धिमान रोबोटिक स्वयंचलनासह भारताच्या लहान शेतकऱ्यांना सशक्त बनवणे. एका वेळी एक शेत, अचूक शेतीचे भविष्य बांधणे.",
    email: "info.aiagrirover@gmail.com",
    location: "भारत",
    company: "कंपनी",
    resources: "संसाधने",
    copyright: "© 2026 एआय एग्रीरोवर | स्मार्ट कृषी रोबोटिक्स",
    statusOnline: "सिस्टम ऑनलाइन"
  },
  ta: {
    // Tamil translations
    home: "முகப்பு",
    product: "தயாரிப்பு",
    technology: "தொழில்நுட்பம்",
    team: "குழு",
    investors: "முதலீட்டாளர்கள்",
    blog: "வலைப்பதிவு",
    contact: "தொடர்பு",
    tag: "⚡ AI-இயக்கப்படும் ஸ்மார்ட் விவசாயம்",
    title: "AI இயக்கப்படும் விவசாயத்தின் எதிர்காலம்",
    subtitle: "அக்ரிரோவர் ஒரு ஸ்மார்ட் ரோபோடிக் விவசாய அமைப்பு ஆகும், இது சிறிய விவசாயிகளுக்கு அவர்களின் விவசாயப் பணிகளை தானியங்குபடுத்த உதவுகிறது — துல்லியம், செயல்திறன் மற்றும் புத்திசாலித்தனத்தை கொண்டுவருகிறது.",
    exploreProduct: "தயாரிப்பை ஆராயுங்கள் →",
    contactUs: "எங்களை தொடர்பு கொள்ளுங்கள்",
    lessChemical: "குறைந்த ரசாயனப் பயன்பாடு",
    fasterOps: "விரைவான செயல்பாடுகள்",
    wirelessRange: "வயர்லெஸ் வரம்பு",
    cropCompat: "பயிர் இணக்கம்",
    coreCapabilities: "கோர் திறன்கள்",
    whatCanDo: "அக்ரிரோவர் என்ன செய்ய முடியும்",
    featuresSub: "நான்கு சக்திவாய்ந்த விவசாய மாடியூல்கள் உங்கள் முழு பயிர் சுழற்சியையும் தானியங்குபடுத்த ஒன்றாக வேலை செய்கின்றன.",
    smartSpraying: "ஸ்மார்ட் ஸ்ப்ரேயிங்",
    sprayingDesc: "தானியங்கு பூச்சிக்கொல்லி ஸ்ப்ரேயிங் துல்லியமான இலக்குடன் — ரசாயனக் கழிவை 40% வரை குறைக்கிறது.",
    seedSowing: "விதை விதைப்பு",
    sowingDesc: "ரோபோடிக் துல்லியத்துடன் துல்லியமான விதை விதைப்பு, ஒவ்வொரு முறையும் உகந்த இடைவெளி மற்றும் ஆழத்தை உறுதிப்படுத்துகிறது.",
    fertilizerSpreading: "உரப் பரப்புதல்",
    fertilizerDesc: "வயலில் சீரான உர விநியோகம் — விளைச்சலை அதிகரிக்கிறது மற்றும் கழிவை குறைக்கிறது.",
    aiNavigation: "AI வழிசெலுத்தல்",
    aiDesc: "AI-இயக்கப்படும் பாதை திட்டமிடல் மற்றும் தடையைத் தவிர்ப்புடன் வரவிருக்கும் தானியங்கு விவசாயம்.",
    ourVision: "எங்கள் பார்வை",
    visionTitle: "இந்திய விவசாயத்தின் எதிர்காலத்தை கட்டுதல்",
    visionDesc: "இந்தியாவில் 100 மில்லியனுக்கும் மேற்பட்ட சிறிய விவசாயிகள் உள்ளனர். அக்ரிரோவர் ஒவ்வொருவருக்கும் தானியங்குபடுத்தலின் சக்தியை கொடுக்க இங்கே உள்ளது — மலிவான, கடினமான மற்றும் ஒவ்வொரு வயலுக்கும் செய்யப்பட்டது.",
    ecoFriendly: "🌱 சுற்றுச்சூழல் நட்பு செயல்பாடு",
    durable: "🛡 கடினமான நிலப்பரப்புக்கு நீடித்தது",
    lowPower: "⚡ குறைந்த சக்தி நுகர்வு",
    technology: "தொழில்நுட்பம்",
    engineered: "வயல்களுக்கு வடிவமைக்கப்பட்டது",
    techDesc: "அக்ரிரோவர் ரோபோடிக்ஸ், உட்பொதிந்த அமைப்புகள் மற்றும் வயர்லெஸ் தொழில்நுட்பத்தை ஒருங்கிணைக்கிறது, இந்திய விவசாய நிலைமைகளில் செழிக்கும் ஒரு காம்பாக்ட் ஸ்மார்ட் விவசாய இயந்திரத்தை உருவாக்க.",
    embedded: "உட்பொதிந்த கட்டுப்பாடு",
    wireless: "வயர்லெஸ் தொடர்புகள்",
    mechanical: "இயந்திர",
    futureTech: "எதிர்கால தொழில்நுட்பம்",
    fullSpecs: "முழு டெக் ஸ்பெக்ஸ் →",
    systemsOnline: "⚡ அமைப்புகள் ஆன்லைன்",
    smartAgri: "ஸ்மார்ட் விவசாய ரோபோடிக்ஸ்",
    footerDesc: "புத்திசாலி ரோபோடிக் தானியங்குபடுத்தலுடன் இந்தியாவின் சிறிய விவசாயிகளை மேம்படுத்துதல். ஒரு வயல் ஒரு வயலாக, துல்லியமான விவசாயத்தின் எதிர்காலத்தை கட்டுதல்.",
    email: "info.aiagrirover@gmail.com",
    location: "இந்தியா",
    company: "நிறுவனம்",
    resources: "வளங்கள்",
    copyright: "© 2026 AI அக்ரிரோவர் | ஸ்மார்ட் விவசாய ரோபோடிக்ஸ்",
    statusOnline: "அமைப்புகள் ஆன்லைன்"
  },
  te: {
    // Telugu translations
    home: "హోమ్",
    product: "ఉత్పత్తి",
    technology: "సాంకేతికత",
    team: "టీమ్",
    investors: "పెట్టుబడిదారులు",
    blog: "బ్లాగ్",
    contact: "సంప్రదించు",
    tag: "⚡ AI-నడిపించే స్మార్ట్ వ్యవసాయం",
    title: "AI నడిపించే వ్యవసాయం యొక్క భవిష్యత్తు",
    subtitle: "అగ్రిరోవర్ ఒక స్మార్ట్ రోబోటిక్ వ్యవసాయ వ్యవస్థ ఇది చిన్న వ్యవసాయులకు వారి వ్యవసాయ పనులను ఆటోమేట్ చేయడంలో సహాయపడుతుంది — ఖచ్చితత్వం, సామర్థ్యం మరియు బుద్ధిమత్తను తెస్తుంది.",
    exploreProduct: "ఉత్పత్తిని అన్వేషించు →",
    contactUs: "మమ్మల్ని సంప్రదించండి",
    lessChemical: "తక్కువ రసాయనాల వాడకం",
    fasterOps: "వేగవంతమైన ఆపరేషన్లు",
    wirelessRange: "వైర్లెస్ పరిధి",
    cropCompat: "పంట సామర్థ్యం",
    coreCapabilities: "కోర్ సామర్థ్యాలు",
    whatCanDo: "అగ్రిరోవర్ ఏమి చేయగలదు",
    featuresSub: "నాలుగు శక్తివంతమైన వ్యవసాయ మాడ్యూల్స్ మీ మొత్తం పంట చక్రాన్ని ఆటోమేట్ చేయడానికి కలిసి పని చేస్తాయి.",
    smartSpraying: "స్మార్ట్ స్ప్రేయింగ్",
    sprayingDesc: "ఖచ్చితమైన లక్ష్యంతో ఆటోమేటెడ్ పెస్టిసైడ్ స్ప్రేయింగ్ — రసాయన కచ్చరను 40% వరకు తగ్గిస్తుంది.",
    seedSowing: "విత్తన పంతించడం",
    sowingDesc: "రోబోటిక్ ఖచ్చితత్వంతో ఖచ్చితమైన విత్తన పంతించడం, ప్రతిసారీ ఆప్టిమల్ స్పేసింగ్ మరియు డెప్త్ నిర్ధారిస్తుంది.",
    fertilizerSpreading: "ఎరువుల పంపిణీ",
    fertilizerDesc: "పొలంలో సమాన ఎరువుల పంపిణీ — దిగుబడిని పెంచుతుంది మరియు కచ్చరను తగ్గిస్తుంది.",
    aiNavigation: "AI నావిగేషన్",
    aiDesc: "AI-నడిపించే పాత్ ప్లానింగ్ మరియు అడ్డంకులను తప్పించడతో రాబోయే ఆటోనమస్ వ్యవసాయం.",
    ourVision: "మా దృష్టి",
    visionTitle: "భారత వ్యవసాయం యొక్క భవిష్యత్తును నిర్మించడం",
    visionDesc: "భారతదేశంలో 100 మిలియన్లకు పైగా చిన్న వ్యవసాయులు ఉన్నారు. అగ్రిరోవర్ ప్రతి ఒక్కరికీ ఆటోమేషన్ యొక్క శక్తిని ఇవ్వడానికి ఇక్కడ ఉంది — చౌకైన, దృఢమైన మరియు ప్రతి పొలానికి తయారు చేయబడింది.",
    ecoFriendly: "🌱 పర్యావరణ అనుకూల ఆపరేషన్",
    durable: "🛡 గట్టిగా ఉన్న ప్రాంతాలకు నిలకడైన",
    lowPower: "⚡ తక్కువ పవర్ కన్సంప్షన్",
    technology: "సాంకేతికత",
    engineered: "పొలాలకు ఇంజినీర్డ్",
    techDesc: "అగ్రిరోవర్ రోబోటిక్స్, ఎంబెడెడ్ సిస్టమ్స్ మరియు వైర్లెస్ సాంకేతికతను ఇంటిగ్రేట్ చేస్తుంది, రియల్-వరల్డ్ ఇండియన్ వ్యవసాయ పరిస్థితులలో బ్రూట్ చేసే ఒక కాంపాక్ట్ స్మార్ట్ వ్యవసాయ మెషీన్ సృష్టిస్తుంది.",
    embedded: "ఎంబెడెడ్ కంట్రోల్",
    wireless: "వైర్లెస్ కమ్యూనికేషన్స్",
    mechanical: "మెకానికల్",
    futureTech: "భవిష్యత్ సాంకేతికత",
    fullSpecs: "పూర్తి టెక్ స్పెక్స్ →",
    systemsOnline: "⚡ సిస్టమ్స్ ఆన్‌లైన్",
    smartAgri: "స్మార్ట్ వ్యవసాయ రోబోటిక్స్",
    footerDesc: "ఇంటెలిజెంట్ రోబోటిక్ ఆటోమేషన్తో ఇండియా యొక్క చిన్న వ్యవసాయులను ఎంపవర్ చేస్తోంది. ఒక పొలం ఒక పొలం, ఖచ్చితమైన వ్యవసాయం యొక్క భవిష్యత్తును నిర్మించడం.",
    email: "info.aiagrirover@gmail.com",
    location: "ఇండియా",
    company: "కంపెనీ",
    resources: "వనరులు",
    copyright: "© 2026 AI అగ్రిరోవర్ | స్మార్ట్ వ్యవసాయ రోబోటిక్స్",
    statusOnline: "సిస్టమ్స్ ఆన్‌లైన్"
  },
  pa: {
    // Punjabi translations
    home: "ਹੋਮ",
    product: "ਉਤਪਾਦ",
    technology: "ਟੈਕਨਾਲੋਜੀ",
    team: "ਟੀਮ",
    investors: "ਨਿਵੇਸ਼ਕ",
    blog: "ਬਲੌਗ",
    contact: "ਸੰਪਰਕ",
    tag: "⚡ AI-ਚਲਾਇਆ ਸਮਾਰਟ ਖੇਤੀਬਾੜੀ",
    title: "AI ਚਲਾਇਆ ਖੇਤੀਬਾੜੀ ਦਾ ਭਵਿੱਖ",
    subtitle: "ਅਗਰੀਰੋਵਰ ਇੱਕ ਸਮਾਰਟ ਰੋਬੋਟਿਕ ਖੇਤੀਬਾੜੀ ਸਿਸਟਮ ਹੈ ਜੋ ਛੋਟੇ ਕਿਸਾਨਾਂ ਨੂੰ ਉਨ੍ਹਾਂ ਦੇ ਖੇਤੀਬਾੜੀ ਕੰਮਾਂ ਨੂੰ ਆਟੋਮੇਟਿਕ ਕਰਨ ਵਿੱਚ ਮਦਦ ਕਰਦਾ ਹੈ — ਸਟੀਕਤਾ, ਕੁਸ਼ਲਤਾ ਅਤੇ ਹੁਸ਼ਿਆਰੀ ਲਿਆਉਂਦਾ ਹੈ।",
    exploreProduct: "ਉਤਪਾਦ ਦੀ ਪੜਚੋਲ ਕਰੋ →",
    contactUs: "ਸਾਡੇ ਨਾਲ ਸੰਪਰਕ ਕਰੋ",
    lessChemical: "ਘੱਟ ਰਸਾਇਣਕ ਵਰਤੋਂ",
    fasterOps: "ਤੇਜ਼ ਓਪਰੇਸ਼ਨ",
    wirelessRange: "ਵਾਇਰਲੈੱਸ ਰੇਂਜ",
    cropCompat: "ਫਸਲ ਅਨੁਕੂਲਤਾ",
    coreCapabilities: "ਕੋਰ ਸਮਰੱਥਾਵਾਂ",
    whatCanDo: "ਅਗਰੀਰੋਵਰ ਕੀ ਕਰ ਸਕਦਾ ਹੈ",
    featuresSub: "ਚਾਰ ਸ਼ਕਤੀਸ਼ਾਲੀ ਖੇਤੀਬਾੜੀ ਮੋਡਿਊਲ ਜੋ ਤੁਹਾਡੇ ਪੂਰੇ ਫਸਲ ਚੱਕਰ ਨੂੰ ਆਟੋਮੇਟਿਕ ਕਰਨ ਲਈ ਇਕੱਠੇ ਕੰਮ ਕਰਦੇ ਹਨ।",
    smartSpraying: "ਸਮਾਰਟ ਸਪਰੇਇੰਗ",
    sprayingDesc: "ਸਟੀਕ ਟਾਰਗੇਟਿੰਗ ਨਾਲ ਆਟੋਮੇਟਿਕ ਕੀਟਨਾਸ਼ਕ ਸਪਰੇਇੰਗ — ਰਸਾਇਣਕ ਬੇਕਾਰ ਨੂੰ 40% ਤੱਕ ਘਟਾਉਂਦਾ ਹੈ।",
    seedSowing: "ਬੀਜ ਬੋਣਾ",
    sowingDesc: "ਰੋਬੋਟਿਕ ਸਟੀਕਤਾ ਨਾਲ ਸਟੀਕ ਬੀਜ ਬੋਣਾ, ਹਰ ਵਾਰ ਆਪਟੀਮਲ ਸਪੇਸਿੰਗ ਅਤੇ ਡੂੰਘਾਈ ਨੂੰ ਯਕੀਨੀ ਬਣਾਉਂਦਾ ਹੈ।",
    fertilizerSpreading: "ਖਾਦ ਫੈਲਾਉਣਾ",
    fertilizerDesc: "ਖੇਤ ਵਿੱਚ ਬਰਾਬਰ ਖਾਦ ਵੰਡ — ਪੈਦਾਵਾਰ ਨੂੰ ਵਧਾਉਂਦਾ ਹੈ ਅਤੇ ਬੇਕਾਰ ਨੂੰ ਘਟਾਉਂਦਾ ਹੈ।",
    aiNavigation: "AI ਨੈਵੀਗੇਸ਼ਨ",
    aiDesc: "AI-ਚਲਾਇਆ ਮਾਰਗ ਯੋਜਨਾ ਅਤੇ ਰੁਕਾਵਟ ਟਾਲਣ ਨਾਲ ਆਉਣ ਵਾਲੀ ਆਟੋਨੋਮਸ ਖੇਤੀਬਾੜੀ।",
    ourVision: "ਸਾਡੀ ਦ੍ਰਿਸ਼ਟੀ",
    visionTitle: "ਭਾਰਤੀ ਖੇਤੀਬਾੜੀ ਦਾ ਭਵਿੱਖ ਬਣਾਉਣਾ",
    visionDesc: "ਭਾਰਤ ਵਿੱਚ 100 ਮਿਲੀਅਨ ਤੋਂ ਵੱਧ ਛੋਟੇ ਕਿਸਾਨ ਹਨ। ਅਗਰੀਰੋਵਰ ਹਰ ਇੱਕ ਨੂੰ ਆਟੋਮੇਸ਼ਨ ਦੀ ਤਾਕਤ ਦੇਣ ਲਈ ਇੱਥੇ ਹੈ — ਸਸਤਾ, ਮਜ਼ਬੂਤ ਅਤੇ ਹਰ ਖੇਤ ਲਈ ਬਣਾਇਆ ਗਿਆ।",
    ecoFriendly: "🌱 ਇਕੋ-ਫ੍ਰੈਂਡਲੀ ਓਪਰੇਸ਼ਨ",
    durable: "🛡 ਰੌਗ਼ ਟੈਰੇਨ ਲਈ ਟਿਕਾਊ",
    lowPower: "⚡ ਘੱਟ ਪਾਵਰ ਖਪਤ",
    technology: "ਟੈਕਨਾਲੋਜੀ",
    engineered: "ਖੇਤਾਂ ਲਈ ਇੰਜੀਨੀਅਰਡ",
    techDesc: "ਅਗਰੀਰੋਵਰ ਰੋਬੋਟਿਕਸ, ਐਮਬੈਡਡ ਸਿਸਟਮਾਂ ਅਤੇ ਵਾਇਰਲੈੱਸ ਟੈਕਨਾਲੋਜੀ ਨੂੰ ਇੰਟੀਗ੍ਰੇਟ ਕਰਦਾ ਹੈ ਤਾਂ ਜੋ ਅਸਲ ਦੁਨੀਆ ਦੀਆਂ ਭਾਰਤੀ ਖੇਤੀਬਾੜੀ ਹਾਲਾਤਾਂ ਵਿੱਚ ਫਲ-ਫੂਲਣ ਵਾਲੀ ਇੱਕ ਕੰਪੈਕਟ ਸਮਾਰਟ ਖੇਤੀਬਾੜੀ ਮਸ਼ੀਨ ਬਣਾਈ ਜਾ ਸਕੇ।",
    embedded: "ਐਮਬੈਡਡ ਕੰਟਰੋਲ",
    wireless: "ਵਾਇਰਲੈੱਸ ਕਮਿਊਨੀਕੇਸ਼ਨ",
    mechanical: "ਮੈਕੈਨੀਕਲ",
    futureTech: "ਭਵਿੱਖ ਦੀ ਟੈਕਨਾਲੋਜੀ",
    fullSpecs: "ਪੂਰੇ ਟੈਕ ਸਪੈਕਸ →",
    systemsOnline: "⚡ ਸਿਸਟਮ ਆਨਲਾਈਨ",
    smartAgri: "ਸਮਾਰਟ ਖੇਤੀਬਾੜੀ ਰੋਬੋਟਿਕਸ",
    footerDesc: "ਭਾਰਤ ਦੇ ਛੋਟੇ ਕਿਸਾਨਾਂ ਨੂੰ ਹੁਸ਼ਿਆਰ ਰੋਬੋਟਿਕ ਆਟੋਮੇਸ਼ਨ ਨਾਲ ਸ਼ਕਤੀਸ਼ਾਲੀ ਬਣਾਉਣਾ। ਇੱਕ ਖੇਤ ਇੱਕ ਖੇਤ, ਸਟੀਕ ਖੇਤੀਬਾੜੀ ਦਾ ਭਵਿੱਖ ਬਣਾਉਣਾ।",
    email: "info.aiagrirover@gmail.com",
    location: "ਭਾਰਤ",
    company: "ਕੰਪਨੀ",
    resources: "ਸਰੋਤ",
    copyright: "© 2026 AI ਅਗਰੀਰੋਵਰ | ਸਮਾਰਟ ਖੇਤੀਬਾੜੀ ਰੋਬੋਟਿਕਸ",
    statusOnline: "ਸਿਸਟਮ ਆਨਲਾਈਨ"
  }
};

Object.assign(translations.en, {
  linkedin: "LinkedIn",
  readMore: "Read More",
  productHeroTitle: "AgriRover – Smart Mini Farming Robot",
  productHeroSub: "A compact electric robotic system designed for small farmers to automate spraying, sowing, fertilizing and more.",
  watchDemo: "Watch Demo",
  badgeFieldReady: "Field Ready",
  badgeEcoFriendly: "Eco Friendly",
  productAboutTag: "ABOUT THE PRODUCT",
  productOneRobot: "One Robot. Many Jobs.",
  productAboutP: "AgriRover is a versatile robotic platform that brings the power of industrial-grade automation to India's small farmers. With swappable tool attachments, it handles spraying, sowing, and fertilizing — reducing labor costs and increasing yield.",
  productFeat1: "Steel frame built for Indian field conditions",
  productFeat2: "10-inch rugged wheels for uneven terrain",
  productFeat3: "Up to 1km wireless remote range",
  productFeat4: "Interchangeable tool attachment system",
  productFeat5: "Low-power, long-duration operation",
  productFeat6: "Weather-resistant enclosed electronics",
  exploreTechnology: "Explore Technology →",
  problemWeSolve: "Problem We Solve",
  probLaborTitle: "Labor Shortage",
  probLaborDesc: "Rising labor costs.",
  probCostTitle: "High Cost",
  probCostDesc: "Machines cost ₹5–8 lakh.",
  probLargeTitle: "Large Machines",
  probLargeDesc: "Not for small farms.",
  probManualTitle: "Manual Work",
  probManualDesc: "Still dependent.",
  futureUpgrades: "Future Upgrades",
  futureUpgradesList: "Mobile App • AI Automation • IoT Integration • Solar Charging",
  requestDemo: "Request Demo →",
  techPageHeroTitle: "Engineering Behind AgriRover",
  techPageHeroSub: "Advanced robotics, embedded systems and wireless tech powering smart farming.",
  sysArchitecture: "System Architecture",
  powerUnit: "Power Unit",
  controlUnit: "Control Unit",
  driveSystem: "Drive System",
  attachmentsCard: "Attachments",
  mechDesignTitle: "Mechanical Design",
  mechDesignP: "Built with rugged steel structure, compact body and terrain-ready wheels.",
  mechLi1: "Steel Frame",
  mechLi2: "Enclosed Body",
  mechLi3: "10-inch Wheels",
  mechLi4: "Compact Design",
  elecControlTitle: "Electronics & Control",
  microTitle: "Microcontroller",
  motorDriver: "Motor Driver",
  powerSysTitle: "Power System",
  safetyTitle: "Safety",
  wirelessCommTitle: "Wireless Communication",
  wlLi1: "NRF / LoRa Modules",
  wlLi2: "1KM Range",
  wlLi3: "Custom Remote",
  wlLi4: "Low Power",
  futureTechSectionTitle: "Future Technology",
  futureAiNav: "AI Navigation",
  futureIot: "IoT",
  futureMobile: "Mobile App",
  futureSolar: "Solar",
  contactPageTitle: "Contact AgriRover",
  contactPageSub: "We’d love to hear from you — farmer, investor or partner.",
  sendUsMessage: "Send Us a Message",
  contactInformation: "Contact Information",
  labelEmail: "Email",
  labelPhone: "Phone",
  labelLocation: "Location",
  placeholderName: "Your Name",
  placeholderEmail: "Your Email",
  placeholderSubject: "Subject",
  placeholderMessage: "Your Message",
  sendMessageBtn: "Send Message →",
  teamHeroLabel: "People & mission",
  teamHeroTitle: "Meet the team behind AgriRover",
  teamHeroLead: "We are building affordable, field-ready robotics so small and marginal farmers can farm with less drudgery, lower input waste, and more predictable outcomes.",
  teamStat1: "Farmer-first product decisions",
  teamStat2: "Built for Indian fields & crops",
  teamStat3: "Hardware, embedded & AI in one loop",
  valuesHeading: "How we work",
  valuesIntro: "Principles that keep AgriRover honest, useful, and shippable.",
  valueH1: "Listen before we build",
  valueP1: "We treat farmer feedback and field trials as the source of truth — not slide decks.",
  valueH2: "Reliability over hype",
  valueP2: "Simple mechanisms, testable electronics, and maintainable code beat brittle demos.",
  valueH3: "Grow the circle",
  valueP3: "We actively welcome engineers, agronomists, and partners who care about the same mission.",
  foundersHeading: "Founding team",
  foundersIntro: "The core team setting direction for product, research, and execution.",
  satyamRole: "Founder — AI & hardware",
  satyamBio: "Leads AgriRover's technical direction: mechanical and electronic design, robotics integration, and the roadmap toward intelligent automation in the field.",
  tagRobotics: "Robotics",
  tagPrototyping: "Prototyping",
  tagSystems: "Systems design",
  harishRole: "Co-founder — research & documentation",
  harishBio: "Drives research synthesis, documentation, grant and program applications, and coordination so the team can move fast without losing rigor or clarity.",
  tagResearch: "Research",
  tagGrants: "Grants & programs",
  tagOperations: "Operations",
  engSectionTitle: "What the engineering team covers",
  engSectionIntro: "Capability areas we are building (and hiring into) as AgriRover matures.",
  engMechTitle: "Mechanical & hardware",
  engMechDesc: "Chassis, actuators, power and sensors — designed for mud, dust, and long days in the sun.",
  engEmbTitle: "Embedded & firmware",
  engEmbDesc: "Microcontrollers, motor control, wireless links, and safe, deterministic behavior on the robot.",
  engSoftTitle: "Software & AI",
  engSoftDesc: "Field software, data from trials, and models that make spraying and navigation smarter over time.",
  advisorsHeading: "Advisors",
  advisorsIntro: "Domain experts who help us stress-test assumptions and stay grounded in real agriculture.",
  advAgTitle: "Agriculture advisor",
  advAgDesc: "Crop cycles, local practices, and what \"good enough\" looks like on small plots.",
  advTechTitle: "Technology mentor",
  advTechDesc: "Architecture, manufacturability, and scaling a hardware-heavy startup responsibly.",
  supportHeading: "Startup support",
  supportIntro: "Programs and mentors that back our execution and connect us to the ecosystem.",
  supInnovTitle: "Innovation programs",
  supInnovDesc: "Incubation, cohorts, and structured support as we validate and deploy.",
  supMentorsTitle: "Mentors",
  supMentorsDesc: "Operators and founders who have shipped hardware and navigated early-stage growth.",
  teamCtaTitle: "Want to join AgriRover?",
  teamCtaSub: "We are looking for engineers, makers, and researchers who want their work to show up in real fields.",
  contactUsBtn: "Contact us",
  invHeroTitle: "Invest in the Future of Farming",
  invHeroSub: "AgriRover is building affordable robotic farming solutions for millions of small farmers in India.",
  downloadPitch: "Download Pitch Deck",
  invProblemTitle: "The Problem",
  invProb1Title: "Labor Shortage",
  invProb1Desc: "Farmers face labor shortages and rising wages.",
  invProb2Title: "Expensive Machinery",
  invProb2Desc: "Traditional tractors cost ₹5–8 lakhs.",
  invProb3Title: "Small Land Holdings",
  invProb3Desc: "Most farmers have very small land sizes.",
  invProb4Title: "Manual Farming",
  invProb4Desc: "Most operations are still manual.",
  invSolutionTitle: "Our Solution",
  invSol1Title: "Compact Electric Rover",
  invSol1Desc: "Designed for small farms and narrow fields.",
  invSol2Title: "Remote Controlled",
  invSol2Desc: "Up to 1 km wireless range.",
  invSol3Title: "Multi Purpose",
  invSol3Desc: "Spraying, sowing, fertilizing & more.",
  invSol4Title: "Affordable",
  invSol4Desc: "Estimated cost under ₹1 lakh.",
  invMarketTitle: "Market Opportunity",
  invTamTitle: "TAM",
  invTamLine: "9.3 Crore Farmers",
  invTamDesc: "Total agricultural users in India.",
  invSamTitle: "SAM",
  invSamLine: "86% Small Farmers",
  invSamDesc: "Majority are small & marginal farmers.",
  invSomTitle: "SOM",
  invSomLine: "Initial Target Segment",
  invSomDesc: "Farmers with less than 2 acres land.",
  invInvestTitle: "Investment Opportunity",
  invInvestP: "AgriRover is seeking investors, accelerators and strategic partners to scale across India.",
  invCard1Title: "Seed Investment",
  invCard1Desc: "Support prototype & manufacturing stage.",
  invCard2Title: "Strategic Partners",
  invCard2Desc: "Collaborate with agri-tech companies.",
  invCard3Title: "Accelerators",
  invCard3Desc: "Join startup programs & scaling support.",
  invCtaTitle: "Interested in Investing?",
  invCtaBtn: "Contact for Investment",
  blogHeroTitle: "AgriRover Blog",
  blogHeroSub: "Insights on agriculture, robotics, and our startup journey.",
  blogLatestTitle: "Latest Articles",
  blogArt1Title: "Future of AI in Agriculture",
  blogArt1Desc: "AI & robotics are transforming modern farming.",
  blogArt2Title: "Problems of Small Farmers",
  blogArt2Desc: "High cost, low tech access & labor shortage.",
  blogArt3Title: "Why AgriRover",
  blogArt3Desc: "Built to solve real farming problems.",
  blogArt4Title: "Robotics in Farming",
  blogArt4Desc: "Automation improving efficiency & yield.",
  blogDevTitle: "Development Updates",
  blogDev1Title: "Prototype Development",
  blogDev1Desc: "Building first working model with remote system.",
  blogDev2Title: "₹50,000 Grant Received",
  blogDev2Desc: "Supported by college innovation program.",
  blogFollowTitle: "Follow Our Journey",
  blogFollowSub: "Stay updated with AgriRover progress & innovations",
  blogConnectBtn: "Connect With Us"
});

Object.assign(translations.hi, {
  linkedin: "लिंक्डइन",
  readMore: "और पढ़ें",
  productHeroTitle: "एग्रीरोवर – स्मार्ट मिनी फार्मिंग रोबोट",
  productHeroSub: "छोटे किसानों के लिए स्प्रे, बुवाई, उर्वरक और अधिक को स्वचालित करने के लिए डिज़ाइन किया गया एक कॉम्पैक्ट इलेक्ट्रिक रोबोटिक सिस्टम।",
  watchDemo: "डेमो देखें",
  badgeFieldReady: "खेत के लिए तैयार",
  badgeEcoFriendly: "पर्यावरण अनुकूल",
  productAboutTag: "उत्पाद के बारे में",
  productOneRobot: "एक रोबोट। कई काम।",
  productAboutP: "एग्रीरोवर एक बहुमुखी रोबोटिक प्लेटफ़ॉर्म है जो भारत के छोटे किसानों तक औद्योगिक-स्तर का स्वचालन लाता है। इंटरचेंजेबल टूल अटैचमेंट के साथ यह छिड़काव, बुवाई और उर्वरक को संभालता है — श्रम लागत कम करता है और उपज बढ़ाता है।",
  productFeat1: "भारतीय खेत की स्थितियों के लिए स्टील फ्रेम",
  productFeat2: "ऊबड़-खाबड़ जमीन के लिए 10 इंच मजबूत पहिए",
  productFeat3: "1 किमी तक वायरलेस रिमोट रेंज",
  productFeat4: "इंटरचेंजेबल टूल अटैचमेंट सिस्टम",
  productFeat5: "कम बिजली, लंबी अवधि संचालन",
  productFeat6: "मौसम-प्रतिरोधी बंद इलेक्ट्रॉनिक्स",
  exploreTechnology: "प्रौद्योगिकी देखें →",
  problemWeSolve: "समस्या जिसे हम हल करते हैं",
  probLaborTitle: "श्रम की कमी",
  probLaborDesc: "बढ़ती श्रम लागत।",
  probCostTitle: "उच्च लागत",
  probCostDesc: "मशीनें ₹5–8 लाख की।",
  probLargeTitle: "बड़ी मशीनें",
  probLargeDesc: "छोटे खेतों के लिए नहीं।",
  probManualTitle: "मैनुअल काम",
  probManualDesc: "अभी भी निर्भर।",
  futureUpgrades: "भविष्य के उन्नयन",
  futureUpgradesList: "मोबाइल ऐप • एआई स्वचालन • IoT एकीकरण • सौर चार्जिंग",
  requestDemo: "डेमो का अनुरोध →",
  techPageHeroTitle: "एग्रीरोवर के पीछे इंजीनियरिंग",
  techPageHeroSub: "स्मार्ट खेती को शक्ति प्रदान करने वाला उन्नत रोबोटिक्स, एम्बेडेड सिस्टम और वायरलेस तकनीक।",
  sysArchitecture: "सिस्टम आर्किटेक्चर",
  powerUnit: "पावर यूनिट",
  controlUnit: "नियंत्रण यूनिट",
  driveSystem: "ड्राइव सिस्टम",
  attachmentsCard: "अटैचमेंट",
  mechDesignTitle: "यांत्रिक डिज़ाइन",
  mechDesignP: "मजबूत स्टील संरचना, कॉम्पैक्ट बॉडी और टेरेन-रेडी पहियों के साथ निर्मित।",
  mechLi1: "स्टील फ्रेम",
  mechLi2: "बंद बॉडी",
  mechLi3: "10 इंच पहिए",
  mechLi4: "कॉम्पैक्ट डिज़ाइन",
  elecControlTitle: "इलेक्ट्रॉनिक्स और नियंत्रण",
  microTitle: "माइक्रोकंट्रोलर",
  motorDriver: "मोटर ड्राइवर",
  powerSysTitle: "पावर सिस्टम",
  safetyTitle: "सुरक्षा",
  wirelessCommTitle: "वायरलेस संचार",
  wlLi1: "NRF / LoRa मॉड्यूल",
  wlLi2: "1KM रेंज",
  wlLi3: "कस्टम रिमोट",
  wlLi4: "कम बिजली",
  futureTechSectionTitle: "भविष्य की तकनीक",
  futureAiNav: "एआई नेविगेशन",
  futureIot: "IoT",
  futureMobile: "मोबाइल ऐप",
  futureSolar: "सौर",
  contactPageTitle: "एग्रीरोवर से संपर्क करें",
  contactPageSub: "हम आपसे सुनना चाहेंगे — किसान, निवेशक या साझेदार।",
  sendUsMessage: "हमें संदेश भेजें",
  contactInformation: "संपर्क जानकारी",
  labelEmail: "ईमेल",
  labelPhone: "फ़ोन",
  labelLocation: "स्थान",
  placeholderName: "आपका नाम",
  placeholderEmail: "आपका ईमेल",
  placeholderSubject: "विषय",
  placeholderMessage: "आपका संदेश",
  sendMessageBtn: "संदेश भेजें →",
  teamHeroLabel: "लोग और मिशन",
  teamHeroTitle: "एग्रीरोवर के पीछे की टीम से मिलें",
  teamHeroLead: "हम किफायती, खेत-तैयार रोबोटिक्स बना रहे हैं ताकि छोटे और सीमांत किसान कम मेहनत, कम इनपुट बर्बादी और अधिक पूर्वानुमेय परिणामों के साथ खेती कर सकें।",
  teamStat1: "किसान-पहले उत्पाद निर्णय",
  teamStat2: "भारतीय खेतों और फसलों के लिए निर्मित",
  teamStat3: "एक लूप में हार्डवेयर, एम्बेडेड और एआई",
  valuesHeading: "हम कैसे काम करते हैं",
  valuesIntro: "सिद्धांत जो एग्रीरोवर को ईमानदार, उपयोगी और शिप करने योग्य रखते हैं।",
  valueH1: "बनाने से पहले सुनें",
  valueP1: "हम किसान प्रतिक्रिया और फील्ड ट्रायल को सच का स्रोत मानते हैं — स्लाइड डेक नहीं।",
  valueH2: "हाइप पर विश्वसनीयता",
  valueP2: "सरल तंत्र, परीक्षण योग्य इलेक्ट्रॉनिक्स और रखरखाव योग्य कोड नाजुक डेमो से बेहतर हैं।",
  valueH3: "मंडली बढ़ाएं",
  valueP3: "हम इंजीनियरों, कृषि विशेषज्ञों और साझेदारों का स्वागत करते हैं जो इसी मिशन की परवाह करते हैं।",
  foundersHeading: "संस्थापक टीम",
  foundersIntro: "उत्पाद, अनुसंधान और निष्पादन की दिशा तय करने वाली मुख्य टीम।",
  satyamRole: "संस्थापक — एआई और हार्डवेयर",
  satyamBio: "एग्रीरोवर की तकनीकी दिशा का नेतृत्व: यांत्रिक और इलेक्ट्रॉनिक डिज़ाइन, रोबोटिक्स एकीकरण, और खेत में बुद्धिमान स्वचालन की रोडमैप।",
  tagRobotics: "रोबोटिक्स",
  tagPrototyping: "प्रोटोटाइपिंग",
  tagSystems: "सिस्टम डिज़ाइन",
  harishRole: "सह-संस्थापक — अनुसंधान और दस्तावेज़ीकरण",
  harishBio: "अनुसंधान संश्लेषण, दस्तावेज़ीकरण, अनुदान और कार्यक्रम आवेदन, और समन्वय ताकि टीम गति से आगे बढ़े बिना कठोरता या स्पष्टता खोए।",
  tagResearch: "अनुसंधान",
  tagGrants: "अनुदान और कार्यक्रम",
  tagOperations: "संचालन",
  engSectionTitle: "इंजीनियरिंग टीम क्या कवर करती है",
  engSectionIntro: "क्षेत्र जिन्हें हम बना रहे हैं (और भर्ती कर रहे हैं) जैसे-जैसे एग्रीरोवर परिपक्व होता है।",
  engMechTitle: "यांत्रिक और हार्डवेयर",
  engMechDesc: "चेसिस, एक्चुएटर, पावर और सेंसर — कीचड़, धूल और धूप में लंबे दिनों के लिए डिज़ाइन।",
  engEmbTitle: "एम्बेडेड और फर्मवेयर",
  engEmbDesc: "माइक्रोकंट्रोलर, मोटर नियंत्रण, वायरलेस लिंक, और रोबोट पर सुरक्षित, निर्धारित व्यवहार।",
  engSoftTitle: "सॉफ़्टवेयर और एआई",
  engSoftDesc: "फील्ड सॉफ़्टवेयर, ट्रायल डेटा, और मॉडल जो समय के साथ छिड़काव और नेविगेशन को स्मार्ट बनाते हैं।",
  advisorsHeading: "सलाहकार",
  advisorsIntro: "क्षेत्र के विशेषज्ञ जो हमारे अनुमानों की जांच करते हैं और वास्तविक कृषि में जमीन पर रखते हैं।",
  advAgTitle: "कृषि सलाहकार",
  advAgDesc: "फसल चक्र, स्थानीय प्रथाएं, और छोटे प्लॉट पर \"अच्छा पर्याप्त\" कैसा दिखता है।",
  advTechTitle: "प्रौद्योगिकी मार्गदर्शक",
  advTechDesc: "आर्किटेक्चर, निर्माण योग्यता, और हार्डवेयर-भारी स्टार्टअप को जिम्मेदारी से स्केल करना।",
  supportHeading: "स्टार्टअप सहायता",
  supportIntro: "कार्यक्रम और मार्गदर्शक जो हमारे निष्पादन का समर्थन करते हैं और पारिस्थितिकी तंत्र से जोड़ते हैं।",
  supInnovTitle: "नवाचार कार्यक्रम",
  supInnovDesc: "इन्क्यूबेशन, कोहॉर्ट और संरचित सहायता जैसे हम मान्य करते और तैनात करते हैं।",
  supMentorsTitle: "मार्गदर्शक",
  supMentorsDesc: "ऑपरेटर और संस्थापक जिन्होंने हार्डवेयर शिप किया और प्रारंभिक वृद्धि नेविगेट की।",
  teamCtaTitle: "एग्रीरोवर में शामिल हों?",
  teamCtaSub: "हम इंजीनियरों, निर्माताओं और शोधकर्ताओं की तलाश में हैं जो चाहते हैं कि उनका काम वास्तविक खेतों में दिखे।",
  contactUsBtn: "हमसे संपर्क करें",
  invHeroTitle: "खेती के भविष्य में निवेश करें",
  invHeroSub: "एग्रीरोवर भारत में लाखों छोटे किसानों के लिए किफायती रोबोटिक खेती समाधान बना रहा है।",
  downloadPitch: "पिच डेक डाउनलोड करें",
  invProblemTitle: "समस्या",
  invProb1Title: "श्रम की कमी",
  invProb1Desc: "किसान श्रम की कमी और बढ़ती मजदूरी का सामना करते हैं।",
  invProb2Title: "महंगी मशीनरी",
  invProb2Desc: "पारंपरिक ट्रैक्टर ₹5–8 लाख की लागत करते हैं।",
  invProb3Title: "छोटे भूमि धारण",
  invProb3Desc: "अधिकांश किसानों के पास बहुत छोटी जमीन है।",
  invProb4Title: "मैनुअल खेती",
  invProb4Desc: "अधिकांश कार्य अभी भी मैनुअल हैं।",
  invSolutionTitle: "हमारा समाधान",
  invSol1Title: "कॉम्पैक्ट इलेक्ट्रिक रोवर",
  invSol1Desc: "छोटे खेतों और संकरी खेतों के लिए डिज़ाइन।",
  invSol2Title: "रिमोट नियंत्रित",
  invSol2Desc: "1 किमी तक वायरलेस रेंज।",
  invSol3Title: "बहुउद्देश्यीय",
  invSol3Desc: "छिड़काव, बुवाई, उर्वरक और अधिक।",
  invSol4Title: "किफायती",
  invSol4Desc: "अनुमानित लागत ₹1 लाख से कम।",
  invMarketTitle: "बाजार अवसर",
  invTamTitle: "TAM",
  invTamLine: "9.3 करोड़ किसान",
  invTamDesc: "भारत में कुल कृषि उपयोगकर्ता।",
  invSamTitle: "SAM",
  invSamLine: "86% छोटे किसान",
  invSamDesc: "बहुमत छोटे और सीमांत किसान हैं।",
  invSomTitle: "SOM",
  invSomLine: "प्रारंभिक लक्ष्य खंड",
  invSomDesc: "2 एकड़ से कम जमीन वाले किसान।",
  invInvestTitle: "निवेश अवसर",
  invInvestP: "एग्रीरोवर भारत भर में स्केल करने के लिए निवेशक, एक्सीलरेटर और रणनीतिक साझेदारों की तलाश में है।",
  invCard1Title: "सीड निवेश",
  invCard1Desc: "प्रोटोटाइप और निर्माण चरण का समर्थन।",
  invCard2Title: "रणनीतिक साझेदार",
  invCard2Desc: "एग्री-टेक कंपनियों के साथ सहयोग।",
  invCard3Title: "एक्सीलरेटर",
  invCard3Desc: "स्टार्टअप कार्यक्रमों और स्केलिंग सहायता में शामिल हों।",
  invCtaTitle: "निवेश में रुचि?",
  invCtaBtn: "निवेश के लिए संपर्क",
  blogHeroTitle: "एग्रीरोवर ब्लॉग",
  blogHeroSub: "कृषि, रोबोटिक्स और हमारी स्टार्टअप यात्रा पर अंतर्दृष्टि।",
  blogLatestTitle: "नवीनतम लेख",
  blogArt1Title: "कृषि में एआई का भविष्य",
  blogArt1Desc: "एआई और रोबोटिक्स आधुनिक खेती को बदल रहे हैं।",
  blogArt2Title: "छोटे किसानों की समस्याएं",
  blogArt2Desc: "उच्च लागत, कम तकनीक पहुंच और श्रम की कमी।",
  blogArt3Title: "एग्रीरोवर क्यों",
  blogArt3Desc: "वास्तविक खेती की समस्याओं को हल करने के लिए बनाया गया।",
  blogArt4Title: "खेती में रोबोटिक्स",
  blogArt4Desc: "दक्षता और उपज में सुधार के लिए स्वचालन।",
  blogDevTitle: "विकास अपडेट",
  blogDev1Title: "प्रोटोटाइप विकास",
  blogDev1Desc: "रिमोट सिस्टम के साथ पहला कार्यशील मॉडल बनाना।",
  blogDev2Title: "₹50,000 अनुदान प्राप्त",
  blogDev2Desc: "कॉलेज नवाचार कार्यक्रम द्वारा समर्थित।",
  blogFollowTitle: "हमारी यात्रा का अनुसरण करें",
  blogFollowSub: "एग्रीरोवर की प्रगति और नवाचारों के साथ अपडेट रहें",
  blogConnectBtn: "हमसे जुड़ें"
});

// Function to get current language
function getCurrentLanguage() {
  return localStorage.getItem('language') || 'en';
}

function htmlLangFromCode(lang) {
  if (lang === 'pa') return 'pa-Guru';
  return lang;
}

function syncLangToggleLabel() {
  const langBtn = document.querySelector('.lang-toggle');
  const lang = getCurrentLanguage();
  if (langBtn && languageNames[lang]) {
    langBtn.textContent = languageNames[lang];
  }
}

function closeLangDropdown() {
  const wrap = document.querySelector('.lang-dropdown');
  const toggle = document.querySelector('.lang-toggle');
  if (wrap) wrap.classList.remove('lang-dropdown--open');
  if (toggle) toggle.setAttribute('aria-expanded', 'false');
}

// Called from index.html onclick handlers — was missing before (only setLanguage existed)
function changeLanguage(lang) {
  setLanguage(lang);
  closeLangDropdown();
}

// Function to set language
function setLanguage(lang) {
  const code = translations[lang] ? lang : 'en';
  localStorage.setItem('language', code);
  document.documentElement.lang = htmlLangFromCode(code);
  updateTexts();
  syncLangToggleLabel();
}

// Function to update all texts
function updateTexts() {
  const lang = getCurrentLanguage();
  const code = translations[lang] ? lang : 'en';
  const trans = { ...translations.en, ...translations[code] };

  document.querySelectorAll('[data-key]').forEach(el => {
    const key = el.getAttribute('data-key');
    if (trans[key] !== undefined && trans[key] !== '') {
      el.textContent = trans[key];
    }
  });

  document.querySelectorAll('[data-placeholder]').forEach(el => {
    const key = el.getAttribute('data-placeholder');
    if (trans[key] !== undefined && trans[key] !== '') {
      el.placeholder = trans[key];
    }
  });
}

function initLangDropdown() {
  const wrap = document.querySelector('.lang-dropdown');
  const toggle = document.querySelector('.lang-toggle');
  if (!wrap || !toggle) return;

  toggle.addEventListener('click', (e) => {
    e.preventDefault();
    e.stopPropagation();
    const open = wrap.classList.toggle('lang-dropdown--open');
    toggle.setAttribute('aria-expanded', open ? 'true' : 'false');
  });

  wrap.addEventListener('click', (e) => e.stopPropagation());

  document.addEventListener('click', () => closeLangDropdown());

  document.addEventListener('keydown', (e) => {
    if (e.key === 'Escape') closeLangDropdown();
  });
}

document.addEventListener('DOMContentLoaded', () => {
  const lang = getCurrentLanguage();
  document.documentElement.lang = htmlLangFromCode(translations[lang] ? lang : 'en');
  updateTexts();
  syncLangToggleLabel();
  initLangDropdown();
});