// Language translations for multi-language support
const translations = {
  en: {
    // Navigation
    home: "Home",
    product: "Product",
    technology: "Technology",
    team: "Team",
    investors: "Investors",
    blog: "Blog",
    contact: "Contact",
    // Hero
    tag: "⚡ AI-Powered Smart Farming",
    title: "AI Powered Future of Farming",
    subtitle: "AgriRover is a smart robotic farming system designed to help small farmers automate their agricultural work — bringing precision, efficiency, and intelligence.",
    exploreProduct: "Explore Product →",
    contactUs: "Contact Us",
    lessChemical: "Less Chemical Use",
    fasterOps: "Faster Operations",
    wirelessRange: "Wireless Range",
    cropCompat: "Crop Compatibility",
    // Features
    coreCapabilities: "CORE CAPABILITIES",
    whatCanDo: "What AgriRover Can Do",
    featuresSub: "Four powerful farming modules that work together to automate your entire crop cycle.",
    smartSpraying: "Smart Spraying",
    sprayingDesc: "Automated pesticide spraying with precision targeting — reducing chemical waste by up to 40%.",
    seedSowing: "Seed Sowing",
    sowingDesc: "Accurate seed planting with robotic precision, ensuring optimal spacing and depth every time.",
    fertilizerSpreading: "Fertilizer Spreading",
    fertilizerDesc: "Uniform fertilizer distribution across the field — maximizing yield and minimizing waste.",
    aiNavigation: "AI Navigation",
    aiDesc: "Upcoming autonomous farming with AI-powered path planning and obstacle avoidance.",
    // Vision
    ourVision: "OUR VISION",
    visionTitle: "Building the Future of Indian Agriculture",
    visionDesc: "India has over 100 million small farmers. AgriRover is here to give each of them the power of automation — affordable, rugged, and made for every field.",
    ecoFriendly: "🌱 Eco-friendly operation",
    durable: "🛡 Durable for rough terrain",
    lowPower: "⚡ Low power consumption",
    // Technology
    technology: "TECHNOLOGY",
    engineered: "Engineered for the Fields",
    techDesc: "AgriRover integrates robotics, embedded systems, and wireless technology to create a compact smart farming machine that thrives in real-world Indian agricultural conditions.",
    embedded: "Embedded Control",
    wireless: "Wireless Comms",
    mechanical: "Mechanical",
    futureTech: "Future Tech",
    fullSpecs: "Full Tech Specs →",
    systemsOnline: "⚡ Systems Online",
    // Footer
    smartAgri: "SMART AGRICULTURE ROBOTICS",
    footerDesc: "Empowering India's small farmers with intelligent robotic automation. Building the future of precision agriculture, one field at a time.",
    email: "info.aiagrirover@gmail.com",
    location: "India",
    company: "COMPANY",
    resources: "RESOURCES",
    copyright: "© 2026 AI AgriRover | Smart Agriculture Robotics",
    statusOnline: "Systems Online"
  },
  hi: {
    // Hindi translations
    home: "होम",
    product: "उत्पाद",
    technology: "प्रौद्योगिकी",
    team: "टीम",
    investors: "निवेशक",
    blog: "ब्लॉग",
    contact: "संपर्क",
    tag: "⚡ एआई-संचालित स्मार्ट कृषि",
    title: "एआई संचालित कृषि का भविष्य",
    subtitle: "एग्रीरोवर एक स्मार्ट रोबोटिक कृषि प्रणाली है जो छोटे किसानों को उनकी कृषि कार्यों को स्वचालित करने में मदद करती है — सटीकता, दक्षता और बुद्धिमत्ता लाती है।",
    exploreProduct: "उत्पाद देखें →",
    contactUs: "हमसे संपर्क करें",
    lessChemical: "कम रासायनिक उपयोग",
    fasterOps: "तेजी से संचालन",
    wirelessRange: "वायरलेस रेंज",
    cropCompat: "फसल अनुकूलता",
    coreCapabilities: "कोर क्षमताएं",
    whatCanDo: "एग्रीरोवर क्या कर सकता है",
    featuresSub: "चार शक्तिशाली कृषि मॉड्यूल जो आपके पूरे फसल चक्र को स्वचालित करने के लिए एक साथ काम करते हैं।",
    smartSpraying: "स्मार्ट स्प्रेइंग",
    sprayingDesc: "स्वचालित कीटनाशक स्प्रेइंग सटीक लक्ष्यीकरण के साथ — रासायनिक अपशिष्ट को 40% तक कम करता है।",
    seedSowing: "बीज बोना",
    sowingDesc: "रोबोटिक सटीकता के साथ सटीक बीज रोपण, हर समय इष्टतम अंतर और गहराई सुनिश्चित करता है।",
    fertilizerSpreading: "उर्वरक फैलाना",
    fertilizerDesc: "खेत में समान उर्वरक वितरण — उपज को अधिकतम करता है और अपशिष्ट को कम करता है।",
    aiNavigation: "एआई नेविगेशन",
    aiDesc: "एआई-संचालित पथ योजना और बाधा से बचने के साथ आगामी स्वायत्त कृषि।",
    ourVision: "हमारा विजन",
    visionTitle: "भारतीय कृषि का भविष्य बनाना",
    visionDesc: "भारत में 100 मिलियन से अधिक छोटे किसान हैं। एग्रीरोवर यहां प्रत्येक को स्वचालन की शक्ति देने के लिए है — किफायती, मजबूत, और हर खेत के लिए बनाया गया।",
    ecoFriendly: "🌱 पर्यावरण-अनुकूल संचालन",
    durable: "🛡 खुरदरे इलाकों के लिए टिकाऊ",
    lowPower: "⚡ कम बिजली खपत",
    technology: "प्रौद्योगिकी",
    engineered: "खेतों के लिए इंजीनियर्ड",
    techDesc: "एग्रीरोवर रोबोटिक्स, एम्बेडेड सिस्टम और वायरलेस तकनीक को एकीकृत करता है ताकि वास्तविक दुनिया की भारतीय कृषि स्थितियों में पनपने वाली एक कॉम्पैक्ट स्मार्ट कृषि मशीन बनाई जा सके।",
    embedded: "एम्बेडेड नियंत्रण",
    wireless: "वायरलेस कम्युनिकेशन",
    mechanical: "यांत्रिक",
    futureTech: "भविष्य की तकनीक",
    fullSpecs: "पूर्ण टेक स्पेक्स →",
    systemsOnline: "⚡ सिस्टम ऑनलाइन",
    smartAgri: "स्मार्ट कृषि रोबोटिक्स",
    footerDesc: "बुद्धिमान रोबोटिक स्वचालन के साथ भारत के छोटे किसानों को सशक्त बनाना। एक समय में एक खेत, सटीक कृषि का भविष्य बनाना।",
    email: "info.aiagrirover@gmail.com",
    location: "भारत",
    company: "कंपनी",
    resources: "संसाधन",
    copyright: "© 2026 एआई एग्रीरोवर | स्मार्ट कृषि रोबोटिक्स",
    statusOnline: "सिस्टम ऑनलाइन"
  },
  mr: {
    // Marathi translations (similar structure)
    home: "मुख्यपृष्ठ",
    product: "उत्पादन",
    technology: "तंत्रज्ञान",
    team: "संघ",
    investors: "गुंतवणूकदार",
    blog: "ब्लॉग",
    contact: "संपर्क",
    tag: "⚡ एआय-चालित स्मार्ट शेती",
    title: "एआय चालित शेतीचे भविष्य",
    subtitle: "एग्रीरोवर ही स्मार्ट रोबोटिक शेती प्रणाली आहे जी लहान शेतकऱ्यांना त्यांच्या शेती कामांना स्वयंचलित करण्यात मदत करते — अचूकता, कार्यक्षमता आणि बुद्धिमत्ता आणते.",
    exploreProduct: "उत्पादन पहा →",
    contactUs: "आमच्याशी संपर्क साधा",
    lessChemical: "कमी रासायनिक वापर",
    fasterOps: "वेगवान ऑपरेशन्स",
    wirelessRange: "वायरलेस रेंज",
    cropCompat: "पीक सुसंगतता",
    coreCapabilities: "कोर क्षमता",
    whatCanDo: "एग्रीरोवर काय करू शकते",
    featuresSub: "चार शक्तिशाली शेती मॉड्यूल्स जी तुमच्या संपूर्ण पीक चक्राला स्वयंचलित करण्यासाठी एकत्र काम करतात.",
    smartSpraying: "स्मार्ट स्प्रेइंग",
    sprayingDesc: "स्वयंचलित कीटकनाशक स्प्रेइंग अचूक लक्ष्यीकरणासह — रासायनिक कचरा 40% पर्यंत कमी करते.",
    seedSowing: "बियाणे पेरणी",
    sowingDesc: "रोबोटिक अचूकतेसह अचूक बियाणे रोपण, प्रत्येक वेळी इष्टतम अंतर आणि खोली सुनिश्चित करते.",
    fertilizerSpreading: "खत पसरवणे",
    fertilizerDesc: "शेतात समान खत वितरण — उत्पादन वाढवते आणि कचरा कमी करते.",
    aiNavigation: "एआय नेव्हिगेशन",
    aiDesc: "एआय-चालित मार्ग नियोजन आणि अडथळा टाळण्यासह येणारे स्वयंचलित शेती.",
    ourVision: "आमचा दृष्टिकोन",
    visionTitle: "भारतीय शेतीचे भविष्य बांधणे",
    visionDesc: "भारतात 100 दशलक्षाहून अधिक लहान शेतकरी आहेत. एग्रीरोवर प्रत्येकाला स्वयंचलनाची शक्ती देण्यासाठी येथे आहे — परवडणारे, मजबूत आणि प्रत्येक शेतासाठी बनवलेले.",
    ecoFriendly: "🌱 पर्यावरण-अनुकूल ऑपरेशन",
    durable: "🛡 खडतर भूभागासाठी टिकाऊ",
    lowPower: "⚡ कमी पॉवर खपत",
    technology: "तंत्रज्ञान",
    engineered: "शेतांसाठी इंजिनियर्ड",
    techDesc: "एग्रीरोवर रोबोटिक्स, एम्बेडेड सिस्टम आणि वायरलेस तंत्रज्ञान एकत्रित करते जेणेकरून वास्तविक जगातील भारतीय शेती परिस्थितींमध्ये वाढणारी कॉम्पॅक्ट स्मार्ट शेती मशीन तयार करता येईल.",
    embedded: "एम्बेडेड कंट्रोल",
    wireless: "वायरलेस कम्युनिकेशन्स",
    mechanical: "यांत्रिक",
    futureTech: "भविष्याचे तंत्रज्ञान",
    fullSpecs: "पूर्ण टेक स्पेक्स →",
    systemsOnline: "⚡ सिस्टम ऑनलाइन",
    smartAgri: "स्मार्ट कृषी रोबोटिक्स",
    footerDesc: "बुद्धिमान रोबोटिक स्वयंचलनासह भारताच्या लहान शेतकऱ्यांना सशक्त बनवणे. एका वेळी एक शेत, अचूक शेतीचे भविष्य बांधणे.",
    email: "info.aiagrirover@gmail.com",
    location: "भारत",
    company: "कंपनी",
    resources: "संसाधने",
    copyright: "© 2026 एआय एग्रीरोवर | स्मार्ट कृषी रोबोटिक्स",
    statusOnline: "सिस्टम ऑनलाइन"
  },
  ta: {
    // Tamil translations
    home: "முகப்பு",
    product: "தயாரிப்பு",
    technology: "தொழில்நுட்பம்",
    team: "குழு",
    investors: "முதலீட்டாளர்கள்",
    blog: "வலைப்பதிவு",
    contact: "தொடர்பு",
    tag: "⚡ AI-இயக்கப்படும் ஸ்மார்ட் விவசாயம்",
    title: "AI இயக்கப்படும் விவசாயத்தின் எதிர்காலம்",
    subtitle: "அக்ரிரோவர் ஒரு ஸ்மார்ட் ரோபோடிக் விவசாய அமைப்பு ஆகும், இது சிறிய விவசாயிகளுக்கு அவர்களின் விவசாயப் பணிகளை தானியங்குபடுத்த உதவுகிறது — துல்லியம், செயல்திறன் மற்றும் புத்திசாலித்தனத்தை கொண்டுவருகிறது.",
    exploreProduct: "தயாரிப்பை ஆராயுங்கள் →",
    contactUs: "எங்களை தொடர்பு கொள்ளுங்கள்",
    lessChemical: "குறைந்த ரசாயனப் பயன்பாடு",
    fasterOps: "விரைவான செயல்பாடுகள்",
    wirelessRange: "வயர்லெஸ் வரம்பு",
    cropCompat: "பயிர் இணக்கம்",
    coreCapabilities: "கோர் திறன்கள்",
    whatCanDo: "அக்ரிரோவர் என்ன செய்ய முடியும்",
    featuresSub: "நான்கு சக்திவாய்ந்த விவசாய மாடியூல்கள் உங்கள் முழு பயிர் சுழற்சியையும் தானியங்குபடுத்த ஒன்றாக வேலை செய்கின்றன.",
    smartSpraying: "ஸ்மார்ட் ஸ்ப்ரேயிங்",
    sprayingDesc: "தானியங்கு பூச்சிக்கொல்லி ஸ்ப்ரேயிங் துல்லியமான இலக்குடன் — ரசாயனக் கழிவை 40% வரை குறைக்கிறது.",
    seedSowing: "விதை விதைப்பு",
    sowingDesc: "ரோபோடிக் துல்லியத்துடன் துல்லியமான விதை விதைப்பு, ஒவ்வொரு முறையும் உகந்த இடைவெளி மற்றும் ஆழத்தை உறுதிப்படுத்துகிறது.",
    fertilizerSpreading: "உரப் பரப்புதல்",
    fertilizerDesc: "வயலில் சீரான உர விநியோகம் — விளைச்சலை அதிகரிக்கிறது மற்றும் கழிவை குறைக்கிறது.",
    aiNavigation: "AI வழிசெலுத்தல்",
    aiDesc: "AI-இயக்கப்படும் பாதை திட்டமிடல் மற்றும் தடையைத் தவிர்ப்புடன் வரவிருக்கும் தானியங்கு விவசாயம்.",
    ourVision: "எங்கள் பார்வை",
    visionTitle: "இந்திய விவசாயத்தின் எதிர்காலத்தை கட்டுதல்",
    visionDesc: "இந்தியாவில் 100 மில்லியனுக்கும் மேற்பட்ட சிறிய விவசாயிகள் உள்ளனர். அக்ரிரோவர் ஒவ்வொருவருக்கும் தானியங்குபடுத்தலின் சக்தியை கொடுக்க இங்கே உள்ளது — மலிவான, கடினமான மற்றும் ஒவ்வொரு வயலுக்கும் செய்யப்பட்டது.",
    ecoFriendly: "🌱 சுற்றுச்சூழல் நட்பு செயல்பாடு",
    durable: "🛡 கடினமான நிலப்பரப்புக்கு நீடித்தது",
    lowPower: "⚡ குறைந்த சக்தி நுகர்வு",
    technology: "தொழில்நுட்பம்",
    engineered: "வயல்களுக்கு வடிவமைக்கப்பட்டது",
    techDesc: "அக்ரிரோவர் ரோபோடிக்ஸ், உட்பொதிந்த அமைப்புகள் மற்றும் வயர்லெஸ் தொழில்நுட்பத்தை ஒருங்கிணைக்கிறது, இந்திய விவசாய நிலைமைகளில் செழிக்கும் ஒரு காம்பாக்ட் ஸ்மார்ட் விவசாய இயந்திரத்தை உருவாக்க.",
    embedded: "உட்பொதிந்த கட்டுப்பாடு",
    wireless: "வயர்லெஸ் தொடர்புகள்",
    mechanical: "இயந்திர",
    futureTech: "எதிர்கால தொழில்நுட்பம்",
    fullSpecs: "முழு டெக் ஸ்பெக்ஸ் →",
    systemsOnline: "⚡ அமைப்புகள் ஆன்லைன்",
    smartAgri: "ஸ்மார்ட் விவசாய ரோபோடிக்ஸ்",
    footerDesc: "புத்திசாலி ரோபோடிக் தானியங்குபடுத்தலுடன் இந்தியாவின் சிறிய விவசாயிகளை மேம்படுத்துதல். ஒரு வயல் ஒரு வயலாக, துல்லியமான விவசாயத்தின் எதிர்காலத்தை கட்டுதல்.",
    email: "info.aiagrirover@gmail.com",
    location: "இந்தியா",
    company: "நிறுவனம்",
    resources: "வளங்கள்",
    copyright: "© 2026 AI அக்ரிரோவர் | ஸ்மார்ட் விவசாய ரோபோடிக்ஸ்",
    statusOnline: "அமைப்புகள் ஆன்லைன்"
  },
  te: {
    // Telugu translations
    home: "హోమ్",
    product: "ఉత్పత్తి",
    technology: "సాంకేతికత",
    team: "టీమ్",
    investors: "పెట్టుబడిదారులు",
    blog: "బ్లాగ్",
    contact: "సంప్రదించు",
    tag: "⚡ AI-నడిపించే స్మార్ట్ వ్యవసాయం",
    title: "AI నడిపించే వ్యవసాయం యొక్క భవిష్యత్తు",
    subtitle: "అగ్రిరోవర్ ఒక స్మార్ట్ రోబోటిక్ వ్యవసాయ వ్యవస్థ ఇది చిన్న వ్యవసాయులకు వారి వ్యవసాయ పనులను ఆటోమేట్ చేయడంలో సహాయపడుతుంది — ఖచ్చితత్వం, సామర్థ్యం మరియు బుద్ధిమత్తను తెస్తుంది.",
    exploreProduct: "ఉత్పత్తిని అన్వేషించు →",
    contactUs: "మమ్మల్ని సంప్రదించండి",
    lessChemical: "తక్కువ రసాయనాల వాడకం",
    fasterOps: "వేగవంతమైన ఆపరేషన్లు",
    wirelessRange: "వైర్లెస్ పరిధి",
    cropCompat: "పంట సామర్థ్యం",
    coreCapabilities: "కోర్ సామర్థ్యాలు",
    whatCanDo: "అగ్రిరోవర్ ఏమి చేయగలదు",
    featuresSub: "నాలుగు శక్తివంతమైన వ్యవసాయ మాడ్యూల్స్ మీ మొత్తం పంట చక్రాన్ని ఆటోమేట్ చేయడానికి కలిసి పని చేస్తాయి.",
    smartSpraying: "స్మార్ట్ స్ప్రేయింగ్",
    sprayingDesc: "ఖచ్చితమైన లక్ష్యంతో ఆటోమేటెడ్ పెస్టిసైడ్ స్ప్రేయింగ్ — రసాయన కచ్చరను 40% వరకు తగ్గిస్తుంది.",
    seedSowing: "విత్తన పంతించడం",
    sowingDesc: "రోబోటిక్ ఖచ్చితత్వంతో ఖచ్చితమైన విత్తన పంతించడం, ప్రతిసారీ ఆప్టిమల్ స్పేసింగ్ మరియు డెప్త్ నిర్ధారిస్తుంది.",
    fertilizerSpreading: "ఎరువుల పంపిణీ",
    fertilizerDesc: "పొలంలో సమాన ఎరువుల పంపిణీ — దిగుబడిని పెంచుతుంది మరియు కచ్చరను తగ్గిస్తుంది.",
    aiNavigation: "AI నావిగేషన్",
    aiDesc: "AI-నడిపించే పాత్ ప్లానింగ్ మరియు అడ్డంకులను తప్పించడతో రాబోయే ఆటోనమస్ వ్యవసాయం.",
    ourVision: "మా దృష్టి",
    visionTitle: "భారత వ్యవసాయం యొక్క భవిష్యత్తును నిర్మించడం",
    visionDesc: "భారతదేశంలో 100 మిలియన్లకు పైగా చిన్న వ్యవసాయులు ఉన్నారు. అగ్రిరోవర్ ప్రతి ఒక్కరికీ ఆటోమేషన్ యొక్క శక్తిని ఇవ్వడానికి ఇక్కడ ఉంది — చౌకైన, దృఢమైన మరియు ప్రతి పొలానికి తయారు చేయబడింది.",
    ecoFriendly: "🌱 పర్యావరణ అనుకూల ఆపరేషన్",
    durable: "🛡 గట్టిగా ఉన్న ప్రాంతాలకు నిలకడైన",
    lowPower: "⚡ తక్కువ పవర్ కన్సంప్షన్",
    technology: "సాంకేతికత",
    engineered: "పొలాలకు ఇంజినీర్డ్",
    techDesc: "అగ్రిరోవర్ రోబోటిక్స్, ఎంబెడెడ్ సిస్టమ్స్ మరియు వైర్లెస్ సాంకేతికతను ఇంటిగ్రేట్ చేస్తుంది, రియల్-వరల్డ్ ఇండియన్ వ్యవసాయ పరిస్థితులలో బ్రూట్ చేసే ఒక కాంపాక్ట్ స్మార్ట్ వ్యవసాయ మెషీన్ సృష్టిస్తుంది.",
    embedded: "ఎంబెడెడ్ కంట్రోల్",
    wireless: "వైర్లెస్ కమ్యూనికేషన్స్",
    mechanical: "మెకానికల్",
    futureTech: "భవిష్యత్ సాంకేతికత",
    fullSpecs: "పూర్తి టెక్ స్పెక్స్ →",
    systemsOnline: "⚡ సిస్టమ్స్ ఆన్‌లైన్",
    smartAgri: "స్మార్ట్ వ్యవసాయ రోబోటిక్స్",
    footerDesc: "ఇంటెలిజెంట్ రోబోటిక్ ఆటోమేషన్తో ఇండియా యొక్క చిన్న వ్యవసాయులను ఎంపవర్ చేస్తోంది. ఒక పొలం ఒక పొలం, ఖచ్చితమైన వ్యవసాయం యొక్క భవిష్యత్తును నిర్మించడం.",
    email: "info.aiagrirover@gmail.com",
    location: "ఇండియా",
    company: "కంపెనీ",
    resources: "వనరులు",
    copyright: "© 2026 AI అగ్రిరోవర్ | స్మార్ట్ వ్యవసాయ రోబోటిక్స్",
    statusOnline: "సిస్టమ్స్ ఆన్‌లైన్"
  },
  pa: {
    // Punjabi translations
    home: "ਹੋਮ",
    product: "ਉਤਪਾਦ",
    technology: "ਟੈਕਨਾਲੋਜੀ",
    team: "ਟੀਮ",
    investors: "ਨਿਵੇਸ਼ਕ",
    blog: "ਬਲੌਗ",
    contact: "ਸੰਪਰਕ",
    tag: "⚡ AI-ਚਲਾਇਆ ਸਮਾਰਟ ਖੇਤੀਬਾੜੀ",
    title: "AI ਚਲਾਇਆ ਖੇਤੀਬਾੜੀ ਦਾ ਭਵਿੱਖ",
    subtitle: "ਅਗਰੀਰੋਵਰ ਇੱਕ ਸਮਾਰਟ ਰੋਬੋਟਿਕ ਖੇਤੀਬਾੜੀ ਸਿਸਟਮ ਹੈ ਜੋ ਛੋਟੇ ਕਿਸਾਨਾਂ ਨੂੰ ਉਨ੍ਹਾਂ ਦੇ ਖੇਤੀਬਾੜੀ ਕੰਮਾਂ ਨੂੰ ਆਟੋਮੇਟਿਕ ਕਰਨ ਵਿੱਚ ਮਦਦ ਕਰਦਾ ਹੈ — ਸਟੀਕਤਾ, ਕੁਸ਼ਲਤਾ ਅਤੇ ਹੁਸ਼ਿਆਰੀ ਲਿਆਉਂਦਾ ਹੈ।",
    exploreProduct: "ਉਤਪਾਦ ਦੀ ਪੜਚੋਲ ਕਰੋ →",
    contactUs: "ਸਾਡੇ ਨਾਲ ਸੰਪਰਕ ਕਰੋ",
    lessChemical: "ਘੱਟ ਰਸਾਇਣਕ ਵਰਤੋਂ",
    fasterOps: "ਤੇਜ਼ ਓਪਰੇਸ਼ਨ",
    wirelessRange: "ਵਾਇਰਲੈੱਸ ਰੇਂਜ",
    cropCompat: "ਫਸਲ ਅਨੁਕੂਲਤਾ",
    coreCapabilities: "ਕੋਰ ਸਮਰੱਥਾਵਾਂ",
    whatCanDo: "ਅਗਰੀਰੋਵਰ ਕੀ ਕਰ ਸਕਦਾ ਹੈ",
    featuresSub: "ਚਾਰ ਸ਼ਕਤੀਸ਼ਾਲੀ ਖੇਤੀਬਾੜੀ ਮੋਡਿਊਲ ਜੋ ਤੁਹਾਡੇ ਪੂਰੇ ਫਸਲ ਚੱਕਰ ਨੂੰ ਆਟੋਮੇਟਿਕ ਕਰਨ ਲਈ ਇਕੱਠੇ ਕੰਮ ਕਰਦੇ ਹਨ।",
    smartSpraying: "ਸਮਾਰਟ ਸਪਰੇਇੰਗ",
    sprayingDesc: "ਸਟੀਕ ਟਾਰਗੇਟਿੰਗ ਨਾਲ ਆਟੋਮੇਟਿਕ ਕੀਟਨਾਸ਼ਕ ਸਪਰੇਇੰਗ — ਰਸਾਇਣਕ ਬੇਕਾਰ ਨੂੰ 40% ਤੱਕ ਘਟਾਉਂਦਾ ਹੈ।",
    seedSowing: "ਬੀਜ ਬੋਣਾ",
    sowingDesc: "ਰੋਬੋਟਿਕ ਸਟੀਕਤਾ ਨਾਲ ਸਟੀਕ ਬੀਜ ਬੋਣਾ, ਹਰ ਵਾਰ ਆਪਟੀਮਲ ਸਪੇਸਿੰਗ ਅਤੇ ਡੂੰਘਾਈ ਨੂੰ ਯਕੀਨੀ ਬਣਾਉਂਦਾ ਹੈ।",
    fertilizerSpreading: "ਖਾਦ ਫੈਲਾਉਣਾ",
    fertilizerDesc: "ਖੇਤ ਵਿੱਚ ਬਰਾਬਰ ਖਾਦ ਵੰਡ — ਪੈਦਾਵਾਰ ਨੂੰ ਵਧਾਉਂਦਾ ਹੈ ਅਤੇ ਬੇਕਾਰ ਨੂੰ ਘਟਾਉਂਦਾ ਹੈ।",
    aiNavigation: "AI ਨੈਵੀਗੇਸ਼ਨ",
    aiDesc: "AI-ਚਲਾਇਆ ਮਾਰਗ ਯੋਜਨਾ ਅਤੇ ਰੁਕਾਵਟ ਟਾਲਣ ਨਾਲ ਆਉਣ ਵਾਲੀ ਆਟੋਨੋਮਸ ਖੇਤੀਬਾੜੀ।",
    ourVision: "ਸਾਡੀ ਦ੍ਰਿਸ਼ਟੀ",
    visionTitle: "ਭਾਰਤੀ ਖੇਤੀਬਾੜੀ ਦਾ ਭਵਿੱਖ ਬਣਾਉਣਾ",
    visionDesc: "ਭਾਰਤ ਵਿੱਚ 100 ਮਿਲੀਅਨ ਤੋਂ ਵੱਧ ਛੋਟੇ ਕਿਸਾਨ ਹਨ। ਅਗਰੀਰੋਵਰ ਹਰ ਇੱਕ ਨੂੰ ਆਟੋਮੇਸ਼ਨ ਦੀ ਤਾਕਤ ਦੇਣ ਲਈ ਇੱਥੇ ਹੈ — ਸਸਤਾ, ਮਜ਼ਬੂਤ ਅਤੇ ਹਰ ਖੇਤ ਲਈ ਬਣਾਇਆ ਗਿਆ।",
    ecoFriendly: "🌱 ਇਕੋ-ਫ੍ਰੈਂਡਲੀ ਓਪਰੇਸ਼ਨ",
    durable: "🛡 ਰੌਗ਼ ਟੈਰੇਨ ਲਈ ਟਿਕਾਊ",
    lowPower: "⚡ ਘੱਟ ਪਾਵਰ ਖਪਤ",
    technology: "ਟੈਕਨਾਲੋਜੀ",
    engineered: "ਖੇਤਾਂ ਲਈ ਇੰਜੀਨੀਅਰਡ",
    techDesc: "ਅਗਰੀਰੋਵਰ ਰੋਬੋਟਿਕਸ, ਐਮਬੈਡਡ ਸਿਸਟਮਾਂ ਅਤੇ ਵਾਇਰਲੈੱਸ ਟੈਕਨਾਲੋਜੀ ਨੂੰ ਇੰਟੀਗ੍ਰੇਟ ਕਰਦਾ ਹੈ ਤਾਂ ਜੋ ਅਸਲ ਦੁਨੀਆ ਦੀਆਂ ਭਾਰਤੀ ਖੇਤੀਬਾੜੀ ਹਾਲਾਤਾਂ ਵਿੱਚ ਫਲ-ਫੂਲਣ ਵਾਲੀ ਇੱਕ ਕੰਪੈਕਟ ਸਮਾਰਟ ਖੇਤੀਬਾੜੀ ਮਸ਼ੀਨ ਬਣਾਈ ਜਾ ਸਕੇ।",
    embedded: "ਐਮਬੈਡਡ ਕੰਟਰੋਲ",
    wireless: "ਵਾਇਰਲੈੱਸ ਕਮਿਊਨੀਕੇਸ਼ਨ",
    mechanical: "ਮੈਕੈਨੀਕਲ",
    futureTech: "ਭਵਿੱਖ ਦੀ ਟੈਕਨਾਲੋਜੀ",
    fullSpecs: "ਪੂਰੇ ਟੈਕ ਸਪੈਕਸ →",
    systemsOnline: "⚡ ਸਿਸਟਮ ਆਨਲਾਈਨ",
    smartAgri: "ਸਮਾਰਟ ਖੇਤੀਬਾੜੀ ਰੋਬੋਟਿਕਸ",
    footerDesc: "ਭਾਰਤ ਦੇ ਛੋਟੇ ਕਿਸਾਨਾਂ ਨੂੰ ਹੁਸ਼ਿਆਰ ਰੋਬੋਟਿਕ ਆਟੋਮੇਸ਼ਨ ਨਾਲ ਸ਼ਕਤੀਸ਼ਾਲੀ ਬਣਾਉਣਾ। ਇੱਕ ਖੇਤ ਇੱਕ ਖੇਤ, ਸਟੀਕ ਖੇਤੀਬਾੜੀ ਦਾ ਭਵਿੱਖ ਬਣਾਉਣਾ।",
    email: "info.aiagrirover@gmail.com",
    location: "ਭਾਰਤ",
    company: "ਕੰਪਨੀ",
    resources: "ਸਰੋਤ",
    copyright: "© 2026 AI ਅਗਰੀਰੋਵਰ | ਸਮਾਰਟ ਖੇਤੀਬਾੜੀ ਰੋਬੋਟਿਕਸ",
    statusOnline: "ਸਿਸਟਮ ਆਨਲਾਈਨ"
  }
};

// Function to get current language
function getCurrentLanguage() {
  return localStorage.getItem('language') || 'en';
}

// Function to set language
function setLanguage(lang) {
  localStorage.setItem('language', lang);
  updateTexts();
}

// Function to update all texts
function updateTexts() {
  const lang = getCurrentLanguage();
  const trans = translations[lang] || translations['en'];

  // Update elements with data-key
  document.querySelectorAll('[data-key]').forEach(el => {
    const key = el.getAttribute('data-key');
    if (trans[key]) {
      el.textContent = trans[key];
    }
  });

  // Update placeholders
  document.querySelectorAll('[data-placeholder]').forEach(el => {
    const key = el.getAttribute('data-placeholder');
    if (trans[key]) {
      el.placeholder = trans[key];
    }
  });
}

// Initialize language on load
document.addEventListener('DOMContentLoaded', updateTexts);