// Language display names in native script
const languageNames = {
  en: "English",
  hi: "हिन्दी",
  mr: "मराठी",
  ta: "தமிழ்",
  te: "తెలుగు",
  pa: "ਪੰਜਾਬੀ"
};

// ─────────────────────────────────────────────
// BASE TRANSLATIONS (nav, hero, index sections, footer)
// ─────────────────────────────────────────────
const translations = {
  en: {
    home: "Home", product: "Product", technology: "Technology",
    team: "Team", investors: "Investors", blog: "Blog", contact: "Contact",
    tag: "⚡ AI-Powered Smart Farming",
    title: "AI Powered Future of Farming",
    subtitle: "AgriRover is a smart robotic farming system designed to help small farmers automate their agricultural work — bringing precision, efficiency, and intelligence.",
    exploreProduct: "Explore Product →", contactUs: "Contact Us",
    lessChemical: "Less Chemical Use", fasterOps: "Faster Operations",
    wirelessRange: "Wireless Range", cropCompat: "Crop Compatibility",
    coreCapabilities: "CORE CAPABILITIES", whatCanDo: "What AgriRover Can Do",
    featuresSub: "Four powerful farming modules that work together to automate your entire crop cycle.",
    smartSpraying: "Smart Spraying",
    sprayingDesc: "Automated pesticide spraying with precision targeting — reducing chemical waste by up to 40%.",
    seedSowing: "Seed Sowing",
    sowingDesc: "Accurate seed planting with robotic precision, ensuring optimal spacing and depth every time.",
    fertilizerSpreading: "Fertilizer Spreading",
    fertilizerDesc: "Uniform fertilizer distribution across the field — maximizing yield and minimizing waste.",
    aiNavigation: "AI Navigation",
    aiDesc: "Upcoming autonomous farming with AI-powered path planning and obstacle avoidance.",
    ourVision: "OUR VISION", visionTitle: "Building the Future of Indian Agriculture",
    visionDesc: "India has over 100 million small farmers. AgriRover is here to give each of them the power of automation — affordable, rugged, and made for every field.",
    ecoFriendly: "🌱 Eco-friendly operation", durable: "🛡 Durable for rough terrain", lowPower: "⚡ Low power consumption",
    technology: "TECHNOLOGY", engineered: "Engineered for the Fields",
    techDesc: "AgriRover integrates robotics, embedded systems, and wireless technology to create a compact smart farming machine that thrives in real-world Indian agricultural conditions.",
    embedded: "Embedded Control", wireless: "Wireless Comms", mechanical: "Mechanical", futureTech: "Future Tech",
    fullSpecs: "Full Tech Specs →", systemsOnline: "⚡ Systems Online",
    smartAgri: "SMART AGRICULTURE ROBOTICS",
    footerDesc: "Empowering India's small farmers with intelligent robotic automation. Building the future of precision agriculture, one field at a time.",
    email: "info.aiagrirover@gmail.com", location: "India", company: "COMPANY", resources: "RESOURCES",
    copyright: "© 2026 AI AgriRover | Smart Agriculture Robotics", statusOnline: "Systems Online"
  },
  hi: {
    home: "होम", product: "उत्पाद", technology: "प्रौद्योगिकी",
    team: "टीम", investors: "निवेशक", blog: "ब्लॉग", contact: "संपर्क",
    tag: "⚡ एआई-संचालित स्मार्ट कृषि",
    title: "एआई संचालित कृषि का भविष्य",
    subtitle: "एग्रीरोवर एक स्मार्ट रोबोटिक कृषि प्रणाली है जो छोटे किसानों को उनकी कृषि कार्यों को स्वचालित करने में मदद करती है — सटीकता, दक्षता और बुद्धिमत्ता लाती है।",
    exploreProduct: "उत्पाद देखें →", contactUs: "हमसे संपर्क करें",
    lessChemical: "कम रासायनिक उपयोग", fasterOps: "तेजी से संचालन",
    wirelessRange: "वायरलेस रेंज", cropCompat: "फसल अनुकूलता",
    coreCapabilities: "कोर क्षमताएं", whatCanDo: "एग्रीरोवर क्या कर सकता है",
    featuresSub: "चार शक्तिशाली कृषि मॉड्यूल जो आपके पूरे फसल चक्र को स्वचालित करने के लिए एक साथ काम करते हैं।",
    smartSpraying: "स्मार्ट स्प्रेइंग",
    sprayingDesc: "स्वचालित कीटनाशक स्प्रेइंग सटीक लक्ष्यीकरण के साथ — रासायनिक अपशिष्ट को 40% तक कम करता है।",
    seedSowing: "बीज बोना",
    sowingDesc: "रोबोटिक सटीकता के साथ सटीक बीज रोपण, हर समय इष्टतम अंतर और गहराई सुनिश्चित करता है।",
    fertilizerSpreading: "उर्वरक फैलाना",
    fertilizerDesc: "खेत में समान उर्वरक वितरण — उपज को अधिकतम करता है और अपशिष्ट को कम करता है।",
    aiNavigation: "एआई नेविगेशन",
    aiDesc: "एआई-संचालित पथ योजना और बाधा से बचने के साथ आगामी स्वायत्त कृषि।",
    ourVision: "हमारा विजन", visionTitle: "भारतीय कृषि का भविष्य बनाना",
    visionDesc: "भारत में 100 मिलियन से अधिक छोटे किसान हैं। एग्रीरोवर यहां प्रत्येक को स्वचालन की शक्ति देने के लिए है — किफायती, मजबूत, और हर खेत के लिए बनाया गया।",
    ecoFriendly: "🌱 पर्यावरण-अनुकूल संचालन", durable: "🛡 खुरदरे इलाकों के लिए टिकाऊ", lowPower: "⚡ कम बिजली खपत",
    technology: "प्रौद्योगिकी", engineered: "खेतों के लिए इंजीनियर्ड",
    techDesc: "एग्रीरोवर रोबोटिक्स, एम्बेडेड सिस्टम और वायरलेस तकनीक को एकीकृत करता है ताकि वास्तविक दुनिया की भारतीय कृषि स्थितियों में पनपने वाली एक कॉम्पैक्ट स्मार्ट कृषि मशीन बनाई जा सके।",
    embedded: "एम्बेडेड नियंत्रण", wireless: "वायरलेस कम्युनिकेशन", mechanical: "यांत्रिक", futureTech: "भविष्य की तकनीक",
    fullSpecs: "पूर्ण टेक स्पेक्स →", systemsOnline: "⚡ सिस्टम ऑनलाइन",
    smartAgri: "स्मार्ट कृषि रोबोटिक्स",
    footerDesc: "बुद्धिमान रोबोटिक स्वचालन के साथ भारत के छोटे किसानों को सशक्त बनाना। एक समय में एक खेत, सटीक कृषि का भविष्य बनाना।",
    email: "info.aiagrirover@gmail.com", location: "भारत", company: "कंपनी", resources: "संसाधन",
    copyright: "© 2026 एआई एग्रीरोवर | स्मार्ट कृषि रोबोटिक्स", statusOnline: "सिस्टम ऑनलाइन"
  },
  mr: {
    home: "मुख्यपृष्ठ", product: "उत्पादन", technology: "तंत्रज्ञान",
    team: "संघ", investors: "गुंतवणूकदार", blog: "ब्लॉग", contact: "संपर्क",
    tag: "⚡ एआय-चालित स्मार्ट शेती",
    title: "एआय चालित शेतीचे भविष्य",
    subtitle: "एग्रीरोवर ही स्मार्ट रोबोटिक शेती प्रणाली आहे जी लहान शेतकऱ्यांना त्यांच्या शेती कामांना स्वयंचलित करण्यात मदत करते — अचूकता, कार्यक्षमता आणि बुद्धिमत्ता आणते.",
    exploreProduct: "उत्पादन पहा →", contactUs: "आमच्याशी संपर्क साधा",
    lessChemical: "कमी रासायनिक वापर", fasterOps: "वेगवान ऑपरेशन्स",
    wirelessRange: "वायरलेस रेंज", cropCompat: "पीक सुसंगतता",
    coreCapabilities: "कोर क्षमता", whatCanDo: "एग्रीरोवर काय करू शकते",
    featuresSub: "चार शक्तिशाली शेती मॉड्यूल्स जी तुमच्या संपूर्ण पीक चक्राला स्वयंचलित करण्यासाठी एकत्र काम करतात.",
    smartSpraying: "स्मार्ट स्प्रेइंग",
    sprayingDesc: "स्वयंचलित कीटकनाशक स्प्रेइंग अचूक लक्ष्यीकरणासह — रासायनिक कचरा 40% पर्यंत कमी करते.",
    seedSowing: "बियाणे पेरणी",
    sowingDesc: "रोबोटिक अचूकतेसह अचूक बियाणे रोपण, प्रत्येक वेळी इष्टतम अंतर आणि खोली सुनिश्चित करते.",
    fertilizerSpreading: "खत पसरवणे",
    fertilizerDesc: "शेतात समान खत वितरण — उत्पादन वाढवते आणि कचरा कमी करते.",
    aiNavigation: "एआय नेव्हिगेशन",
    aiDesc: "एआय-चालित मार्ग नियोजन आणि अडथळा टाळण्यासह येणारे स्वयंचलित शेती.",
    ourVision: "आमचा दृष्टिकोन", visionTitle: "भारतीय शेतीचे भविष्य बांधणे",
    visionDesc: "भारतात 100 दशलक्षाहून अधिक लहान शेतकरी आहेत. एग्रीरोवर प्रत्येकाला स्वयंचलनाची शक्ती देण्यासाठी येथे आहे — परवडणारे, मजबूत आणि प्रत्येक शेतासाठी बनवलेले.",
    ecoFriendly: "🌱 पर्यावरण-अनुकूल ऑपरेशन", durable: "🛡 खडतर भूभागासाठी टिकाऊ", lowPower: "⚡ कमी पॉवर खपत",
    technology: "तंत्रज्ञान", engineered: "शेतांसाठी इंजिनियर्ड",
    techDesc: "एग्रीरोवर रोबोटिक्स, एम्बेडेड सिस्टम आणि वायरलेस तंत्रज्ञान एकत्रित करते जेणेकरून वास्तविक जगातील भारतीय शेती परिस्थितींमध्ये वाढणारी कॉम्पॅक्ट स्मार्ट शेती मशीन तयार करता येईल.",
    embedded: "एम्बेडेड कंट्रोल", wireless: "वायरलेस कम्युनिकेशन्स", mechanical: "यांत्रिक", futureTech: "भविष्याचे तंत्रज्ञान",
    fullSpecs: "पूर्ण टेक स्पेक्स →", systemsOnline: "⚡ सिस्टम ऑनलाइन",
    smartAgri: "स्मार्ट कृषी रोबोटिक्स",
    footerDesc: "बुद्धिमान रोबोटिक स्वयंचलनासह भारताच्या लहान शेतकऱ्यांना सशक्त बनवणे. एका वेळी एक शेत, अचूक शेतीचे भविष्य बांधणे.",
    email: "info.aiagrirover@gmail.com", location: "भारत", company: "कंपनी", resources: "संसाधने",
    copyright: "© 2026 एआय एग्रीरोवर | स्मार्ट कृषी रोबोटिक्स", statusOnline: "सिस्टम ऑनलाइन"
  },
  ta: {
    home: "முகப்பு", product: "தயாரிப்பு", technology: "தொழில்நுட்பம்",
    team: "குழு", investors: "முதலீட்டாளர்கள்", blog: "வலைப்பதிவு", contact: "தொடர்பு",
    tag: "⚡ AI-இயக்கப்படும் ஸ்மார்ட் விவசாயம்",
    title: "AI இயக்கப்படும் விவசாயத்தின் எதிர்காலம்",
    subtitle: "அக்ரிரோவர் ஒரு ஸ்மார்ட் ரோபோடிக் விவசாய அமைப்பு, இது சிறிய விவசாயிகளுக்கு அவர்களின் விவசாயப் பணிகளை தானியங்குபடுத்த உதவுகிறது — துல்லியம், செயல்திறன் மற்றும் புத்திசாலித்தனத்தை கொண்டுவருகிறது.",
    exploreProduct: "தயாரிப்பை ஆராயுங்கள் →", contactUs: "எங்களை தொடர்பு கொள்ளுங்கள்",
    lessChemical: "குறைந்த ரசாயனப் பயன்பாடு", fasterOps: "விரைவான செயல்பாடுகள்",
    wirelessRange: "வயர்லெஸ் வரம்பு", cropCompat: "பயிர் இணக்கம்",
    coreCapabilities: "கோர் திறன்கள்", whatCanDo: "அக்ரிரோவர் என்ன செய்ய முடியும்",
    featuresSub: "நான்கு சக்திவாய்ந்த விவசாய மாடியூல்கள் உங்கள் முழு பயிர் சுழற்சியையும் தானியங்குபடுத்த ஒன்றாக வேலை செய்கின்றன.",
    smartSpraying: "ஸ்மார்ட் ஸ்ப்ரேயிங்",
    sprayingDesc: "தானியங்கு பூச்சிக்கொல்லி ஸ்ப்ரேயிங் துல்லியமான இலக்குடன் — ரசாயனக் கழிவை 40% வரை குறைக்கிறது.",
    seedSowing: "விதை விதைப்பு",
    sowingDesc: "ரோபோடிக் துல்லியத்துடன் துல்லியமான விதை விதைப்பு, ஒவ்வொரு முறையும் உகந்த இடைவெளி மற்றும் ஆழத்தை உறுதிப்படுத்துகிறது.",
    fertilizerSpreading: "உரப் பரப்புதல்",
    fertilizerDesc: "வயலில் சீரான உர விநியோகம் — விளைச்சலை அதிகரிக்கிறது மற்றும் கழிவை குறைக்கிறது.",
    aiNavigation: "AI வழிசெலுத்தல்",
    aiDesc: "AI-இயக்கப்படும் பாதை திட்டமிடல் மற்றும் தடையைத் தவிர்ப்புடன் வரவிருக்கும் தானியங்கு விவசாயம்.",
    ourVision: "எங்கள் பார்வை", visionTitle: "இந்திய விவசாயத்தின் எதிர்காலத்தை கட்டுதல்",
    visionDesc: "இந்தியாவில் 100 மில்லியனுக்கும் மேற்பட்ட சிறிய விவசாயிகள் உள்ளனர். அக்ரிரோவர் ஒவ்வொருவருக்கும் தானியங்குபடுத்தலின் சக்தியை கொடுக்க இங்கே உள்ளது — மலிவான, கடினமான மற்றும் ஒவ்வொரு வயலுக்கும் செய்யப்பட்டது.",
    ecoFriendly: "🌱 சுற்றுச்சூழல் நட்பு செயல்பாடு", durable: "🛡 கடினமான நிலப்பரப்புக்கு நீடித்தது", lowPower: "⚡ குறைந்த சக்தி நுகர்வு",
    technology: "தொழில்நுட்பம்", engineered: "வயல்களுக்கு வடிவமைக்கப்பட்டது",
    techDesc: "அக்ரிரோவர் ரோபோடிக்ஸ், உட்பொதிந்த அமைப்புகள் மற்றும் வயர்லெஸ் தொழில்நுட்பத்தை ஒருங்கிணைக்கிறது, இந்திய விவசாய நிலைமைகளில் செழிக்கும் ஒரு காம்பாக்ட் ஸ்மார்ட் விவசாய இயந்திரத்தை உருவாக்க.",
    embedded: "உட்பொதிந்த கட்டுப்பாடு", wireless: "வயர்லெஸ் தொடர்புகள்", mechanical: "இயந்திர", futureTech: "எதிர்கால தொழில்நுட்பம்",
    fullSpecs: "முழு டெக் ஸ்பெக்ஸ் →", systemsOnline: "⚡ அமைப்புகள் ஆன்லைன்",
    smartAgri: "ஸ்மார்ட் விவசாய ரோபோடிக்ஸ்",
    footerDesc: "புத்திசாலி ரோபோடிக் தானியங்குபடுத்தலுடன் இந்தியாவின் சிறிய விவசாயிகளை மேம்படுத்துதல். ஒரு வயல் ஒரு வயலாக, துல்லியமான விவசாயத்தின் எதிர்காலத்தை கட்டுதல்.",
    email: "info.aiagrirover@gmail.com", location: "இந்தியா", company: "நிறுவனம்", resources: "வளங்கள்",
    copyright: "© 2026 AI அக்ரிரோவர் | ஸ்மார்ட் விவசாய ரோபோடிக்ஸ்", statusOnline: "அமைப்புகள் ஆன்லைன்"
  },
  te: {
    home: "హోమ్", product: "ఉత్పత్తి", technology: "సాంకేతికత",
    team: "టీమ్", investors: "పెట్టుబడిదారులు", blog: "బ్లాగ్", contact: "సంప్రదించు",
    tag: "⚡ AI-నడిపించే స్మార్ట్ వ్యవసాయం",
    title: "AI నడిపించే వ్యవసాయం యొక్క భవిష్యత్తు",
    subtitle: "అగ్రిరోవర్ ఒక స్మార్ట్ రోబోటిక్ వ్యవసాయ వ్యవస్థ — ఇది చిన్న వ్యవసాయులకు వారి వ్యవసాయ పనులను ఆటోమేట్ చేయడంలో సహాయపడుతుంది — ఖచ్చితత్వం, సామర్థ్యం మరియు బుద్ధిమత్తను తెస్తుంది.",
    exploreProduct: "ఉత్పత్తిని అన్వేషించు →", contactUs: "మమ్మల్ని సంప్రదించండి",
    lessChemical: "తక్కువ రసాయనాల వాడకం", fasterOps: "వేగవంతమైన ఆపరేషన్లు",
    wirelessRange: "వైర్లెస్ పరిధి", cropCompat: "పంట సామర్థ్యం",
    coreCapabilities: "కోర్ సామర్థ్యాలు", whatCanDo: "అగ్రిరోవర్ ఏమి చేయగలదు",
    featuresSub: "నాలుగు శక్తివంతమైన వ్యవసాయ మాడ్యూల్స్ మీ మొత్తం పంట చక్రాన్ని ఆటోమేట్ చేయడానికి కలిసి పని చేస్తాయి.",
    smartSpraying: "స్మార్ట్ స్ప్రేయింగ్",
    sprayingDesc: "ఖచ్చితమైన లక్ష్యంతో ఆటోమేటెడ్ పెస్టిసైడ్ స్ప్రేయింగ్ — రసాయన వ్యర్థాన్ని 40% వరకు తగ్గిస్తుంది.",
    seedSowing: "విత్తన నాటడం",
    sowingDesc: "రోబోటిక్ ఖచ్చితత్వంతో ఖచ్చితమైన విత్తన నాటడం, ప్రతిసారీ ఆప్టిమల్ స్పేసింగ్ మరియు డెప్త్ నిర్ధారిస్తుంది.",
    fertilizerSpreading: "ఎరువుల పంపిణీ",
    fertilizerDesc: "పొలంలో సమాన ఎరువుల పంపిణీ — దిగుబడిని పెంచుతుంది మరియు వ్యర్థాన్ని తగ్గిస్తుంది.",
    aiNavigation: "AI నావిగేషన్",
    aiDesc: "AI-నడిపించే పాత్ ప్లానింగ్ మరియు అడ్డంకులను తప్పించడతో రాబోయే ఆటోనమస్ వ్యవసాయం.",
    ourVision: "మా దృష్టి", visionTitle: "భారత వ్యవసాయం యొక్క భవిష్యత్తును నిర్మించడం",
    visionDesc: "భారతదేశంలో 100 మిలియన్లకు పైగా చిన్న వ్యవసాయులు ఉన్నారు. అగ్రిరోవర్ ప్రతి ఒక్కరికీ ఆటోమేషన్ యొక్క శక్తిని ఇవ్వడానికి ఇక్కడ ఉంది — చౌకైన, దృఢమైన మరియు ప్రతి పొలానికి తయారు చేయబడింది.",
    ecoFriendly: "🌱 పర్యావరణ అనుకూల ఆపరేషన్", durable: "🛡 కఠినమైన భూభాగానికి నిలకడైన", lowPower: "⚡ తక్కువ పవర్ కన్సంప్షన్",
    technology: "సాంకేతికత", engineered: "పొలాలకు ఇంజినీర్డ్",
    techDesc: "అగ్రిరోవర్ రోబోటిక్స్, ఎంబెడెడ్ సిస్టమ్స్ మరియు వైర్లెస్ సాంకేతికతను ఇంటిగ్రేట్ చేస్తుంది, వాస్తవ-ప్రపంచ భారతీయ వ్యవసాయ పరిస్థితులలో పనిచేసే ఒక కాంపాక్ట్ స్మార్ట్ వ్యవసాయ మెషీన్ సృష్టిస్తుంది.",
    embedded: "ఎంబెడెడ్ కంట్రోల్", wireless: "వైర్లెస్ కమ్యూనికేషన్స్", mechanical: "మెకానికల్", futureTech: "భవిష్యత్ సాంకేతికత",
    fullSpecs: "పూర్తి టెక్ స్పెక్స్ →", systemsOnline: "⚡ సిస్టమ్స్ ఆన్‌లైన్",
    smartAgri: "స్మార్ట్ వ్యవసాయ రోబోటిక్స్",
    footerDesc: "ఇంటెలిజెంట్ రోబోటిక్ ఆటోమేషన్‌తో ఇండియా యొక్క చిన్న వ్యవసాయులను ఎంపవర్ చేస్తోంది. ఒక పొలం ఒక పొలం, ఖచ్చితమైన వ్యవసాయం యొక్క భవిష్యత్తును నిర్మించడం.",
    email: "info.aiagrirover@gmail.com", location: "ఇండియా", company: "కంపెనీ", resources: "వనరులు",
    copyright: "© 2026 AI అగ్రిరోవర్ | స్మార్ట్ వ్యవసాయ రోబోటిక్స్", statusOnline: "సిస్టమ్స్ ఆన్‌లైన్"
  },
  pa: {
    home: "ਹੋਮ", product: "ਉਤਪਾਦ", technology: "ਟੈਕਨਾਲੋਜੀ",
    team: "ਟੀਮ", investors: "ਨਿਵੇਸ਼ਕ", blog: "ਬਲੌਗ", contact: "ਸੰਪਰਕ",
    tag: "⚡ AI-ਚਲਾਇਆ ਸਮਾਰਟ ਖੇਤੀਬਾੜੀ",
    title: "AI ਚਲਾਇਆ ਖੇਤੀਬਾੜੀ ਦਾ ਭਵਿੱਖ",
    subtitle: "ਅਗਰੀਰੋਵਰ ਇੱਕ ਸਮਾਰਟ ਰੋਬੋਟਿਕ ਖੇਤੀਬਾੜੀ ਸਿਸਟਮ ਹੈ ਜੋ ਛੋਟੇ ਕਿਸਾਨਾਂ ਨੂੰ ਉਨ੍ਹਾਂ ਦੇ ਖੇਤੀਬਾੜੀ ਕੰਮਾਂ ਨੂੰ ਆਟੋਮੇਟਿਕ ਕਰਨ ਵਿੱਚ ਮਦਦ ਕਰਦਾ ਹੈ — ਸਟੀਕਤਾ, ਕੁਸ਼ਲਤਾ ਅਤੇ ਹੁਸ਼ਿਆਰੀ ਲਿਆਉਂਦਾ ਹੈ।",
    exploreProduct: "ਉਤਪਾਦ ਦੀ ਪੜਚੋਲ ਕਰੋ →", contactUs: "ਸਾਡੇ ਨਾਲ ਸੰਪਰਕ ਕਰੋ",
    lessChemical: "ਘੱਟ ਰਸਾਇਣਕ ਵਰਤੋਂ", fasterOps: "ਤੇਜ਼ ਓਪਰੇਸ਼ਨ",
    wirelessRange: "ਵਾਇਰਲੈੱਸ ਰੇਂਜ", cropCompat: "ਫਸਲ ਅਨੁਕੂਲਤਾ",
    coreCapabilities: "ਕੋਰ ਸਮਰੱਥਾਵਾਂ", whatCanDo: "ਅਗਰੀਰੋਵਰ ਕੀ ਕਰ ਸਕਦਾ ਹੈ",
    featuresSub: "ਚਾਰ ਸ਼ਕਤੀਸ਼ਾਲੀ ਖੇਤੀਬਾੜੀ ਮੋਡਿਊਲ ਜੋ ਤੁਹਾਡੇ ਪੂਰੇ ਫਸਲ ਚੱਕਰ ਨੂੰ ਆਟੋਮੇਟਿਕ ਕਰਨ ਲਈ ਇਕੱਠੇ ਕੰਮ ਕਰਦੇ ਹਨ।",
    smartSpraying: "ਸਮਾਰਟ ਸਪਰੇਇੰਗ",
    sprayingDesc: "ਸਟੀਕ ਟਾਰਗੇਟਿੰਗ ਨਾਲ ਆਟੋਮੇਟਿਕ ਕੀਟਨਾਸ਼ਕ ਸਪਰੇਇੰਗ — ਰਸਾਇਣਕ ਬੇਕਾਰ ਨੂੰ 40% ਤੱਕ ਘਟਾਉਂਦਾ ਹੈ।",
    seedSowing: "ਬੀਜ ਬੋਣਾ",
    sowingDesc: "ਰੋਬੋਟਿਕ ਸਟੀਕਤਾ ਨਾਲ ਸਟੀਕ ਬੀਜ ਬੋਣਾ, ਹਰ ਵਾਰ ਆਪਟੀਮਲ ਸਪੇਸਿੰਗ ਅਤੇ ਡੂੰਘਾਈ ਨੂੰ ਯਕੀਨੀ ਬਣਾਉਂਦਾ ਹੈ।",
    fertilizerSpreading: "ਖਾਦ ਫੈਲਾਉਣਾ",
    fertilizerDesc: "ਖੇਤ ਵਿੱਚ ਬਰਾਬਰ ਖਾਦ ਵੰਡ — ਪੈਦਾਵਾਰ ਨੂੰ ਵਧਾਉਂਦਾ ਹੈ ਅਤੇ ਬੇਕਾਰ ਨੂੰ ਘਟਾਉਂਦਾ ਹੈ।",
    aiNavigation: "AI ਨੈਵੀਗੇਸ਼ਨ",
    aiDesc: "AI-ਚਲਾਇਆ ਮਾਰਗ ਯੋਜਨਾ ਅਤੇ ਰੁਕਾਵਟ ਟਾਲਣ ਨਾਲ ਆਉਣ ਵਾਲੀ ਆਟੋਨੋਮਸ ਖੇਤੀਬਾੜੀ।",
    ourVision: "ਸਾਡੀ ਦ੍ਰਿਸ਼ਟੀ", visionTitle: "ਭਾਰਤੀ ਖੇਤੀਬਾੜੀ ਦਾ ਭਵਿੱਖ ਬਣਾਉਣਾ",
    visionDesc: "ਭਾਰਤ ਵਿੱਚ 100 ਮਿਲੀਅਨ ਤੋਂ ਵੱਧ ਛੋਟੇ ਕਿਸਾਨ ਹਨ। ਅਗਰੀਰੋਵਰ ਹਰ ਇੱਕ ਨੂੰ ਆਟੋਮੇਸ਼ਨ ਦੀ ਤਾਕਤ ਦੇਣ ਲਈ ਇੱਥੇ ਹੈ — ਸਸਤਾ, ਮਜ਼ਬੂਤ ਅਤੇ ਹਰ ਖੇਤ ਲਈ ਬਣਾਇਆ ਗਿਆ।",
    ecoFriendly: "🌱 ਇਕੋ-ਫ੍ਰੈਂਡਲੀ ਓਪਰੇਸ਼ਨ", durable: "🛡 ਰੌਗ਼ ਟੈਰੇਨ ਲਈ ਟਿਕਾਊ", lowPower: "⚡ ਘੱਟ ਪਾਵਰ ਖਪਤ",
    technology: "ਟੈਕਨਾਲੋਜੀ", engineered: "ਖੇਤਾਂ ਲਈ ਇੰਜੀਨੀਅਰਡ",
    techDesc: "ਅਗਰੀਰੋਵਰ ਰੋਬੋਟਿਕਸ, ਐਮਬੈਡਡ ਸਿਸਟਮਾਂ ਅਤੇ ਵਾਇਰਲੈੱਸ ਟੈਕਨਾਲੋਜੀ ਨੂੰ ਇੰਟੀਗ੍ਰੇਟ ਕਰਦਾ ਹੈ ਤਾਂ ਜੋ ਅਸਲ ਦੁਨੀਆ ਦੀਆਂ ਭਾਰਤੀ ਖੇਤੀਬਾੜੀ ਹਾਲਾਤਾਂ ਵਿੱਚ ਫਲ-ਫੂਲਣ ਵਾਲੀ ਇੱਕ ਕੰਪੈਕਟ ਸਮਾਰਟ ਖੇਤੀਬਾੜੀ ਮਸ਼ੀਨ ਬਣਾਈ ਜਾ ਸਕੇ।",
    embedded: "ਐਮਬੈਡਡ ਕੰਟਰੋਲ", wireless: "ਵਾਇਰਲੈੱਸ ਕਮਿਊਨੀਕੇਸ਼ਨ", mechanical: "ਮੈਕੈਨੀਕਲ", futureTech: "ਭਵਿੱਖ ਦੀ ਟੈਕਨਾਲੋਜੀ",
    fullSpecs: "ਪੂਰੇ ਟੈਕ ਸਪੈਕਸ →", systemsOnline: "⚡ ਸਿਸਟਮ ਆਨਲਾਈਨ",
    smartAgri: "ਸਮਾਰਟ ਖੇਤੀਬਾੜੀ ਰੋਬੋਟਿਕਸ",
    footerDesc: "ਭਾਰਤ ਦੇ ਛੋਟੇ ਕਿਸਾਨਾਂ ਨੂੰ ਹੁਸ਼ਿਆਰ ਰੋਬੋਟਿਕ ਆਟੋਮੇਸ਼ਨ ਨਾਲ ਸ਼ਕਤੀਸ਼ਾਲੀ ਬਣਾਉਣਾ। ਇੱਕ ਖੇਤ ਇੱਕ ਖੇਤ, ਸਟੀਕ ਖੇਤੀਬਾੜੀ ਦਾ ਭਵਿੱਖ ਬਣਾਉਣਾ।",
    email: "info.aiagrirover@gmail.com", location: "ਭਾਰਤ", company: "ਕੰਪਨੀ", resources: "ਸਰੋਤ",
    copyright: "© 2026 AI ਅਗਰੀਰੋਵਰ | ਸਮਾਰਟ ਖੇਤੀਬਾੜੀ ਰੋਬੋਟਿਕਸ", statusOnline: "ਸਿਸਟਮ ਆਨਲਾਈਨ"
  }
};

// ─────────────────────────────────────────────
// PAGE-SPECIFIC KEYS — ENGLISH
// ─────────────────────────────────────────────
Object.assign(translations.en, {
  linkedin: "LinkedIn", readMore: "Read More",
  // Product page
  productHeroTitle: "AgriRover – Smart Mini Farming Robot",
  productHeroSub: "A compact electric robotic system designed for small farmers to automate spraying, sowing, fertilizing and more.",
  watchDemo: "Watch Demo",
  badgeFieldReady: "🛡 Field Ready", badgeEcoFriendly: "🌱 Eco Friendly",
  productAboutTag: "ABOUT THE PRODUCT", productOneRobot: "One Robot. Many Jobs.",
  productAboutP: "AgriRover is a versatile robotic platform that brings the power of industrial-grade automation to India's small farmers. With swappable tool attachments, it handles spraying, sowing, and fertilizing — reducing labor costs and increasing yield.",
  productFeat1: "✔ Steel frame built for Indian field conditions",
  productFeat2: "✔ 10-inch rugged wheels for uneven terrain",
  productFeat3: "✔ Up to 1km wireless remote range",
  productFeat4: "✔ Interchangeable tool attachment system",
  productFeat5: "✔ Low-power, long-duration operation",
  productFeat6: "✔ Weather-resistant enclosed electronics",
  exploreTechnology: "Explore Technology →",
  problemWeSolve: "Problem We Solve",
  probLaborTitle: "Labor Shortage", probLaborDesc: "Rising labor costs.",
  probCostTitle: "High Cost", probCostDesc: "Machines cost ₹5–8 lakh.",
  probLargeTitle: "Large Machines", probLargeDesc: "Not for small farms.",
  probManualTitle: "Manual Work", probManualDesc: "Still dependent.",
  futureUpgrades: "Future Upgrades",
  futureUpgradesList: "Mobile App • AI Automation • IoT Integration • Solar Charging",
  requestDemo: "Request Demo →",
  // Technology page
  techPageHeroTitle: "Engineering Behind AgriRover",
  techPageHeroSub: "Advanced robotics, embedded systems and wireless tech powering smart farming.",
  sysArchitecture: "System Architecture",
  powerUnit: "Power Unit", controlUnit: "Control Unit", driveSystem: "Drive System", attachmentsCard: "Attachments",
  mechDesignTitle: "Mechanical Design",
  mechDesignP: "Built with rugged steel structure, compact body and terrain-ready wheels.",
  mechLi1: "✔ Steel Frame", mechLi2: "✔ Enclosed Body", mechLi3: "✔ 10-inch Wheels", mechLi4: "✔ Compact Design",
  elecControlTitle: "Electronics & Control",
  microTitle: "Microcontroller", motorDriver: "Motor Driver", powerSysTitle: "Power System", safetyTitle: "Safety",
  wirelessCommTitle: "Wireless Communication",
  wlLi1: "✔ NRF / LoRa Modules", wlLi2: "✔ 1KM Range", wlLi3: "✔ Custom Remote", wlLi4: "✔ Low Power",
  futureTechSectionTitle: "Future Technology",
  futureAiNav: "AI Navigation", futureIot: "IoT", futureMobile: "Mobile App", futureSolar: "Solar",
  // Contact page
  contactPageTitle: "Contact AgriRover",
  contactPageSub: "We'd love to hear from you — farmer, investor or partner.",
  sendUsMessage: "Send Us a Message", contactInformation: "Contact Information",
  labelEmail: "Email", labelPhone: "Phone", labelLocation: "Location",
  placeholderName: "Your Name", placeholderEmail: "Your Email",
  placeholderSubject: "Subject", placeholderMessage: "Your Message",
  sendMessageBtn: "Send Message →",
  // Team page
  teamHeroLabel: "People & mission",
  teamHeroTitle: "Meet the team behind AgriRover",
  teamHeroLead: "We are building affordable, field-ready robotics so small and marginal farmers can farm with less drudgery, lower input waste, and more predictable outcomes.",
  teamStat1: "Farmer-first product decisions",
  teamStat2: "Built for Indian fields & crops",
  teamStat3: "Hardware, embedded & AI in one loop",
  valuesHeading: "How we work",
  valuesIntro: "Principles that keep AgriRover honest, useful, and shippable.",
  valueH1: "Listen before we build",
  valueP1: "We treat farmer feedback and field trials as the source of truth — not slide decks.",
  valueH2: "Reliability over hype",
  valueP2: "Simple mechanisms, testable electronics, and maintainable code beat brittle demos.",
  valueH3: "Grow the circle",
  valueP3: "We actively welcome engineers, agronomists, and partners who care about the same mission.",
  foundersHeading: "Founding team",
  foundersIntro: "The core team setting direction for product, research, and execution.",
  satyamRole: "Founder — AI & hardware",
  satyamBio: "Leads AgriRover's technical direction: mechanical and electronic design, robotics integration, and the roadmap toward intelligent automation in the field.",
  tagRobotics: "Robotics", tagPrototyping: "Prototyping", tagSystems: "Systems design",
  harishRole: "Co-founder — research & documentation",
  harishBio: "Drives research synthesis, documentation, grant and program applications, and coordination so the team can move fast without losing rigor or clarity.",
  tagResearch: "Research", tagGrants: "Grants & programs", tagOperations: "Operations",
  engSectionTitle: "What the engineering team covers",
  engSectionIntro: "Capability areas we are building (and hiring into) as AgriRover matures.",
  engMechTitle: "Mechanical & hardware",
  engMechDesc: "Chassis, actuators, power and sensors — designed for mud, dust, and long days in the sun.",
  engEmbTitle: "Embedded & firmware",
  engEmbDesc: "Microcontrollers, motor control, wireless links, and safe, deterministic behavior on the robot.",
  engSoftTitle: "Software & AI",
  engSoftDesc: "Field software, data from trials, and models that make spraying and navigation smarter over time.",
  advisorsHeading: "Advisors",
  advisorsIntro: "Domain experts who help us stress-test assumptions and stay grounded in real agriculture.",
  advAgTitle: "Agriculture advisor",
  advAgDesc: "Crop cycles, local practices, and what \"good enough\" looks like on small plots.",
  advTechTitle: "Technology mentor",
  advTechDesc: "Architecture, manufacturability, and scaling a hardware-heavy startup responsibly.",
  supportHeading: "Startup support",
  supportIntro: "Programs and mentors that back our execution and connect us to the ecosystem.",
  supInnovTitle: "Innovation programs",
  supInnovDesc: "Incubation, cohorts, and structured support as we validate and deploy.",
  supMentorsTitle: "Mentors",
  supMentorsDesc: "Operators and founders who have shipped hardware and navigated early-stage growth.",
  teamCtaTitle: "Want to join AgriRover?",
  teamCtaSub: "We are looking for engineers, makers, and researchers who want their work to show up in real fields.",
  contactUsBtn: "Contact us",
  // Investors page
  invHeroTitle: "Invest in the Future of Farming",
  invHeroSub: "AgriRover is building affordable robotic farming solutions for millions of small farmers in India.",
  downloadPitch: "Download Pitch Deck",
  invProblemTitle: "The Problem",
  invProb1Title: "Labor Shortage", invProb1Desc: "Farmers face labor shortages and rising wages.",
  invProb2Title: "Expensive Machinery", invProb2Desc: "Traditional tractors cost ₹5–8 lakhs.",
  invProb3Title: "Small Land Holdings", invProb3Desc: "Most farmers have very small land sizes.",
  invProb4Title: "Manual Farming", invProb4Desc: "Most operations are still manual.",
  invSolutionTitle: "Our Solution",
  invSol1Title: "Compact Electric Rover", invSol1Desc: "Designed for small farms and narrow fields.",
  invSol2Title: "Remote Controlled", invSol2Desc: "Up to 1 km wireless range.",
  invSol3Title: "Multi Purpose", invSol3Desc: "Spraying, sowing, fertilizing & more.",
  invSol4Title: "Affordable", invSol4Desc: "Estimated cost under ₹1 lakh.",
  invMarketTitle: "Market Opportunity",
  invTamTitle: "TAM", invTamLine: "9.3 Crore Farmers", invTamDesc: "Total agricultural users in India.",
  invSamTitle: "SAM", invSamLine: "86% Small Farmers", invSamDesc: "Majority are small & marginal farmers.",
  invSomTitle: "SOM", invSomLine: "Initial Target Segment", invSomDesc: "Farmers with less than 2 acres land.",
  invInvestTitle: "Investment Opportunity",
  invInvestP: "AgriRover is seeking investors, accelerators and strategic partners to scale across India.",
  invCard1Title: "Seed Investment", invCard1Desc: "Support prototype & manufacturing stage.",
  invCard2Title: "Strategic Partners", invCard2Desc: "Collaborate with agri-tech companies.",
  invCard3Title: "Accelerators", invCard3Desc: "Join startup programs & scaling support.",
  invCtaTitle: "Interested in Investing?", invCtaBtn: "Contact for Investment",
  // Blog page
  blogHeroTitle: "AgriRover Blog",
  blogHeroSub: "Insights on agriculture, robotics, and our startup journey.",
  blogLatestTitle: "Latest Articles",
  blogArt1Title: "Future of AI in Agriculture", blogArt1Desc: "AI & robotics are transforming modern farming.",
  blogArt2Title: "Problems of Small Farmers", blogArt2Desc: "High cost, low tech access & labor shortage.",
  blogArt3Title: "Why AgriRover", blogArt3Desc: "Built to solve real farming problems.",
  blogArt4Title: "Robotics in Farming", blogArt4Desc: "Automation improving efficiency & yield.",
  blogDevTitle: "Development Updates",
  blogDev1Title: "Prototype Development", blogDev1Desc: "Building first working model with remote system.",
  blogDev2Title: "₹50,000 Grant Received", blogDev2Desc: "Supported by college innovation program.",
  blogFollowTitle: "Follow Our Journey",
  blogFollowSub: "Stay updated with AgriRover progress & innovations",
  blogConnectBtn: "Connect With Us"
});

// ─────────────────────────────────────────────
// PAGE-SPECIFIC KEYS — HINDI
// ─────────────────────────────────────────────
Object.assign(translations.hi, {
  linkedin: "लिंक्डइन", readMore: "और पढ़ें",
  productHeroTitle: "एग्रीरोवर – स्मार्ट मिनी फार्मिंग रोबोट",
  productHeroSub: "छोटे किसानों के लिए स्प्रे, बुवाई, उर्वरक और अधिक को स्वचालित करने के लिए डिज़ाइन किया गया एक कॉम्पैक्ट इलेक्ट्रिक रोबोटिक सिस्टम।",
  watchDemo: "डेमो देखें",
  badgeFieldReady: "🛡 खेत के लिए तैयार", badgeEcoFriendly: "🌱 पर्यावरण अनुकूल",
  productAboutTag: "उत्पाद के बारे में", productOneRobot: "एक रोबोट। कई काम।",
  productAboutP: "एग्रीरोवर एक बहुमुखी रोबोटिक प्लेटफ़ॉर्म है जो भारत के छोटे किसानों तक औद्योगिक-स्तर का स्वचालन लाता है। इंटरचेंजेबल टूल अटैचमेंट के साथ यह छिड़काव, बुवाई और उर्वरक को संभालता है — श्रम लागत कम करता है और उपज बढ़ाता है।",
  productFeat1: "✔ भारतीय खेत की स्थितियों के लिए स्टील फ्रेम",
  productFeat2: "✔ ऊबड़-खाबड़ जमीन के लिए 10 इंच मजबूत पहिए",
  productFeat3: "✔ 1 किमी तक वायरलेस रिमोट रेंज",
  productFeat4: "✔ इंटरचेंजेबल टूल अटैचमेंट सिस्टम",
  productFeat5: "✔ कम बिजली, लंबी अवधि संचालन",
  productFeat6: "✔ मौसम-प्रतिरोधी बंद इलेक्ट्रॉनिक्स",
  exploreTechnology: "प्रौद्योगिकी देखें →",
  problemWeSolve: "समस्या जिसे हम हल करते हैं",
  probLaborTitle: "श्रम की कमी", probLaborDesc: "बढ़ती श्रम लागत।",
  probCostTitle: "उच्च लागत", probCostDesc: "मशीनें ₹5–8 लाख की।",
  probLargeTitle: "बड़ी मशीनें", probLargeDesc: "छोटे खेतों के लिए नहीं।",
  probManualTitle: "मैनुअल काम", probManualDesc: "अभी भी निर्भर।",
  futureUpgrades: "भविष्य के उन्नयन",
  futureUpgradesList: "मोबाइल ऐप • एआई स्वचालन • IoT एकीकरण • सौर चार्जिंग",
  requestDemo: "डेमो का अनुरोध →",
  techPageHeroTitle: "एग्रीरोवर के पीछे इंजीनियरिंग",
  techPageHeroSub: "स्मार्ट खेती को शक्ति प्रदान करने वाला उन्नत रोबोटिक्स, एम्बेडेड सिस्टम और वायरलेस तकनीक।",
  sysArchitecture: "सिस्टम आर्किटेक्चर",
  powerUnit: "पावर यूनिट", controlUnit: "नियंत्रण यूनिट", driveSystem: "ड्राइव सिस्टम", attachmentsCard: "अटैचमेंट",
  mechDesignTitle: "यांत्रिक डिज़ाइन",
  mechDesignP: "मजबूत स्टील संरचना, कॉम्पैक्ट बॉडी और टेरेन-रेडी पहियों के साथ निर्मित।",
  mechLi1: "✔ स्टील फ्रेम", mechLi2: "✔ बंद बॉडी", mechLi3: "✔ 10 इंच पहिए", mechLi4: "✔ कॉम्पैक्ट डिज़ाइन",
  elecControlTitle: "इलेक्ट्रॉनिक्स और नियंत्रण",
  microTitle: "माइक्रोकंट्रोलर", motorDriver: "मोटर ड्राइवर", powerSysTitle: "पावर सिस्टम", safetyTitle: "सुरक्षा",
  wirelessCommTitle: "वायरलेस संचार",
  wlLi1: "✔ NRF / LoRa मॉड्यूल", wlLi2: "✔ 1KM रेंज", wlLi3: "✔ कस्टम रिमोट", wlLi4: "✔ कम बिजली",
  futureTechSectionTitle: "भविष्य की तकनीक",
  futureAiNav: "एआई नेविगेशन", futureIot: "IoT", futureMobile: "मोबाइल ऐप", futureSolar: "सौर",
  contactPageTitle: "एग्रीरोवर से संपर्क करें",
  contactPageSub: "हम आपसे सुनना चाहेंगे — किसान, निवेशक या साझेदार।",
  sendUsMessage: "हमें संदेश भेजें", contactInformation: "संपर्क जानकारी",
  labelEmail: "ईमेल", labelPhone: "फ़ोन", labelLocation: "स्थान",
  placeholderName: "आपका नाम", placeholderEmail: "आपका ईमेल",
  placeholderSubject: "विषय", placeholderMessage: "आपका संदेश",
  sendMessageBtn: "संदेश भेजें →",
  teamHeroLabel: "लोग और मिशन",
  teamHeroTitle: "एग्रीरोवर के पीछे की टीम से मिलें",
  teamHeroLead: "हम किफायती, खेत-तैयार रोबोटिक्स बना रहे हैं ताकि छोटे और सीमांत किसान कम मेहनत, कम इनपुट बर्बादी और अधिक पूर्वानुमेय परिणामों के साथ खेती कर सकें।",
  teamStat1: "किसान-पहले उत्पाद निर्णय",
  teamStat2: "भारतीय खेतों और फसलों के लिए निर्मित",
  teamStat3: "एक लूप में हार्डवेयर, एम्बेडेड और एआई",
  valuesHeading: "हम कैसे काम करते हैं",
  valuesIntro: "सिद्धांत जो एग्रीरोवर को ईमानदार, उपयोगी और शिप करने योग्य रखते हैं।",
  valueH1: "बनाने से पहले सुनें",
  valueP1: "हम किसान प्रतिक्रिया और फील्ड ट्रायल को सच का स्रोत मानते हैं — स्लाइड डेक नहीं।",
  valueH2: "हाइप पर विश्वसनीयता",
  valueP2: "सरल तंत्र, परीक्षण योग्य इलेक्ट्रॉनिक्स और रखरखाव योग्य कोड नाजुक डेमो से बेहतर हैं।",
  valueH3: "मंडली बढ़ाएं",
  valueP3: "हम इंजीनियरों, कृषि विशेषज्ञों और साझेदारों का स्वागत करते हैं जो इसी मिशन की परवाह करते हैं।",
  foundersHeading: "संस्थापक टीम",
  foundersIntro: "उत्पाद, अनुसंधान और निष्पादन की दिशा तय करने वाली मुख्य टीम।",
  satyamRole: "संस्थापक — एआई और हार्डवेयर",
  satyamBio: "एग्रीरोवर की तकनीकी दिशा का नेतृत्व: यांत्रिक और इलेक्ट्रॉनिक डिज़ाइन, रोबोटिक्स एकीकरण, और खेत में बुद्धिमान स्वचालन की रोडमैप।",
  tagRobotics: "रोबोटिक्स", tagPrototyping: "प्रोटोटाइपिंग", tagSystems: "सिस्टम डिज़ाइन",
  harishRole: "सह-संस्थापक — अनुसंधान और दस्तावेज़ीकरण",
  harishBio: "अनुसंधान संश्लेषण, दस्तावेज़ीकरण, अनुदान और कार्यक्रम आवेदन, और समन्वय ताकि टीम गति से आगे बढ़े बिना कठोरता या स्पष्टता खोए।",
  tagResearch: "अनुसंधान", tagGrants: "अनुदान और कार्यक्रम", tagOperations: "संचालन",
  engSectionTitle: "इंजीनियरिंग टीम क्या कवर करती है",
  engSectionIntro: "क्षमता क्षेत्र जो हम बना रहे हैं (और भर्ती कर रहे हैं) जैसे एग्रीरोवर परिपक्व होता है।",
  engMechTitle: "यांत्रिक और हार्डवेयर",
  engMechDesc: "चेसिस, एक्चुएटर, पावर और सेंसर — कीचड़, धूल और धूप में लंबे दिनों के लिए डिज़ाइन।",
  engEmbTitle: "एम्बेडेड और फर्मवेयर",
  engEmbDesc: "माइक्रोकंट्रोलर, मोटर नियंत्रण, वायरलेस लिंक, और रोबोट पर सुरक्षित, निर्धारित व्यवहार।",
  engSoftTitle: "सॉफ़्टवेयर और एआई",
  engSoftDesc: "फील्ड सॉफ़्टवेयर, ट्रायल डेटा, और मॉडल जो समय के साथ छिड़काव और नेविगेशन को स्मार्ट बनाते हैं।",
  advisorsHeading: "सलाहकार",
  advisorsIntro: "क्षेत्र के विशेषज्ञ जो हमारे अनुमानों की जांच करते हैं और वास्तविक कृषि में जमीन पर रखते हैं।",
  advAgTitle: "कृषि सलाहकार",
  advAgDesc: "फसल चक्र, स्थानीय प्रथाएं, और छोटे प्लॉट पर 'अच्छा पर्याप्त' कैसा दिखता है।",
  advTechTitle: "प्रौद्योगिकी मार्गदर्शक",
  advTechDesc: "आर्किटेक्चर, निर्माण योग्यता, और हार्डवेयर-भारी स्टार्टअप को जिम्मेदारी से स्केल करना।",
  supportHeading: "स्टार्टअप सहायता",
  supportIntro: "कार्यक्रम और मार्गदर्शक जो हमारे निष्पादन का समर्थन करते हैं और पारिस्थितिकी तंत्र से जोड़ते हैं।",
  supInnovTitle: "नवाचार कार्यक्रम",
  supInnovDesc: "इन्क्यूबेशन, कोहॉर्ट और संरचित सहायता जैसे हम मान्य करते और तैनात करते हैं।",
  supMentorsTitle: "मार्गदर्शक",
  supMentorsDesc: "ऑपरेटर और संस्थापक जिन्होंने हार्डवेयर शिप किया और प्रारंभिक वृद्धि नेविगेट की।",
  teamCtaTitle: "एग्रीरोवर में शामिल हों?",
  teamCtaSub: "हम इंजीनियरों, निर्माताओं और शोधकर्ताओं की तलाश में हैं जो चाहते हैं कि उनका काम वास्तविक खेतों में दिखे।",
  contactUsBtn: "हमसे संपर्क करें",
  invHeroTitle: "खेती के भविष्य में निवेश करें",
  invHeroSub: "एग्रीरोवर भारत में लाखों छोटे किसानों के लिए किफायती रोबोटिक खेती समाधान बना रहा है।",
  downloadPitch: "पिच डेक डाउनलोड करें",
  invProblemTitle: "समस्या",
  invProb1Title: "श्रम की कमी", invProb1Desc: "किसान श्रम की कमी और बढ़ती मजदूरी का सामना करते हैं।",
  invProb2Title: "महंगी मशीनरी", invProb2Desc: "पारंपरिक ट्रैक्टर ₹5–8 लाख की लागत करते हैं।",
  invProb3Title: "छोटे भूमि धारण", invProb3Desc: "अधिकांश किसानों के पास बहुत छोटी जमीन है।",
  invProb4Title: "मैनुअल खेती", invProb4Desc: "अधिकांश कार्य अभी भी मैनुअल हैं।",
  invSolutionTitle: "हमारा समाधान",
  invSol1Title: "कॉम्पैक्ट इलेक्ट्रिक रोवर", invSol1Desc: "छोटे खेतों और संकरी खेतों के लिए डिज़ाइन।",
  invSol2Title: "रिमोट नियंत्रित", invSol2Desc: "1 किमी तक वायरलेस रेंज।",
  invSol3Title: "बहुउद्देश्यीय", invSol3Desc: "छिड़काव, बुवाई, उर्वरक और अधिक।",
  invSol4Title: "किफायती", invSol4Desc: "अनुमानित लागत ₹1 लाख से कम।",
  invMarketTitle: "बाजार अवसर",
  invTamTitle: "TAM", invTamLine: "9.3 करोड़ किसान", invTamDesc: "भारत में कुल कृषि उपयोगकर्ता।",
  invSamTitle: "SAM", invSamLine: "86% छोटे किसान", invSamDesc: "बहुमत छोटे और सीमांत किसान हैं।",
  invSomTitle: "SOM", invSomLine: "प्रारंभिक लक्ष्य खंड", invSomDesc: "2 एकड़ से कम जमीन वाले किसान।",
  invInvestTitle: "निवेश अवसर",
  invInvestP: "एग्रीरोवर भारत भर में स्केल करने के लिए निवेशक, एक्सीलरेटर और रणनीतिक साझेदारों की तलाश में है।",
  invCard1Title: "सीड निवेश", invCard1Desc: "प्रोटोटाइप और निर्माण चरण का समर्थन।",
  invCard2Title: "रणनीतिक साझेदार", invCard2Desc: "एग्री-टेक कंपनियों के साथ सहयोग।",
  invCard3Title: "एक्सीलरेटर", invCard3Desc: "स्टार्टअप कार्यक्रमों और स्केलिंग सहायता में शामिल हों।",
  invCtaTitle: "निवेश में रुचि?", invCtaBtn: "निवेश के लिए संपर्क",
  blogHeroTitle: "एग्रीरोवर ब्लॉग",
  blogHeroSub: "कृषि, रोबोटिक्स और हमारी स्टार्टअप यात्रा पर अंतर्दृष्टि।",
  blogLatestTitle: "नवीनतम लेख",
  blogArt1Title: "कृषि में एआई का भविष्य", blogArt1Desc: "एआई और रोबोटिक्स आधुनिक खेती को बदल रहे हैं।",
  blogArt2Title: "छोटे किसानों की समस्याएं", blogArt2Desc: "उच्च लागत, कम तकनीक पहुंच और श्रम की कमी।",
  blogArt3Title: "एग्रीरोवर क्यों", blogArt3Desc: "वास्तविक खेती की समस्याओं को हल करने के लिए बनाया गया।",
  blogArt4Title: "खेती में रोबोटिक्स", blogArt4Desc: "दक्षता और उपज में सुधार के लिए स्वचालन।",
  blogDevTitle: "विकास अपडेट",
  blogDev1Title: "प्रोटोटाइप विकास", blogDev1Desc: "रिमोट सिस्टम के साथ पहला कार्यशील मॉडल बनाना।",
  blogDev2Title: "₹50,000 अनुदान प्राप्त", blogDev2Desc: "कॉलेज नवाचार कार्यक्रम द्वारा समर्थित।",
  blogFollowTitle: "हमारी यात्रा का अनुसरण करें",
  blogFollowSub: "एग्रीरोवर की प्रगति और नवाचारों के साथ अपडेट रहें",
  blogConnectBtn: "हमसे जुड़ें"
});

// ─────────────────────────────────────────────
// PAGE-SPECIFIC KEYS — MARATHI
// ─────────────────────────────────────────────
Object.assign(translations.mr, {
  linkedin: "लिंक्डइन", readMore: "अधिक वाचा",
  productHeroTitle: "एग्रीरोवर – स्मार्ट मिनी शेती रोबोट",
  productHeroSub: "लहान शेतकऱ्यांसाठी स्प्रेइंग, पेरणी, खत टाकणे आणि बरेच काही स्वयंचलित करण्यासाठी डिझाइन केलेली कॉम्पॅक्ट इलेक्ट्रिक रोबोटिक प्रणाली.",
  watchDemo: "डेमो पहा",
  badgeFieldReady: "🛡 शेतासाठी तयार", badgeEcoFriendly: "🌱 पर्यावरण अनुकूल",
  productAboutTag: "उत्पादनाबद्दल", productOneRobot: "एक रोबोट. अनेक कामे.",
  productAboutP: "एग्रीरोवर ही एक बहुमुखी रोबोटिक प्लॅटफॉर्म आहे जी भारताच्या लहान शेतकऱ्यांना औद्योगिक-स्तरीय स्वयंचलनाची शक्ती आणते. इंटरचेंजेबल टूल अटॅचमेंटसह ते स्प्रेइंग, पेरणी आणि खत टाकणे हाताळते — श्रम खर्च कमी करते आणि उत्पादन वाढवते.",
  productFeat1: "✔ भारतीय शेती परिस्थितींसाठी स्टील फ्रेम",
  productFeat2: "✔ ऊबड-खाबड जमिनीसाठी 10 इंच चाके",
  productFeat3: "✔ 1 किमी पर्यंत वायरलेस रिमोट रेंज",
  productFeat4: "✔ इंटरचेंजेबल टूल अटॅचमेंट सिस्टम",
  productFeat5: "✔ कमी-शक्ती, दीर्घ-कालावधी ऑपरेशन",
  productFeat6: "✔ हवामान-प्रतिरोधी बंद इलेक्ट्रॉनिक्स",
  exploreTechnology: "तंत्रज्ञान एक्सप्लोर करा →",
  problemWeSolve: "आम्ही सोडवत असलेली समस्या",
  probLaborTitle: "श्रम टंचाई", probLaborDesc: "वाढती श्रम खर्च.",
  probCostTitle: "जास्त खर्च", probCostDesc: "मशीन ₹5–8 लाखांच्या.",
  probLargeTitle: "मोठ्या मशीन", probLargeDesc: "लहान शेतांसाठी नाही.",
  probManualTitle: "मॅन्युअल काम", probManualDesc: "अजूनही अवलंबित.",
  futureUpgrades: "भविष्यातील अपग्रेड",
  futureUpgradesList: "मोबाइल अॅप • एआय स्वयंचलन • IoT एकत्रीकरण • सौर चार्जिंग",
  requestDemo: "डेमोची विनंती →",
  techPageHeroTitle: "एग्रीरोवरमागील अभियांत्रिकी",
  techPageHeroSub: "स्मार्ट शेतीला शक्ती देणारे प्रगत रोबोटिक्स, एम्बेडेड सिस्टम आणि वायरलेस तंत्रज्ञान.",
  sysArchitecture: "सिस्टम आर्किटेक्चर",
  powerUnit: "पावर युनिट", controlUnit: "नियंत्रण युनिट", driveSystem: "ड्राइव्ह सिस्टम", attachmentsCard: "अटॅचमेंट",
  mechDesignTitle: "यांत्रिक डिझाइन",
  mechDesignP: "मजबूत स्टील संरचना, कॉम्पॅक्ट बॉडी आणि भूभाग-तयार चाकांसह बनवलेले.",
  mechLi1: "✔ स्टील फ्रेम", mechLi2: "✔ बंद बॉडी", mechLi3: "✔ 10 इंच चाके", mechLi4: "✔ कॉम्पॅक्ट डिझाइन",
  elecControlTitle: "इलेक्ट्रॉनिक्स आणि नियंत्रण",
  microTitle: "मायक्रोकंट्रोलर", motorDriver: "मोटर ड्रायव्हर", powerSysTitle: "पावर सिस्टम", safetyTitle: "सुरक्षा",
  wirelessCommTitle: "वायरलेस संचार",
  wlLi1: "✔ NRF / LoRa मॉड्यूल", wlLi2: "✔ 1KM रेंज", wlLi3: "✔ कस्टम रिमोट", wlLi4: "✔ कमी शक्ती",
  futureTechSectionTitle: "भविष्याचे तंत्रज्ञान",
  futureAiNav: "एआय नेव्हिगेशन", futureIot: "IoT", futureMobile: "मोबाइल अॅप", futureSolar: "सौर",
  contactPageTitle: "एग्रीरोवरशी संपर्क साधा",
  contactPageSub: "आम्हाला तुमच्याकडून ऐकायला आवडेल — शेतकरी, गुंतवणूकदार किंवा भागीदार.",
  sendUsMessage: "आम्हाला संदेश पाठवा", contactInformation: "संपर्क माहिती",
  labelEmail: "ईमेल", labelPhone: "फोन", labelLocation: "स्थान",
  placeholderName: "तुमचे नाव", placeholderEmail: "तुमचा ईमेल",
  placeholderSubject: "विषय", placeholderMessage: "तुमचा संदेश",
  sendMessageBtn: "संदेश पाठवा →",
  teamHeroLabel: "लोक आणि मिशन",
  teamHeroTitle: "एग्रीरोवरमागील टीमला भेटा",
  teamHeroLead: "आम्ही परवडणारे, शेत-तयार रोबोटिक्स बनवत आहोत जेणेकरून लहान आणि सीमांत शेतकरी कमी कष्ट, कमी इनपुट बर्बादी आणि अधिक अनुमानित परिणामांसह शेती करू शकतात.",
  teamStat1: "शेतकरी-प्रथम उत्पादन निर्णय",
  teamStat2: "भारतीय शेते आणि पिकांसाठी बनवलेले",
  teamStat3: "एका लूपमध्ये हार्डवेयर, एम्बेडेड आणि एआय",
  valuesHeading: "आम्ही कसे काम करतो",
  valuesIntro: "तत्त्वे जी एग्रीरोवरला प्रामाणिक, उपयुक्त आणि शिप करण्यायोग्य ठेवतात.",
  valueH1: "बनवण्यापूर्वी ऐका",
  valueP1: "आम्ही शेतकरी अभिप्राय आणि फील्ड चाचण्या सत्याचा स्रोत म्हणून मानतो — स्लाइड डेक नाही.",
  valueH2: "हाइपवर विश्वासार्हता",
  valueP2: "साधे यंत्र, चाचणीयोग्य इलेक्ट्रॉनिक्स आणि देखभालयोग्य कोड नाजूक डेमोपेक्षा चांगले.",
  valueH3: "वर्तुळ वाढवा",
  valueP3: "आम्ही सक्रियपणे अभियंते, कृषी तज्ञ आणि भागीदारांचे स्वागत करतो जे त्याच मिशनची काळजी करतात.",
  foundersHeading: "संस्थापक टीम",
  foundersIntro: "उत्पादन, संशोधन आणि अंमलबजावणीची दिशा ठरवणारी मुख्य टीम.",
  satyamRole: "संस्थापक — एआय आणि हार्डवेयर",
  satyamBio: "एग्रीरोवरच्या तांत्रिक दिशेचे नेतृत्व: यांत्रिक आणि इलेक्ट्रॉनिक डिझाइन, रोबोटिक्स एकत्रीकरण आणि शेतात बुद्धिमान स्वयंचलनाचा रोडमॅप.",
  tagRobotics: "रोबोटिक्स", tagPrototyping: "प्रोटोटाइपिंग", tagSystems: "सिस्टम डिझाइन",
  harishRole: "सह-संस्थापक — संशोधन आणि दस्तऐवजीकरण",
  harishBio: "संशोधन संश्लेषण, दस्तऐवजीकरण, अनुदान आणि कार्यक्रम अर्ज आणि समन्वय चालवतो जेणेकरून टीम कठोरता किंवा स्पष्टता न गमावता वेगाने पुढे जाऊ शकते.",
  tagResearch: "संशोधन", tagGrants: "अनुदाने आणि कार्यक्रम", tagOperations: "ऑपरेशन्स",
  engSectionTitle: "अभियांत्रिकी टीम काय कव्हर करते",
  engSectionIntro: "क्षमता क्षेत्रे जी आम्ही बनवत आहोत (आणि भरती करत आहोत) जसे एग्रीरोवर परिपक्व होते.",
  engMechTitle: "यांत्रिक आणि हार्डवेयर",
  engMechDesc: "चेसिस, अॅक्च्युएटर, पावर आणि सेन्सर — चिखल, धूळ आणि उन्हाळ्यातील लांब दिवसांसाठी डिझाइन.",
  engEmbTitle: "एम्बेडेड आणि फर्मवेयर",
  engEmbDesc: "मायक्रोकंट्रोलर, मोटर नियंत्रण, वायरलेस लिंक आणि रोबोटवर सुरक्षित, निश्चित वर्तन.",
  engSoftTitle: "सॉफ्टवेयर आणि एआय",
  engSoftDesc: "फील्ड सॉफ्टवेयर, चाचणींचा डेटा आणि मॉडेल जे कालांतराने स्प्रेइंग आणि नेव्हिगेशन स्मार्ट बनवतात.",
  advisorsHeading: "सल्लागार",
  advisorsIntro: "डोमेन तज्ञ जे आमच्या गृहितकांची तपासणी करण्यास आणि वास्तविक शेतीमध्ये ग्राउंड ठेवण्यास मदत करतात.",
  advAgTitle: "कृषी सल्लागार",
  advAgDesc: "पीक चक्र, स्थानीय पद्धती आणि लहान प्लॉटवर 'पुरेसे चांगले' कसे दिसते.",
  advTechTitle: "तंत्रज्ञान मार्गदर्शक",
  advTechDesc: "आर्किटेक्चर, निर्मितीयोग्यता आणि हार्डवेयर-जड स्टार्टअप जबाबदारीने स्केल करणे.",
  supportHeading: "स्टार्टअप समर्थन",
  supportIntro: "कार्यक्रम आणि मार्गदर्शक जे आमच्या अंमलबजावणीचे समर्थन करतात आणि आम्हाला इकोसिस्टमशी जोडतात.",
  supInnovTitle: "नवोपक्रम कार्यक्रम",
  supInnovDesc: "इन्क्यूबेशन, कोहॉर्ट आणि संरचित समर्थन जसे आम्ही सत्यापन आणि तैनाती करतो.",
  supMentorsTitle: "मार्गदर्शक",
  supMentorsDesc: "ऑपरेटर आणि संस्थापक ज्यांनी हार्डवेयर शिप केले आणि प्रारंभिक वाढ नेव्हिगेट केली.",
  teamCtaTitle: "एग्रीरोवरमध्ये सामील व्हायचे आहे?",
  teamCtaSub: "आम्ही अभियंते, निर्माते आणि संशोधक शोधत आहोत ज्यांना त्यांचे काम वास्तविक शेतांमध्ये दिसावे.",
  contactUsBtn: "आमच्याशी संपर्क साधा",
  invHeroTitle: "शेतीच्या भविष्यात गुंतवणूक करा",
  invHeroSub: "एग्रीरोवर भारतातील लाखो लहान शेतकऱ्यांसाठी परवडणारे रोबोटिक शेती उपाय बनवत आहे.",
  downloadPitch: "पिच डेक डाउनलोड करा",
  invProblemTitle: "समस्या",
  invProb1Title: "श्रम टंचाई", invProb1Desc: "शेतकऱ्यांना श्रम टंचाई आणि वाढत्या मजुरीचा सामना करावा लागतो.",
  invProb2Title: "महागडी यंत्रसामग्री", invProb2Desc: "पारंपारिक ट्रॅक्टर ₹5–8 लाख खर्च करतात.",
  invProb3Title: "लहान जमीन धारणा", invProb3Desc: "बहुतेक शेतकऱ्यांकडे खूप लहान जमीन आहे.",
  invProb4Title: "मॅन्युअल शेती", invProb4Desc: "बहुतेक ऑपरेशन अजूनही मॅन्युअल आहेत.",
  invSolutionTitle: "आमचा उपाय",
  invSol1Title: "कॉम्पॅक्ट इलेक्ट्रिक रोव्हर", invSol1Desc: "लहान शेते आणि अरुंद शेतांसाठी डिझाइन.",
  invSol2Title: "रिमोट नियंत्रित", invSol2Desc: "1 किमी पर्यंत वायरलेस रेंज.",
  invSol3Title: "बहुउद्देशीय", invSol3Desc: "स्प्रेइंग, पेरणी, खत टाकणे आणि बरेच काही.",
  invSol4Title: "परवडणारे", invSol4Desc: "अंदाजे खर्च ₹1 लाखापेक्षा कमी.",
  invMarketTitle: "बाजार संधी",
  invTamTitle: "TAM", invTamLine: "9.3 कोटी शेतकरी", invTamDesc: "भारतातील एकूण कृषी वापरकर्ते.",
  invSamTitle: "SAM", invSamLine: "86% लहान शेतकरी", invSamDesc: "बहुसंख्य लहान आणि सीमांत शेतकरी आहेत.",
  invSomTitle: "SOM", invSomLine: "प्रारंभिक लक्ष्य विभाग", invSomDesc: "2 एकरपेक्षा कमी जमीन असलेले शेतकरी.",
  invInvestTitle: "गुंतवणूक संधी",
  invInvestP: "एग्रीरोवर भारतभर स्केल करण्यासाठी गुंतवणूकदार, एक्सीलरेटर आणि रणनीतिक भागीदार शोधत आहे.",
  invCard1Title: "सीड गुंतवणूक", invCard1Desc: "प्रोटोटाइप आणि उत्पादन टप्प्याचे समर्थन.",
  invCard2Title: "रणनीतिक भागीदार", invCard2Desc: "कृषी-तंत्र कंपन्यांसह सहयोग.",
  invCard3Title: "एक्सीलरेटर", invCard3Desc: "स्टार्टअप कार्यक्रमांमध्ये सामील व्हा आणि स्केलिंग समर्थन.",
  invCtaTitle: "गुंतवणुकीत स्वारस्य आहे?", invCtaBtn: "गुंतवणुकीसाठी संपर्क साधा",
  blogHeroTitle: "एग्रीरोवर ब्लॉग",
  blogHeroSub: "कृषी, रोबोटिक्स आणि आमच्या स्टार्टअप प्रवासावरील अंतर्दृष्टी.",
  blogLatestTitle: "नवीनतम लेख",
  blogArt1Title: "कृषीमध्ये एआयचे भविष्य", blogArt1Desc: "एआय आणि रोबोटिक्स आधुनिक शेती बदलत आहेत.",
  blogArt2Title: "लहान शेतकऱ्यांच्या समस्या", blogArt2Desc: "जास्त खर्च, कमी तंत्र प्रवेश आणि श्रम टंचाई.",
  blogArt3Title: "एग्रीरोवर का", blogArt3Desc: "वास्तविक शेती समस्या सोडवण्यासाठी बनवलेले.",
  blogArt4Title: "शेतीमध्ये रोबोटिक्स", blogArt4Desc: "कार्यक्षमता आणि उत्पादन सुधारत असलेले स्वयंचलन.",
  blogDevTitle: "विकास अपडेट",
  blogDev1Title: "प्रोटोटाइप विकास", blogDev1Desc: "रिमोट सिस्टमसह पहिले कार्यशील मॉडेल बनवणे.",
  blogDev2Title: "₹50,000 अनुदान मिळाले", blogDev2Desc: "महाविद्यालय नवोपक्रम कार्यक्रमाद्वारे समर्थित.",
  blogFollowTitle: "आमचा प्रवास अनुसरण करा",
  blogFollowSub: "एग्रीरोवरच्या प्रगती आणि नवकल्पनांसह अपडेट रहा",
  blogConnectBtn: "आमच्याशी कनेक्ट व्हा"
});

// ─────────────────────────────────────────────
// PAGE-SPECIFIC KEYS — TAMIL
// ─────────────────────────────────────────────
Object.assign(translations.ta, {
  linkedin: "லிங்க்டின்", readMore: "மேலும் படிக்கவும்",
  productHeroTitle: "அக்ரிரோவர் – ஸ்மார்ட் மினி விவசாய ரோபோ",
  productHeroSub: "சிறிய விவசாயிகளுக்கு தெளிப்பு, விதைப்பு, உரமிடுதல் மற்றும் பலவற்றை தானியங்குபடுத்த வடிவமைக்கப்பட்ட காம்பாக்ட் எலெக்ட்ரிக் ரோபோடிக் அமைப்பு.",
  watchDemo: "டெமோ பாருங்கள்",
  badgeFieldReady: "🛡 வயலுக்கு தயார்", badgeEcoFriendly: "🌱 சுற்றுச்சூழல் நட்பு",
  productAboutTag: "தயாரிப்பு பற்றி", productOneRobot: "ஒரு ரோபோ. பல வேலைகள்.",
  productAboutP: "அக்ரிரோவர் ஒரு பல்துறை ரோபோடிக் தளம், இது இந்தியாவின் சிறிய விவசாயிகளுக்கு தொழில்துறை-தர ஆட்டோமேஷனின் சக்தியை கொண்டுவருகிறது. மாற்று கருவி இணைப்புகளுடன், இது தெளிப்பு, விதைப்பு மற்றும் உரமிடுதல் கையாளுகிறது — உழைப்பு செலவைக் குறைக்கிறது மற்றும் விளைச்சலை அதிகரிக்கிறது.",
  productFeat1: "✔ இந்திய வயல் நிலைமைகளுக்கு எஃகு சட்டகம்",
  productFeat2: "✔ சமன்படுத்தப்படாத நிலத்திற்கு 10 அங்குல உறுதியான சக்கரங்கள்",
  productFeat3: "✔ 1கிமீ வரை வயர்லெஸ் ரிமோட் வரம்பு",
  productFeat4: "✔ மாற்றத்தக்க கருவி இணைப்பு அமைப்பு",
  productFeat5: "✔ குறைந்த சக்தி, நீண்ட கால செயல்பாடு",
  productFeat6: "✔ வானிலை-எதிர்ப்பு மூடிய மின்னணுவியல்",
  exploreTechnology: "தொழில்நுட்பத்தை ஆராயுங்கள் →",
  problemWeSolve: "நாங்கள் தீர்க்கும் சிக்கல்",
  probLaborTitle: "தொழிலாளர் பற்றாக்குறை", probLaborDesc: "அதிகரிக்கும் தொழிலாளர் செலவுகள்.",
  probCostTitle: "அதிக செலவு", probCostDesc: "இயந்திரங்கள் ₹5–8 லட்சம் செலவாகும்.",
  probLargeTitle: "பெரிய இயந்திரங்கள்", probLargeDesc: "சிறிய பண்ணைகளுக்கு இல்லை.",
  probManualTitle: "கைமுறை வேலை", probManualDesc: "இன்னும் சார்ந்துள்ளது.",
  futureUpgrades: "எதிர்கால மேம்பாடுகள்",
  futureUpgradesList: "மொபைல் ஆப் • AI ஆட்டோமேஷன் • IoT ஒருங்கிணைப்பு • சோலார் சார்ஜிங்",
  requestDemo: "டெமோ கோருங்கள் →",
  techPageHeroTitle: "அக்ரிரோவருக்கு பின்னால் உள்ள பொறியியல்",
  techPageHeroSub: "ஸ்மார்ட் விவசாயத்திற்கு சக்தி அளிக்கும் மேம்பட்ட ரோபோடிக்ஸ், உட்பொதிந்த அமைப்புகள் மற்றும் வயர்லெஸ் தொழில்நுட்பம்.",
  sysArchitecture: "சிஸ்டம் கட்டமைப்பு",
  powerUnit: "பவர் யூனிட்", controlUnit: "கண்ட்ரோல் யூனிட்", driveSystem: "டிரைவ் சிஸ்டம்", attachmentsCard: "இணைப்புகள்",
  mechDesignTitle: "இயந்திர வடிவமைப்பு",
  mechDesignP: "உறுதியான எஃகு கட்டமைப்பு, காம்பாக்ட் உடல் மற்றும் நிலப்பரப்பு-தயார் சக்கரங்களுடன் கட்டப்பட்டது.",
  mechLi1: "✔ எஃகு சட்டகம்", mechLi2: "✔ மூடிய உடல்", mechLi3: "✔ 10 அங்குல சக்கரங்கள்", mechLi4: "✔ காம்பாக்ட் டிசைன்",
  elecControlTitle: "மின்னணுவியல் & கட்டுப்பாடு",
  microTitle: "மைக்ரோகண்ட்ரோலர்", motorDriver: "மோட்டார் டிரைவர்", powerSysTitle: "பவர் சிஸ்டம்", safetyTitle: "பாதுகாப்பு",
  wirelessCommTitle: "வயர்லெஸ் தொடர்பு",
  wlLi1: "✔ NRF / LoRa மாடியூல்கள்", wlLi2: "✔ 1KM வரம்பு", wlLi3: "✔ தனிப்பயன் ரிமோட்", wlLi4: "✔ குறைந்த சக்தி",
  futureTechSectionTitle: "எதிர்கால தொழில்நுட்பம்",
  futureAiNav: "AI வழிசெலுத்தல்", futureIot: "IoT", futureMobile: "மொபைல் ஆப்", futureSolar: "சோலார்",
  contactPageTitle: "அக்ரிரோவரை தொடர்பு கொள்ளுங்கள்",
  contactPageSub: "உங்களிடமிருந்து கேட்க விரும்புகிறோம் — விவசாயி, முதலீட்டாளர் அல்லது பங்குதாரர்.",
  sendUsMessage: "எங்களுக்கு செய்தி அனுப்புங்கள்", contactInformation: "தொடர்பு தகவல்",
  labelEmail: "மின்னஞ்சல்", labelPhone: "தொலைபேசி", labelLocation: "இடம்",
  placeholderName: "உங்கள் பெயர்", placeholderEmail: "உங்கள் மின்னஞ்சல்",
  placeholderSubject: "விஷயம்", placeholderMessage: "உங்கள் செய்தி",
  sendMessageBtn: "செய்தி அனுப்புங்கள் →",
  teamHeroLabel: "மக்கள் & இயக்கம்",
  teamHeroTitle: "அக்ரிரோவருக்கு பின்னால் உள்ள குழுவை சந்தியுங்கள்",
  teamHeroLead: "சிறிய மற்றும் விளிம்பு விவசாயிகள் குறைந்த கஷ்டம், குறைந்த உள்ளீட்டு வீணாக்கல் மற்றும் அதிக முன்கணிக்கக்கூடிய முடிவுகளுடன் விவசாயம் செய்ய, மலிவான, வயல்-தயார் ரோபோடிக்ஸை உருவாக்குகிறோம்.",
  teamStat1: "விவசாயி-முதல் தயாரிப்பு முடிவுகள்",
  teamStat2: "இந்திய வயல்கள் & பயிர்களுக்காக கட்டப்பட்டது",
  teamStat3: "ஒரு லூப்பில் ஹார்டுவேர், உட்பொதிந்த & AI",
  valuesHeading: "நாங்கள் எப்படி வேலை செய்கிறோம்",
  valuesIntro: "அக்ரிரோவரை நேர்மையான, பயனுள்ள மற்றும் அனுப்பக்கூடியதாக வைத்திருக்கும் கொள்கைகள்.",
  valueH1: "கட்டமைப்பதற்கு முன் கேளுங்கள்",
  valueP1: "விவசாயி கருத்து மற்றும் வயல் சோதனைகளை உண்மையின் ஆதாரமாக கருதுகிறோம் — ஸ்லைட் டெக்குகள் அல்ல.",
  valueH2: "ஆர்ப்பாட்டத்தை விட நம்பகத்தன்மை",
  valueP2: "எளிய வழிமுறைகள், சோதிக்கக்கூடிய மின்னணுவியல் மற்றும் பராமரிக்கக்கூடிய குறியீடு உடையக்கூடிய டெமோக்களை விட சிறந்தது.",
  valueH3: "வட்டத்தை வளர்க்கவும்",
  valueP3: "ஒரே இயக்கத்தைப் பற்றி அக்கறை கொண்ட பொறியாளர்கள், வேளாண் நிபுணர்கள் மற்றும் பங்குதாரர்களை தீவிரமாக வரவேற்கிறோம்.",
  foundersHeading: "நிறுவன குழு",
  foundersIntro: "தயாரிப்பு, ஆராய்ச்சி மற்றும் செயல்படுத்தலுக்கான திசையை அமைக்கும் மைய குழு.",
  satyamRole: "நிறுவனர் — AI & ஹார்டுவேர்",
  satyamBio: "அக்ரிரோவரின் தொழில்நுட்ப திசையை வழிநடத்துகிறார்: இயந்திர மற்றும் மின்னணு வடிவமைப்பு, ரோபோடிக்ஸ் ஒருங்கிணைப்பு மற்றும் வயலில் அறிவார்ந்த ஆட்டோமேஷன் நோக்கிய ரோட்மேப்.",
  tagRobotics: "ரோபோடிக்ஸ்", tagPrototyping: "முன்மாதிரி", tagSystems: "சிஸ்டம் டிசைன்",
  harishRole: "இணை நிறுவனர் — ஆராய்ச்சி & ஆவணமாக்கல்",
  harishBio: "ஆராய்ச்சி தொகுப்பு, ஆவணமாக்கல், மானிய மற்றும் திட்ட விண்ணப்பங்கள் மற்றும் ஒருங்கிணைப்பு மூலம் குழு கடுமை அல்லது தெளிவை இழக்காமல் வேகமாக நகரலாம்.",
  tagResearch: "ஆராய்ச்சி", tagGrants: "மானியங்கள் & திட்டங்கள்", tagOperations: "செயல்பாடுகள்",
  engSectionTitle: "பொறியியல் குழு என்ன உள்ளடக்குகிறது",
  engSectionIntro: "அக்ரிரோவர் முதிர்ச்சியடையும்போது நாங்கள் கட்டமைக்கும் (மற்றும் பணியமர்த்தும்) திறன் பகுதிகள்.",
  engMechTitle: "இயந்திர & ஹார்டுவேர்",
  engMechDesc: "சேஸி, ஆக்டுவேட்டர்கள், சக்தி மற்றும் சென்சார்கள் — சேறு, தூசு மற்றும் வெயிலில் நீண்ட நாட்களுக்கு வடிவமைக்கப்பட்டது.",
  engEmbTitle: "உட்பொதிந்த & ஃபார்மேர்",
  engEmbDesc: "மைக்ரோகண்ட்ரோலர்கள், மோட்டார் கட்டுப்பாடு, வயர்லெஸ் இணைப்புகள் மற்றும் ரோபோட்டில் பாதுகாப்பான, நிர்ணயமான நடத்தை.",
  engSoftTitle: "மென்பொருள் & AI",
  engSoftDesc: "வயல் மென்பொருள், சோதனைகளிலிருந்து தரவு மற்றும் காலப்போக்கில் தெளிப்பு மற்றும் வழிசெலுத்தலை புத்திசாலியாக்கும் மாதிரிகள்.",
  advisorsHeading: "ஆலோசகர்கள்",
  advisorsIntro: "எங்கள் அனுமானங்களை சோதிக்க மற்றும் உண்மையான விவசாயத்தில் தரையில் இருக்க உதவும் டொமைன் நிபுணர்கள்.",
  advAgTitle: "விவசாய ஆலோசகர்",
  advAgDesc: "பயிர் சுழற்சிகள், உள்ளூர் நடைமுறைகள் மற்றும் சிறிய நிலங்களில் 'போதுமானது' எப்படி இருக்கும்.",
  advTechTitle: "தொழில்நுட்ப வழிகாட்டி",
  advTechDesc: "கட்டமைப்பு, உற்பத்தி திறன் மற்றும் ஹார்டுவேர்-கனமான ஸ்டார்ட்அப்பை பொறுப்பாக அளவிடுதல்.",
  supportHeading: "ஸ்டார்ட்அப் ஆதரவு",
  supportIntro: "எங்கள் செயல்படுத்தலை ஆதரிக்கும் மற்றும் சுற்றுச்சூழலுடன் இணைக்கும் திட்டங்கள் மற்றும் வழிகாட்டிகள்.",
  supInnovTitle: "புத்தாக்க திட்டங்கள்",
  supInnovDesc: "நாங்கள் சரிபார்க்கும் மற்றும் வரிசைப்படுத்தும்போது இன்குபேஷன், குழுக்கள் மற்றும் கட்டமைக்கப்பட்ட ஆதரவு.",
  supMentorsTitle: "வழிகாட்டிகள்",
  supMentorsDesc: "ஹார்டுவேர் அனுப்பிய மற்றும் ஆரம்பகால வளர்ச்சியை வழிநடத்திய ஆபரேட்டர்கள் மற்றும் நிறுவனர்கள்.",
  teamCtaTitle: "அக்ரிரோவரில் சேர விரும்புகிறீர்களா?",
  teamCtaSub: "உண்மையான வயல்களில் தங்கள் வேலை காட்டப்படுவதை விரும்பும் பொறியாளர்கள், தயாரிப்பாளர்கள் மற்றும் ஆராய்ச்சியாளர்களை தேடுகிறோம்.",
  contactUsBtn: "எங்களை தொடர்பு கொள்ளுங்கள்",
  invHeroTitle: "விவசாயத்தின் எதிர்காலத்தில் முதலீடு செய்யுங்கள்",
  invHeroSub: "அக்ரிரோவர் இந்தியாவில் லட்சக்கணக்கான சிறிய விவசாயிகளுக்கு மலிவான ரோபோடிக் விவசாய தீர்வுகளை கட்டி வருகிறது.",
  downloadPitch: "பிட்ச் டெக் பதிவிறக்கவும்",
  invProblemTitle: "சிக்கல்",
  invProb1Title: "தொழிலாளர் பற்றாக்குறை", invProb1Desc: "விவசாயிகள் தொழிலாளர் பற்றாக்குறை மற்றும் அதிகரிக்கும் கூலிகளை எதிர்கொள்கிறார்கள்.",
  invProb2Title: "விலையுயர்ந்த இயந்திரங்கள்", invProb2Desc: "பாரம்பரிய டிராக்டர்கள் ₹5–8 லட்சம் செலவாகும்.",
  invProb3Title: "சிறிய நில வைத்திருப்பு", invProb3Desc: "பெரும்பாலான விவசாயிகளுக்கு மிகவும் சிறிய நிலம் உள்ளது.",
  invProb4Title: "கைமுறை விவசாயம்", invProb4Desc: "பெரும்பாலான செயல்பாடுகள் இன்னும் கைமுறையாகவே உள்ளன.",
  invSolutionTitle: "எங்கள் தீர்வு",
  invSol1Title: "காம்பாக்ட் எலெக்ட்ரிக் ரோவர்", invSol1Desc: "சிறிய பண்ணைகள் மற்றும் குறுகிய வயல்களுக்கு வடிவமைக்கப்பட்டது.",
  invSol2Title: "ரிமோட் கண்ட்ரோல்", invSol2Desc: "1 கிமீ வரை வயர்லெஸ் வரம்பு.",
  invSol3Title: "பல நோக்கம்", invSol3Desc: "தெளிப்பு, விதைப்பு, உரமிடுதல் & மேலும்.",
  invSol4Title: "மலிவான", invSol4Desc: "மதிப்பிடப்பட்ட செலவு ₹1 லட்சத்திற்கும் குறைவு.",
  invMarketTitle: "சந்தை வாய்ப்பு",
  invTamTitle: "TAM", invTamLine: "9.3 கோடி விவசாயிகள்", invTamDesc: "இந்தியாவில் மொத்த விவசாய பயனர்கள்.",
  invSamTitle: "SAM", invSamLine: "86% சிறிய விவசாயிகள்", invSamDesc: "பெரும்பாலும் சிறிய மற்றும் விளிம்பு விவசாயிகள்.",
  invSomTitle: "SOM", invSomLine: "ஆரம்ப இலக்கு பகுப்பு", invSomDesc: "2 ஏக்கரிற்கும் குறைவான நிலம் உள்ள விவசாயிகள்.",
  invInvestTitle: "முதலீட்டு வாய்ப்பு",
  invInvestP: "அக்ரிரோவர் இந்தியா முழுவதும் விரிவாக்க முதலீட்டாளர்கள், முடுக்கிகள் மற்றும் மூலோபாய பங்குதாரர்களை தேடுகிறது.",
  invCard1Title: "விதை முதலீடு", invCard1Desc: "முன்மாதிரி & உற்பத்தி நிலை ஆதரவு.",
  invCard2Title: "மூலோபாய பங்குதாரர்கள்", invCard2Desc: "விவசாய-தொழில்நுட்ப நிறுவனங்களுடன் ஒத்துழைக்கவும்.",
  invCard3Title: "முடுக்கிகள்", invCard3Desc: "ஸ்டார்ட்அப் திட்டங்களில் சேரவும் & விரிவாக்க ஆதரவு.",
  invCtaTitle: "முதலீட்டில் ஆர்வமா?", invCtaBtn: "முதலீட்டிற்காக தொடர்பு கொள்ளுங்கள்",
  blogHeroTitle: "அக்ரிரோவர் வலைப்பதிவு",
  blogHeroSub: "விவசாயம், ரோபோடிக்ஸ் மற்றும் எங்கள் ஸ்டார்ட்அப் பயணத்தின் நுண்ணறிவுகள்.",
  blogLatestTitle: "சமீபத்திய கட்டுரைகள்",
  blogArt1Title: "விவசாயத்தில் AI யின் எதிர்காலம்", blogArt1Desc: "AI & ரோபோடிக்ஸ் நவீன விவசாயத்தை மாற்றுகிறது.",
  blogArt2Title: "சிறிய விவசாயிகளின் சிக்கல்கள்", blogArt2Desc: "அதிக செலவு, குறைந்த தொழில்நுட்ப அணுகல் & தொழிலாளர் பற்றாக்குறை.",
  blogArt3Title: "ஏன் அக்ரிரோவர்", blogArt3Desc: "உண்மையான விவசாய சிக்கல்களை தீர்க்க கட்டப்பட்டது.",
  blogArt4Title: "விவசாயத்தில் ரோபோடிக்ஸ்", blogArt4Desc: "செயல்திறன் & விளைச்சலை மேம்படுத்தும் ஆட்டோமேஷன்.",
  blogDevTitle: "மேம்பாட்டு புதுப்பிப்புகள்",
  blogDev1Title: "முன்மாதிரி மேம்பாடு", blogDev1Desc: "ரிமோட் சிஸ்டத்துடன் முதல் வேலை செய்யும் மாதிரி கட்டமைக்கிறது.",
  blogDev2Title: "₹50,000 மானியம் பெறப்பட்டது", blogDev2Desc: "கல்லூரி புத்தாக்க திட்டத்தால் ஆதரிக்கப்படுகிறது.",
  blogFollowTitle: "எங்கள் பயணத்தை பின்தொடருங்கள்",
  blogFollowSub: "அக்ரிரோவர் முன்னேற்றம் & புதுமைகளுடன் புதுப்பித்த நிலையில் இருங்கள்",
  blogConnectBtn: "எங்களுடன் இணையுங்கள்"
});

// ─────────────────────────────────────────────
// PAGE-SPECIFIC KEYS — TELUGU
// ─────────────────────────────────────────────
Object.assign(translations.te, {
  linkedin: "లింక్డ్‌ఇన్", readMore: "మరింత చదవండి",
  productHeroTitle: "అగ్రిరోవర్ – స్మార్ట్ మినీ ఫార్మింగ్ రోబోట్",
  productHeroSub: "చిన్న వ్యవసాయులకు స్ప్రే, విత్తనం, ఎరువు మరియు మరిన్నింటిని ఆటోమేట్ చేయడానికి రూపొందించబడిన కాంపాక్ట్ ఎలెక్ట్రిక్ రోబోటిక్ సిస్టమ్.",
  watchDemo: "డెమో చూడండి",
  badgeFieldReady: "🛡 పొలానికి సిద్ధంగా ఉంది", badgeEcoFriendly: "🌱 పర్యావరణ స్నేహపూర్వక",
  productAboutTag: "ఉత్పత్తి గురించి", productOneRobot: "ఒక రోబోట్. అనేక పనులు.",
  productAboutP: "అగ్రిరోవర్ ఒక బహుముఖ రోబోటిక్ వేదిక, ఇది భారతదేశంలోని చిన్న వ్యవసాయులకు పారిశ్రామిక-స్థాయి ఆటోమేషన్ యొక్క శక్తిని తెస్తుంది. మార్చదగిన సాధన అనుబంధాలతో, ఇది స్ప్రేయింగ్, విత్తనం మరియు ఎరువులు నిర్వహిస్తుంది — శ్రమ ఖర్చులను తగ్గిస్తుంది మరియు దిగుబడిని పెంచుతుంది.",
  productFeat1: "✔ భారతీయ వ్యవసాయ పరిస్థితులకు స్టీల్ ఫ్రేమ్",
  productFeat2: "✔ అసమాన భూభాగానికి 10 అంగుళాల దృఢమైన చక్రాలు",
  productFeat3: "✔ 1కిమీ వరకు వైర్లెస్ రిమోట్ రేంజ్",
  productFeat4: "✔ మార్చదగిన సాధన అనుబంధ సిస్టమ్",
  productFeat5: "✔ తక్కువ-శక్తి, దీర్ఘ-వ్యవధి ఆపరేషన్",
  productFeat6: "✔ వాతావరణ-నిరోధక మూసిన ఎలెక్ట్రానిక్స్",
  exploreTechnology: "సాంకేతికతను అన్వేషించండి →",
  problemWeSolve: "మేము పరిష్కరించే సమస్య",
  probLaborTitle: "శ్రమ కొరత", probLaborDesc: "పెరుగుతున్న శ్రమ ఖర్చులు.",
  probCostTitle: "అధిక ఖర్చు", probCostDesc: "యంత్రాలు ₹5–8 లక్షలు.",
  probLargeTitle: "పెద్ద యంత్రాలు", probLargeDesc: "చిన్న పొలాలకు కాదు.",
  probManualTitle: "మాన్యువల్ పని", probManualDesc: "ఇంకా ఆధారపడి ఉంది.",
  futureUpgrades: "భవిష్యత్ అప్‌గ్రేడ్‌లు",
  futureUpgradesList: "మొబైల్ యాప్ • AI ఆటోమేషన్ • IoT ఇంటిగ్రేషన్ • సోలార్ చార్జింగ్",
  requestDemo: "డెమో అభ్యర్థించండి →",
  techPageHeroTitle: "అగ్రిరోవర్ వెనక ఇంజినీరింగ్",
  techPageHeroSub: "స్మార్ట్ వ్యవసాయానికి శక్తినిచ్చే అధునాతన రోబోటిక్స్, ఎంబెడెడ్ సిస్టమ్స్ మరియు వైర్లెస్ టెక్.",
  sysArchitecture: "సిస్టమ్ ఆర్కిటెక్చర్",
  powerUnit: "పవర్ యూనిట్", controlUnit: "కంట్రోల్ యూనిట్", driveSystem: "డ్రైవ్ సిస్టమ్", attachmentsCard: "అటాచ్‌మెంట్‌లు",
  mechDesignTitle: "మెకానికల్ డిజైన్",
  mechDesignP: "దృఢమైన స్టీల్ నిర్మాణం, కాంపాక్ట్ బాడీ మరియు భూభాగ-సిద్ధ చక్రాలతో నిర్మించబడింది.",
  mechLi1: "✔ స్టీల్ ఫ్రేమ్", mechLi2: "✔ మూసిన బాడీ", mechLi3: "✔ 10 అంగుళాల చక్రాలు", mechLi4: "✔ కాంపాక్ట్ డిజైన్",
  elecControlTitle: "ఎలక్ట్రానిక్స్ & కంట్రోల్",
  microTitle: "మైక్రోకంట్రోలర్", motorDriver: "మోటార్ డ్రైవర్", powerSysTitle: "పవర్ సిస్టమ్", safetyTitle: "భద్రత",
  wirelessCommTitle: "వైర్లెస్ కమ్యూనికేషన్",
  wlLi1: "✔ NRF / LoRa మాడ్యూల్స్", wlLi2: "✔ 1KM రేంజ్", wlLi3: "✔ కస్టమ్ రిమోట్", wlLi4: "✔ తక్కువ శక్తి",
  futureTechSectionTitle: "భవిష్యత్ సాంకేతికత",
  futureAiNav: "AI నావిగేషన్", futureIot: "IoT", futureMobile: "మొబైల్ యాప్", futureSolar: "సోలార్",
  contactPageTitle: "అగ్రిరోవర్‌ను సంప్రదించండి",
  contactPageSub: "మీరు మాతో మాట్లాడాలనుకుంటున్నారా — వ్యవసాయి, పెట్టుబడిదారు లేదా భాగస్వామి.",
  sendUsMessage: "మాకు సందేశం పంపండి", contactInformation: "సంప్రదింపు సమాచారం",
  labelEmail: "ఇమెయిల్", labelPhone: "ఫోన్", labelLocation: "స్థానం",
  placeholderName: "మీ పేరు", placeholderEmail: "మీ ఇమెయిల్",
  placeholderSubject: "విషయం", placeholderMessage: "మీ సందేశం",
  sendMessageBtn: "సందేశం పంపండి →",
  teamHeroLabel: "వ్యక్తులు & లక్ష్యం",
  teamHeroTitle: "అగ్రిరోవర్ వెనక ఉన్న బృందాన్ని కలవండి",
  teamHeroLead: "చిన్న మరియు విలువైన వ్యవసాయులు తక్కువ శ్రమ, తక్కువ ఇన్‌పుట్ వ్యర్థం మరియు అంచనా వేయదగిన ఫలితాలతో వ్యవసాయం చేయగలిగేలా, సరసమైన, పొలం-సిద్ధ రోబోటిక్స్ నిర్మిస్తున్నాము.",
  teamStat1: "వ్యవసాయి-ముందు ఉత్పత్తి నిర్ణయాలు",
  teamStat2: "భారతీయ పొలాలు & పంటలకు నిర్మించబడింది",
  teamStat3: "ఒక లూప్‌లో హార్డ్‌వేర్, ఎంబెడెడ్ & AI",
  valuesHeading: "మేము ఎలా పని చేస్తాం",
  valuesIntro: "అగ్రిరోవర్‌ను నిజాయితీగా, ఉపయోగకరంగా మరియు షిప్ చేయగలిగేలా ఉంచే సూత్రాలు.",
  valueH1: "నిర్మించే ముందు వినండి",
  valueP1: "వ్యవసాయి అభిప్రాయం మరియు ఫీల్డ్ ట్రయల్‌లను సత్యానికి మూలంగా పరిగణిస్తాం — స్లైడ్ డెక్‌లు కాదు.",
  valueH2: "హైప్‌పై నమ్మకత్వం",
  valueP2: "సాధారణ యంత్రాలు, పరీక్షించదగిన ఎలక్ట్రానిక్స్ మరియు నిర్వహించదగిన కోడ్ పెళుసైన డెమోలను అధిగమిస్తాయి.",
  valueH3: "వృత్తాన్ని పెంచండి",
  valueP3: "ఒకే లక్ష్యంపై శ్రద్ధ కలిగిన ఇంజినీర్లు, వ్యవసాయ నిపుణులు మరియు భాగస్వాముల స్వాగతాన్ని చురుకుగా స్వీకరిస్తాం.",
  foundersHeading: "వ్యవస్థాపక బృందం",
  foundersIntro: "ఉత్పత్తి, పరిశోధన మరియు అమలుకు దిశను నిర్ణయించే కేంద్ర బృందం.",
  satyamRole: "వ్యవస్థాపకుడు — AI & హార్డ్‌వేర్",
  satyamBio: "అగ్రిరోవర్ యొక్క సాంకేతిక దిశకు నేతృత్వం వహిస్తారు: యాంత్రిక మరియు ఎలక్ట్రానిక్ డిజైన్, రోబోటిక్స్ ఇంటిగ్రేషన్ మరియు పొలంలో తెలివైన ఆటోమేషన్ వైపు రోడ్‌మ్యాప్.",
  tagRobotics: "రోబోటిక్స్", tagPrototyping: "ప్రోటోటైపింగ్", tagSystems: "సిస్టమ్స్ డిజైన్",
  harishRole: "సహ-వ్యవస్థాపకుడు — పరిశోధన & డాక్యుమెంటేషన్",
  harishBio: "పరిశోధన సంశ్లేషణ, డాక్యుమెంటేషన్, గ్రాంట్ మరియు ప్రోగ్రామ్ అప్లికేషన్‌లు మరియు సమన్వయాన్ని నడిపిస్తారు, తద్వారా బృందం కఠినత లేదా స్పష్టత కోల్పోకుండా వేగంగా ముందుకు సాగగలదు.",
  tagResearch: "పరిశోధన", tagGrants: "గ్రాంట్లు & ప్రోగ్రామ్‌లు", tagOperations: "ఆపరేషన్లు",
  engSectionTitle: "ఇంజినీరింగ్ బృందం ఏమి కవర్ చేస్తుంది",
  engSectionIntro: "అగ్రిరోవర్ పరిపక్వమవుతున్న కొద్దీ మేము నిర్మిస్తున్న (మరియు నియమిస్తున్న) సామర్థ్య రంగాలు.",
  engMechTitle: "మెకానికల్ & హార్డ్‌వేర్",
  engMechDesc: "చాసిస్, యాక్చుయేటర్లు, పవర్ మరియు సెన్సార్లు — బురద, దుమ్ము మరియు ఎండలో సుదీర్ఘ రోజులకు రూపొందించబడింది.",
  engEmbTitle: "ఎంబెడెడ్ & ఫర్మ్‌వేర్",
  engEmbDesc: "మైక్రోకంట్రోలర్లు, మోటార్ కంట్రోల్, వైర్లెస్ లింక్‌లు మరియు రోబోట్‌పై సురక్షితమైన, నిర్ణయాత్మక ప్రవర్తన.",
  engSoftTitle: "సాఫ్ట్‌వేర్ & AI",
  engSoftDesc: "ఫీల్డ్ సాఫ్ట్‌వేర్, ట్రయల్‌ల నుండి డేటా మరియు కాలక్రమేణా స్ప్రేయింగ్ మరియు నావిగేషన్‌ను తెలివైనవిగా చేసే మోడల్‌లు.",
  advisorsHeading: "సలహాదారులు",
  advisorsIntro: "మా అనుమానాలను పరీక్షించడానికి మరియు వాస్తవ వ్యవసాయంలో స్థిరంగా ఉండటానికి సహాయపడే డొమైన్ నిపుణులు.",
  advAgTitle: "వ్యవసాయ సలహాదారు",
  advAgDesc: "పంట చక్రాలు, స్థానిక పద్ధతులు మరియు చిన్న వ్యవసాయ భూముల్లో 'తగినంత మంచిది' ఎలా ఉంటుంది.",
  advTechTitle: "సాంకేతిక మార్గదర్శి",
  advTechDesc: "ఆర్కిటెక్చర్, తయారీ సామర్థ్యం మరియు హార్డ్‌వేర్-భారమైన స్టార్టప్‌ను బాధ్యతాయుతంగా స్కేల్ చేయడం.",
  supportHeading: "స్టార్టప్ మద్దతు",
  supportIntro: "మా అమలుకు మద్దతు ఇచ్చే మరియు మనల్ని పర్యావరణ వ్యవస్థతో అనుసంధానించే కార్యక్రమాలు మరియు మార్గదర్శకులు.",
  supInnovTitle: "ఆవిష్కరణ కార్యక్రమాలు",
  supInnovDesc: "మేము ధృవీకరించి మోహరించేటప్పుడు ఇన్‌క్యుబేషన్, కోహోర్ట్‌లు మరియు నిర్మాణాత్మక మద్దతు.",
  supMentorsTitle: "మార్గదర్శకులు",
  supMentorsDesc: "హార్డ్‌వేర్ పంపించిన మరియు ప్రారంభ-దశ వృద్ధిని నావిగేట్ చేసిన ఆపరేటర్లు మరియు వ్యవస్థాపకులు.",
  teamCtaTitle: "అగ్రిరోవర్‌లో చేరాలనుకుంటున్నారా?",
  teamCtaSub: "వారి పని వాస్తవ పొలాల్లో కనిపించాలని కోరుకునే ఇంజినీర్లు, తయారీదారులు మరియు పరిశోధకులను వెతుకుతున్నాము.",
  contactUsBtn: "మమ్మల్ని సంప్రదించండి",
  invHeroTitle: "వ్యవసాయం యొక్క భవిష్యత్తులో పెట్టుబడి పెట్టండి",
  invHeroSub: "అగ్రిరోవర్ భారతదేశంలో లక్షలాది చిన్న వ్యవసాయులకు సరసమైన రోబోటిక్ వ్యవసాయ పరిష్కారాలను నిర్మిస్తోంది.",
  downloadPitch: "పిచ్ డెక్ డౌన్‌లోడ్ చేయండి",
  invProblemTitle: "సమస్య",
  invProb1Title: "శ్రమ కొరత", invProb1Desc: "వ్యవసాయులు శ్రమ కొరత మరియు పెరుగుతున్న వేతనాలను ఎదుర్కొంటున్నారు.",
  invProb2Title: "ఖరీదైన యంత్రాలు", invProb2Desc: "సంప్రదాయ ట్రాక్టర్లు ₹5–8 లక్షలు.",
  invProb3Title: "చిన్న భూమి వైశాల్యం", invProb3Desc: "చాలా మంది వ్యవసాయులకు చాలా చిన్న భూమి ఉంది.",
  invProb4Title: "మాన్యువల్ వ్యవసాయం", invProb4Desc: "చాలా ఆపరేషన్లు ఇంకా మాన్యువల్‌గా ఉన్నాయి.",
  invSolutionTitle: "మా పరిష్కారం",
  invSol1Title: "కాంపాక్ట్ ఎలక్ట్రిక్ రోవర్", invSol1Desc: "చిన్న పొలాలు మరియు ఇరుకైన వ్యవసాయ భూముల కోసం రూపొందించబడింది.",
  invSol2Title: "రిమోట్ కంట్రోల్", invSol2Desc: "1 కిమీ వరకు వైర్లెస్ రేంజ్.",
  invSol3Title: "బహు ప్రయోజన", invSol3Desc: "స్ప్రేయింగ్, విత్తనం, ఎరువు & మరిన్ని.",
  invSol4Title: "సరసమైన", invSol4Desc: "అంచనా వేసిన ఖర్చు ₹1 లక్ష కంటే తక్కువ.",
  invMarketTitle: "మార్కెట్ అవకాశం",
  invTamTitle: "TAM", invTamLine: "9.3 కోటి వ్యవసాయులు", invTamDesc: "భారతదేశంలో మొత్తం వ్యవసాయ వినియోగదారులు.",
  invSamTitle: "SAM", invSamLine: "86% చిన్న వ్యవసాయులు", invSamDesc: "మెజారిటీ చిన్న & విలువైన వ్యవసాయులు.",
  invSomTitle: "SOM", invSomLine: "ప్రారంభ లక్ష్య విభాగం", invSomDesc: "2 ఎకరాల కంటే తక్కువ భూమి ఉన్న వ్యవసాయులు.",
  invInvestTitle: "పెట్టుబడి అవకాశం",
  invInvestP: "అగ్రిరోవర్ భారతదేశం అంతటా స్కేల్ చేయడానికి పెట్టుబడిదారులు, యాక్సిలరేటర్లు మరియు వ్యూహాత్మక భాగస్వాముల కోసం వెతుకుతోంది.",
  invCard1Title: "సీడ్ పెట్టుబడి", invCard1Desc: "ప్రోటోటైప్ & తయారీ దశకు మద్దతు.",
  invCard2Title: "వ్యూహాత్మక భాగస్వాములు", invCard2Desc: "అగ్రి-టెక్ కంపెనీలతో సహకరించండి.",
  invCard3Title: "యాక్సిలరేటర్లు", invCard3Desc: "స్టార్టప్ ప్రోగ్రామ్‌లలో చేరండి & స్కేలింగ్ మద్దతు.",
  invCtaTitle: "పెట్టుబడిలో ఆసక్తి ఉందా?", invCtaBtn: "పెట్టుబడి కోసం సంప్రదించండి",
  blogHeroTitle: "అగ్రిరోవర్ బ్లాగ్",
  blogHeroSub: "వ్యవసాయం, రోబోటిక్స్ మరియు మా స్టార్టప్ ప్రయాణంపై అంతర్దృష్టులు.",
  blogLatestTitle: "తాజా వ్యాసాలు",
  blogArt1Title: "వ్యవసాయంలో AI యొక్క భవిష్యత్తు", blogArt1Desc: "AI & రోబోటిక్స్ ఆధునిక వ్యవసాయాన్ని మారుస్తున్నాయి.",
  blogArt2Title: "చిన్న వ్యవసాయుల సమస్యలు", blogArt2Desc: "అధిక ఖర్చు, తక్కువ టెక్ యాక్సెస్ & శ్రమ కొరత.",
  blogArt3Title: "ఏమి అగ్రిరోవర్", blogArt3Desc: "వాస్తవ వ్యవసాయ సమస్యలను పరిష్కరించడానికి నిర్మించబడింది.",
  blogArt4Title: "వ్యవసాయంలో రోబోటిక్స్", blogArt4Desc: "సామర్థ్యం & దిగుబడిని మెరుగుపరిచే ఆటోమేషన్.",
  blogDevTitle: "అభివృద్ధి నవీకరణలు",
  blogDev1Title: "ప్రోటోటైప్ అభివృద్ధి", blogDev1Desc: "రిమోట్ సిస్టమ్‌తో మొదటి పని చేసే మోడల్‌ను నిర్మిస్తోంది.",
  blogDev2Title: "₹50,000 గ్రాంట్ అందుకున్నాం", blogDev2Desc: "కళాశాల ఆవిష్కరణ కార్యక్రమం ద్వారా మద్దతు.",
  blogFollowTitle: "మా ప్రయాణాన్ని అనుసరించండి",
  blogFollowSub: "అగ్రిరోవర్ పురోగతి & ఆవిష్కరణలతో అప్‌డేట్‌గా ఉండండి",
  blogConnectBtn: "మాతో కనెక్ట్ అవ్వండి"
});

// ─────────────────────────────────────────────
// PAGE-SPECIFIC KEYS — PUNJABI
// ─────────────────────────────────────────────
Object.assign(translations.pa, {
  linkedin: "ਲਿੰਕਡਇਨ", readMore: "ਹੋਰ ਪੜ੍ਹੋ",
  productHeroTitle: "ਅਗਰੀਰੋਵਰ – ਸਮਾਰਟ ਮਿਨੀ ਫਾਰਮਿੰਗ ਰੋਬੋਟ",
  productHeroSub: "ਛੋਟੇ ਕਿਸਾਨਾਂ ਲਈ ਸਪਰੇਇੰਗ, ਬੀਜ ਬੋਣਾ, ਖਾਦ ਪਾਉਣਾ ਅਤੇ ਹੋਰ ਆਟੋਮੇਟਿਕ ਕਰਨ ਲਈ ਡਿਜ਼ਾਈਨ ਕੀਤਾ ਗਿਆ ਕੰਪੈਕਟ ਇਲੈਕਟ੍ਰਿਕ ਰੋਬੋਟਿਕ ਸਿਸਟਮ।",
  watchDemo: "ਡੈਮੋ ਦੇਖੋ",
  badgeFieldReady: "🛡 ਖੇਤ ਲਈ ਤਿਆਰ", badgeEcoFriendly: "🌱 ਵਾਤਾਵਰਣ ਅਨੁਕੂਲ",
  productAboutTag: "ਉਤਪਾਦ ਬਾਰੇ", productOneRobot: "ਇੱਕ ਰੋਬੋਟ। ਅਨੇਕ ਕੰਮ।",
  productAboutP: "ਅਗਰੀਰੋਵਰ ਇੱਕ ਬਹੁਮੁਖੀ ਰੋਬੋਟਿਕ ਪਲੇਟਫਾਰਮ ਹੈ ਜੋ ਭਾਰਤ ਦੇ ਛੋਟੇ ਕਿਸਾਨਾਂ ਤੱਕ ਉਦਯੋਗਿਕ-ਪੱਧਰ ਦੇ ਆਟੋਮੇਸ਼ਨ ਦੀ ਸ਼ਕਤੀ ਲਿਆਉਂਦਾ ਹੈ। ਬਦਲਣਯੋਗ ਟੂਲ ਅਟੈਚਮੈਂਟਾਂ ਨਾਲ, ਇਹ ਸਪਰੇਇੰਗ, ਬੀਜ ਬੋਣਾ ਅਤੇ ਖਾਦ ਪਾਉਣਾ ਸੰਭਾਲਦਾ ਹੈ — ਮਜ਼ਦੂਰ ਖਰਚ ਘਟਾਉਂਦਾ ਹੈ ਅਤੇ ਪੈਦਾਵਾਰ ਵਧਾਉਂਦਾ ਹੈ।",
  productFeat1: "✔ ਭਾਰਤੀ ਖੇਤ ਹਾਲਾਤਾਂ ਲਈ ਸਟੀਲ ਫਰੇਮ",
  productFeat2: "✔ ਅਸਮਾਨ ਜ਼ਮੀਨ ਲਈ 10 ਇੰਚ ਮਜ਼ਬੂਤ ਪਹੀਏ",
  productFeat3: "✔ 1 ਕਿਮੀ ਤੱਕ ਵਾਇਰਲੈੱਸ ਰਿਮੋਟ ਰੇਂਜ",
  productFeat4: "✔ ਬਦਲਣਯੋਗ ਟੂਲ ਅਟੈਚਮੈਂਟ ਸਿਸਟਮ",
  productFeat5: "✔ ਘੱਟ ਪਾਵਰ, ਲੰਬੇ ਸਮੇਂ ਦਾ ਓਪਰੇਸ਼ਨ",
  productFeat6: "✔ ਮੌਸਮ-ਰੋਧੀ ਬੰਦ ਇਲੈਕਟ੍ਰਾਨਿਕਸ",
  exploreTechnology: "ਟੈਕਨਾਲੋਜੀ ਐਕਸਪਲੋਰ ਕਰੋ →",
  problemWeSolve: "ਸਮੱਸਿਆ ਜੋ ਅਸੀਂ ਹੱਲ ਕਰਦੇ ਹਾਂ",
  probLaborTitle: "ਮਜ਼ਦੂਰ ਦੀ ਕਮੀ", probLaborDesc: "ਵਧਦੀ ਮਜ਼ਦੂਰੀ ਦੀ ਲਾਗਤ।",
  probCostTitle: "ਜ਼ਿਆਦਾ ਲਾਗਤ", probCostDesc: "ਮਸ਼ੀਨਾਂ ₹5–8 ਲੱਖ।",
  probLargeTitle: "ਵੱਡੀਆਂ ਮਸ਼ੀਨਾਂ", probLargeDesc: "ਛੋਟੇ ਖੇਤਾਂ ਲਈ ਨਹੀਂ।",
  probManualTitle: "ਹੱਥੀਂ ਕੰਮ", probManualDesc: "ਅਜੇ ਵੀ ਨਿਰਭਰ।",
  futureUpgrades: "ਭਵਿੱਖ ਦੇ ਅੱਪਗ੍ਰੇਡ",
  futureUpgradesList: "ਮੋਬਾਈਲ ਐਪ • AI ਆਟੋਮੇਸ਼ਨ • IoT ਏਕੀਕਰਨ • ਸੋਲਰ ਚਾਰਜਿੰਗ",
  requestDemo: "ਡੈਮੋ ਦੀ ਬੇਨਤੀ ਕਰੋ →",
  techPageHeroTitle: "ਅਗਰੀਰੋਵਰ ਪਿੱਛੇ ਇੰਜੀਨੀਅਰਿੰਗ",
  techPageHeroSub: "ਸਮਾਰਟ ਖੇਤੀਬਾੜੀ ਨੂੰ ਸ਼ਕਤੀ ਪ੍ਰਦਾਨ ਕਰਨ ਵਾਲਾ ਉੱਨਤ ਰੋਬੋਟਿਕਸ, ਐਮਬੈਡਡ ਸਿਸਟਮ ਅਤੇ ਵਾਇਰਲੈੱਸ ਟੈਕ।",
  sysArchitecture: "ਸਿਸਟਮ ਆਰਕੀਟੈਕਚਰ",
  powerUnit: "ਪਾਵਰ ਯੂਨਿਟ", controlUnit: "ਕੰਟਰੋਲ ਯੂਨਿਟ", driveSystem: "ਡਰਾਈਵ ਸਿਸਟਮ", attachmentsCard: "ਅਟੈਚਮੈਂਟ",
  mechDesignTitle: "ਮਕੈਨੀਕਲ ਡਿਜ਼ਾਈਨ",
  mechDesignP: "ਮਜ਼ਬੂਤ ਸਟੀਲ ਢਾਂਚੇ, ਕੰਪੈਕਟ ਬਾਡੀ ਅਤੇ ਟੈਰੇਨ-ਰੈਡੀ ਪਹੀਆਂ ਨਾਲ ਬਣਾਇਆ।",
  mechLi1: "✔ ਸਟੀਲ ਫਰੇਮ", mechLi2: "✔ ਬੰਦ ਬਾਡੀ", mechLi3: "✔ 10 ਇੰਚ ਪਹੀਏ", mechLi4: "✔ ਕੰਪੈਕਟ ਡਿਜ਼ਾਈਨ",
  elecControlTitle: "ਇਲੈਕਟ੍ਰਾਨਿਕਸ & ਕੰਟਰੋਲ",
  microTitle: "ਮਾਈਕ੍ਰੋਕੰਟਰੋਲਰ", motorDriver: "ਮੋਟਰ ਡਰਾਈਵਰ", powerSysTitle: "ਪਾਵਰ ਸਿਸਟਮ", safetyTitle: "ਸੁਰੱਖਿਆ",
  wirelessCommTitle: "ਵਾਇਰਲੈੱਸ ਸੰਚਾਰ",
  wlLi1: "✔ NRF / LoRa ਮੋਡੀਊਲ", wlLi2: "✔ 1KM ਰੇਂਜ", wlLi3: "✔ ਕਸਟਮ ਰਿਮੋਟ", wlLi4: "✔ ਘੱਟ ਪਾਵਰ",
  futureTechSectionTitle: "ਭਵਿੱਖ ਦੀ ਟੈਕਨਾਲੋਜੀ",
  futureAiNav: "AI ਨੈਵੀਗੇਸ਼ਨ", futureIot: "IoT", futureMobile: "ਮੋਬਾਈਲ ਐਪ", futureSolar: "ਸੋਲਰ",
  contactPageTitle: "ਅਗਰੀਰੋਵਰ ਨਾਲ ਸੰਪਰਕ ਕਰੋ",
  contactPageSub: "ਅਸੀਂ ਤੁਹਾਡੇ ਤੋਂ ਸੁਣਨਾ ਚਾਹੁੰਦੇ ਹਾਂ — ਕਿਸਾਨ, ਨਿਵੇਸ਼ਕ ਜਾਂ ਭਾਈਵਾਲ।",
  sendUsMessage: "ਸਾਨੂੰ ਸੁਨੇਹਾ ਭੇਜੋ", contactInformation: "ਸੰਪਰਕ ਜਾਣਕਾਰੀ",
  labelEmail: "ਈਮੇਲ", labelPhone: "ਫ਼ੋਨ", labelLocation: "ਸਥਾਨ",
  placeholderName: "ਤੁਹਾਡਾ ਨਾਮ", placeholderEmail: "ਤੁਹਾਡੀ ਈਮੇਲ",
  placeholderSubject: "ਵਿਸ਼ਾ", placeholderMessage: "ਤੁਹਾਡਾ ਸੁਨੇਹਾ",
  sendMessageBtn: "ਸੁਨੇਹਾ ਭੇਜੋ →",
  teamHeroLabel: "ਲੋਕ & ਮਿਸ਼ਨ",
  teamHeroTitle: "ਅਗਰੀਰੋਵਰ ਪਿੱਛੇ ਟੀਮ ਨੂੰ ਮਿਲੋ",
  teamHeroLead: "ਅਸੀਂ ਕਿਫਾਇਤੀ, ਖੇਤ-ਤਿਆਰ ਰੋਬੋਟਿਕਸ ਬਣਾ ਰਹੇ ਹਾਂ ਤਾਂ ਜੋ ਛੋਟੇ ਅਤੇ ਸੀਮਾਂਤ ਕਿਸਾਨ ਘੱਟ ਮਿਹਨਤ, ਘੱਟ ਇਨਪੁਟ ਬਰਬਾਦੀ ਅਤੇ ਵਧੇਰੇ ਅਨੁਮਾਨਯੋਗ ਨਤੀਜਿਆਂ ਨਾਲ ਖੇਤੀ ਕਰ ਸਕਣ।",
  teamStat1: "ਕਿਸਾਨ-ਪਹਿਲੇ ਉਤਪਾਦ ਫੈਸਲੇ",
  teamStat2: "ਭਾਰਤੀ ਖੇਤਾਂ & ਫਸਲਾਂ ਲਈ ਬਣਾਇਆ",
  teamStat3: "ਇੱਕ ਲੂਪ ਵਿੱਚ ਹਾਰਡਵੇਅਰ, ਐਮਬੈਡਡ & AI",
  valuesHeading: "ਅਸੀਂ ਕਿਵੇਂ ਕੰਮ ਕਰਦੇ ਹਾਂ",
  valuesIntro: "ਉਹ ਸਿਧਾਂਤ ਜੋ ਅਗਰੀਰੋਵਰ ਨੂੰ ਇਮਾਨਦਾਰ, ਉਪਯੋਗੀ ਅਤੇ ਸ਼ਿਪਯੋਗ ਰੱਖਦੇ ਹਨ।",
  valueH1: "ਬਣਾਉਣ ਤੋਂ ਪਹਿਲਾਂ ਸੁਣੋ",
  valueP1: "ਅਸੀਂ ਕਿਸਾਨ ਫੀਡਬੈਕ ਅਤੇ ਫੀਲਡ ਟਰਾਇਲਾਂ ਨੂੰ ਸੱਚ ਦਾ ਸਰੋਤ ਮੰਨਦੇ ਹਾਂ — ਸਲਾਈਡ ਡੈੱਕ ਨਹੀਂ।",
  valueH2: "ਹਾਈਪ ਉੱਤੇ ਭਰੋਸੇਯੋਗਤਾ",
  valueP2: "ਸਧਾਰਨ ਵਿਧੀਆਂ, ਜਾਂਚਯੋਗ ਇਲੈਕਟ੍ਰਾਨਿਕਸ ਅਤੇ ਰੱਖਣਯੋਗ ਕੋਡ ਕਮਜ਼ੋਰ ਡੈਮੋ ਤੋਂ ਬਿਹਤਰ ਹਨ।",
  valueH3: "ਦਾਇਰਾ ਵਧਾਓ",
  valueP3: "ਅਸੀਂ ਉਸੇ ਮਿਸ਼ਨ ਦੀ ਪਰਵਾਹ ਕਰਨ ਵਾਲੇ ਇੰਜੀਨੀਅਰਾਂ, ਖੇਤੀਬਾੜੀ ਮਾਹਿਰਾਂ ਅਤੇ ਭਾਈਵਾਲਾਂ ਦਾ ਸਰਗਰਮੀ ਨਾਲ ਸੁਆਗਤ ਕਰਦੇ ਹਾਂ।",
  foundersHeading: "ਸੰਸਥਾਪਕ ਟੀਮ",
  foundersIntro: "ਉਤਪਾਦ, ਖੋਜ ਅਤੇ ਲਾਗੂਕਰਨ ਦੀ ਦਿਸ਼ਾ ਨਿਰਧਾਰਿਤ ਕਰਨ ਵਾਲੀ ਮੁੱਖ ਟੀਮ।",
  satyamRole: "ਸੰਸਥਾਪਕ — AI & ਹਾਰਡਵੇਅਰ",
  satyamBio: "ਅਗਰੀਰੋਵਰ ਦੀ ਤਕਨੀਕੀ ਦਿਸ਼ਾ ਦੀ ਅਗਵਾਈ ਕਰਦੇ ਹਨ: ਮਕੈਨੀਕਲ ਅਤੇ ਇਲੈਕਟ੍ਰਾਨਿਕ ਡਿਜ਼ਾਈਨ, ਰੋਬੋਟਿਕਸ ਏਕੀਕਰਨ ਅਤੇ ਖੇਤ ਵਿੱਚ ਬੁੱਧੀਮਾਨ ਆਟੋਮੇਸ਼ਨ ਵੱਲ ਰੋਡਮੈਪ।",
  tagRobotics: "ਰੋਬੋਟਿਕਸ", tagPrototyping: "ਪ੍ਰੋਟੋਟਾਈਪਿੰਗ", tagSystems: "ਸਿਸਟਮ ਡਿਜ਼ਾਈਨ",
  harishRole: "ਸਹਿ-ਸੰਸਥਾਪਕ — ਖੋਜ & ਦਸਤਾਵੇਜ਼ੀਕਰਨ",
  harishBio: "ਖੋਜ ਸੰਸ਼ਲੇਸ਼ਣ, ਦਸਤਾਵੇਜ਼ੀਕਰਨ, ਗ੍ਰਾਂਟ ਅਤੇ ਪ੍ਰੋਗਰਾਮ ਅਰਜ਼ੀਆਂ, ਅਤੇ ਤਾਲਮੇਲ ਚਲਾਉਂਦੇ ਹਨ ਤਾਂ ਜੋ ਟੀਮ ਸਖ਼ਤੀ ਜਾਂ ਸਪੱਸ਼ਟਤਾ ਗੁਆਏ ਬਿਨਾਂ ਤੇਜ਼ੀ ਨਾਲ ਅੱਗੇ ਵਧ ਸਕੇ।",
  tagResearch: "ਖੋਜ", tagGrants: "ਗ੍ਰਾਂਟਾਂ & ਪ੍ਰੋਗਰਾਮ", tagOperations: "ਓਪਰੇਸ਼ਨ",
  engSectionTitle: "ਇੰਜੀਨੀਅਰਿੰਗ ਟੀਮ ਕੀ ਕਵਰ ਕਰਦੀ ਹੈ",
  engSectionIntro: "ਸਮਰੱਥਾ ਖੇਤਰ ਜੋ ਅਸੀਂ ਬਣਾ ਰਹੇ ਹਾਂ (ਅਤੇ ਭਰਤੀ ਕਰ ਰਹੇ ਹਾਂ) ਜਿਵੇਂ ਅਗਰੀਰੋਵਰ ਪਰਿਪੱਕ ਹੁੰਦਾ ਹੈ।",
  engMechTitle: "ਮਕੈਨੀਕਲ & ਹਾਰਡਵੇਅਰ",
  engMechDesc: "ਚੈਸਿਸ, ਐਕਚੁਏਟਰ, ਪਾਵਰ ਅਤੇ ਸੈਂਸਰ — ਚਿੱਕੜ, ਧੂੜ ਅਤੇ ਧੁੱਪ ਵਿੱਚ ਲੰਮੇ ਦਿਨਾਂ ਲਈ ਡਿਜ਼ਾਈਨ ਕੀਤੇ।",
  engEmbTitle: "ਐਮਬੈਡਡ & ਫਰਮਵੇਅਰ",
  engEmbDesc: "ਮਾਈਕ੍ਰੋਕੰਟਰੋਲਰ, ਮੋਟਰ ਕੰਟਰੋਲ, ਵਾਇਰਲੈੱਸ ਲਿੰਕ, ਅਤੇ ਰੋਬੋਟ ਉੱਤੇ ਸੁਰੱਖਿਅਤ, ਨਿਰਧਾਰਿਤ ਵਿਵਹਾਰ।",
  engSoftTitle: "ਸਾਫ਼ਟਵੇਅਰ & AI",
  engSoftDesc: "ਫੀਲਡ ਸਾਫ਼ਟਵੇਅਰ, ਟਰਾਇਲਾਂ ਤੋਂ ਡੇਟਾ, ਅਤੇ ਮਾਡਲ ਜੋ ਸਮੇਂ ਦੇ ਨਾਲ ਸਪਰੇਇੰਗ ਅਤੇ ਨੈਵੀਗੇਸ਼ਨ ਨੂੰ ਸਮਾਰਟ ਬਣਾਉਂਦੇ ਹਨ।",
  advisorsHeading: "ਸਲਾਹਕਾਰ",
  advisorsIntro: "ਡੋਮੇਨ ਮਾਹਿਰ ਜੋ ਸਾਡੀਆਂ ਧਾਰਨਾਵਾਂ ਦੀ ਜਾਂਚ ਕਰਨ ਅਤੇ ਅਸਲ ਖੇਤੀਬਾੜੀ ਵਿੱਚ ਜ਼ਮੀਨ ਉੱਤੇ ਰਹਿਣ ਵਿੱਚ ਸਾਡੀ ਮਦਦ ਕਰਦੇ ਹਨ।",
  advAgTitle: "ਖੇਤੀਬਾੜੀ ਸਲਾਹਕਾਰ",
  advAgDesc: "ਫਸਲ ਚੱਕਰ, ਸਥਾਨਕ ਅਭਿਆਸ, ਅਤੇ ਛੋਟੇ ਪਲਾਟਾਂ ਤੇ 'ਕਾਫ਼ੀ ਚੰਗਾ' ਕਿਵੇਂ ਦਿਖਦਾ ਹੈ।",
  advTechTitle: "ਟੈਕਨਾਲੋਜੀ ਮਾਰਗਦਰਸ਼ਕ",
  advTechDesc: "ਆਰਕੀਟੈਕਚਰ, ਨਿਰਮਾਣਯੋਗਤਾ, ਅਤੇ ਹਾਰਡਵੇਅਰ-ਭਾਰੀ ਸਟਾਰਟਅੱਪ ਨੂੰ ਜ਼ਿੰਮੇਵਾਰੀ ਨਾਲ ਸਕੇਲ ਕਰਨਾ।",
  supportHeading: "ਸਟਾਰਟਅੱਪ ਸਹਾਇਤਾ",
  supportIntro: "ਪ੍ਰੋਗਰਾਮ ਅਤੇ ਮਾਰਗਦਰਸ਼ਕ ਜੋ ਸਾਡੇ ਲਾਗੂਕਰਨ ਦਾ ਸਮਰਥਨ ਕਰਦੇ ਹਨ ਅਤੇ ਸਾਨੂੰ ਈਕੋਸਿਸਟਮ ਨਾਲ ਜੋੜਦੇ ਹਨ।",
  supInnovTitle: "ਨਵੀਨਤਾ ਪ੍ਰੋਗਰਾਮ",
  supInnovDesc: "ਇਨਕਿਊਬੇਸ਼ਨ, ਕੋਹੌਰਟ, ਅਤੇ ਢਾਂਚਾਗਤ ਸਹਾਇਤਾ ਜਿਵੇਂ ਅਸੀਂ ਮਾਨਤਾ ਦਿੰਦੇ ਅਤੇ ਤਾਇਨਾਤ ਕਰਦੇ ਹਾਂ।",
  supMentorsTitle: "ਮਾਰਗਦਰਸ਼ਕ",
  supMentorsDesc: "ਉਹ ਆਪਰੇਟਰ ਅਤੇ ਸੰਸਥਾਪਕ ਜਿਨ੍ਹਾਂ ਨੇ ਹਾਰਡਵੇਅਰ ਭੇਜਿਆ ਅਤੇ ਸ਼ੁਰੂਆਤੀ ਵਿਕਾਸ ਨੂੰ ਨੇਵੀਗੇਟ ਕੀਤਾ।",
  teamCtaTitle: "ਅਗਰੀਰੋਵਰ ਵਿੱਚ ਸ਼ਾਮਲ ਹੋਣਾ ਚਾਹੁੰਦੇ ਹੋ?",
  teamCtaSub: "ਅਸੀਂ ਇੰਜੀਨੀਅਰਾਂ, ਬਣਾਉਣ ਵਾਲਿਆਂ ਅਤੇ ਖੋਜਕਰਤਾਵਾਂ ਦੀ ਭਾਲ ਕਰ ਰਹੇ ਹਾਂ ਜੋ ਚਾਹੁੰਦੇ ਹਨ ਕਿ ਉਨ੍ਹਾਂ ਦਾ ਕੰਮ ਅਸਲ ਖੇਤਾਂ ਵਿੱਚ ਦਿਖਾਈ ਦੇਵੇ।",
  contactUsBtn: "ਸਾਡੇ ਨਾਲ ਸੰਪਰਕ ਕਰੋ",
  invHeroTitle: "ਖੇਤੀਬਾੜੀ ਦੇ ਭਵਿੱਖ ਵਿੱਚ ਨਿਵੇਸ਼ ਕਰੋ",
  invHeroSub: "ਅਗਰੀਰੋਵਰ ਭਾਰਤ ਵਿੱਚ ਲੱਖਾਂ ਛੋਟੇ ਕਿਸਾਨਾਂ ਲਈ ਕਿਫਾਇਤੀ ਰੋਬੋਟਿਕ ਖੇਤੀ ਹੱਲ ਬਣਾ ਰਿਹਾ ਹੈ।",
  downloadPitch: "ਪਿੱਚ ਡੈੱਕ ਡਾਊਨਲੋਡ ਕਰੋ",
  invProblemTitle: "ਸਮੱਸਿਆ",
  invProb1Title: "ਮਜ਼ਦੂਰ ਦੀ ਕਮੀ", invProb1Desc: "ਕਿਸਾਨਾਂ ਨੂੰ ਮਜ਼ਦੂਰ ਦੀ ਕਮੀ ਅਤੇ ਵਧਦੀਆਂ ਉਜਰਤਾਂ ਦਾ ਸਾਹਮਣਾ ਕਰਨਾ ਪੈਂਦਾ ਹੈ।",
  invProb2Title: "ਮਹਿੰਗੀ ਮਸ਼ੀਨਰੀ", invProb2Desc: "ਰਵਾਇਤੀ ਟਰੈਕਟਰ ₹5–8 ਲੱਖ ਖਰਚਦੇ ਹਨ।",
  invProb3Title: "ਛੋਟੀ ਜ਼ਮੀਨ ਧਾਰਨ", invProb3Desc: "ਜ਼ਿਆਦਾਤਰ ਕਿਸਾਨਾਂ ਕੋਲ ਬਹੁਤ ਛੋਟੀ ਜ਼ਮੀਨ ਹੈ।",
  invProb4Title: "ਦਸਤੀ ਖੇਤੀ", invProb4Desc: "ਜ਼ਿਆਦਾਤਰ ਕੰਮ ਅਜੇ ਵੀ ਹੱਥੀਂ ਹਨ।",
  invSolutionTitle: "ਸਾਡਾ ਹੱਲ",
  invSol1Title: "ਕੰਪੈਕਟ ਇਲੈਕਟ੍ਰਿਕ ਰੋਵਰ", invSol1Desc: "ਛੋਟੇ ਖੇਤਾਂ ਅਤੇ ਤੰਗ ਖੇਤਾਂ ਲਈ ਡਿਜ਼ਾਈਨ ਕੀਤਾ।",
  invSol2Title: "ਰਿਮੋਟ ਕੰਟਰੋਲ", invSol2Desc: "1 ਕਿਮੀ ਤੱਕ ਵਾਇਰਲੈੱਸ ਰੇਂਜ।",
  invSol3Title: "ਬਹੁ-ਉਦੇਸ਼", invSol3Desc: "ਸਪਰੇਇੰਗ, ਬੀਜ ਬੋਣਾ, ਖਾਦ ਅਤੇ ਹੋਰ।",
  invSol4Title: "ਕਿਫਾਇਤੀ", invSol4Desc: "ਅਨੁਮਾਨਿਤ ਲਾਗਤ ₹1 ਲੱਖ ਤੋਂ ਘੱਟ।",
  invMarketTitle: "ਬਾਜ਼ਾਰ ਮੌਕਾ",
  invTamTitle: "TAM", invTamLine: "9.3 ਕਰੋੜ ਕਿਸਾਨ", invTamDesc: "ਭਾਰਤ ਵਿੱਚ ਕੁੱਲ ਖੇਤੀ ਵਰਤੋਂਕਾਰ।",
  invSamTitle: "SAM", invSamLine: "86% ਛੋਟੇ ਕਿਸਾਨ", invSamDesc: "ਬਹੁਮਤ ਛੋਟੇ ਅਤੇ ਸੀਮਾਂਤ ਕਿਸਾਨ ਹਨ।",
  invSomTitle: "SOM", invSomLine: "ਸ਼ੁਰੂਆਤੀ ਟੀਚਾ ਹਿੱਸਾ", invSomDesc: "2 ਏਕੜ ਤੋਂ ਘੱਟ ਜ਼ਮੀਨ ਵਾਲੇ ਕਿਸਾਨ।",
  invInvestTitle: "ਨਿਵੇਸ਼ ਮੌਕਾ",
  invInvestP: "ਅਗਰੀਰੋਵਰ ਭਾਰਤ ਭਰ ਵਿੱਚ ਸਕੇਲ ਕਰਨ ਲਈ ਨਿਵੇਸ਼ਕਾਂ, ਐਕਸੀਲੇਟਰਾਂ ਅਤੇ ਰਣਨੀਤਕ ਭਾਈਵਾਲਾਂ ਦੀ ਭਾਲ ਕਰ ਰਿਹਾ ਹੈ।",
  invCard1Title: "ਸੀਡ ਨਿਵੇਸ਼", invCard1Desc: "ਪ੍ਰੋਟੋਟਾਈਪ & ਨਿਰਮਾਣ ਪੜਾਅ ਦਾ ਸਮਰਥਨ।",
  invCard2Title: "ਰਣਨੀਤਕ ਭਾਈਵਾਲ", invCard2Desc: "ਖੇਤੀ-ਟੈਕ ਕੰਪਨੀਆਂ ਨਾਲ ਸਹਿਯੋਗ।",
  invCard3Title: "ਐਕਸੀਲੇਟਰ", invCard3Desc: "ਸਟਾਰਟਅੱਪ ਪ੍ਰੋਗਰਾਮਾਂ ਵਿੱਚ ਸ਼ਾਮਲ ਹੋਵੋ & ਸਕੇਲਿੰਗ ਸਹਾਇਤਾ।",
  invCtaTitle: "ਨਿਵੇਸ਼ ਵਿੱਚ ਦਿਲਚਸਪੀ ਹੈ?", invCtaBtn: "ਨਿਵੇਸ਼ ਲਈ ਸੰਪਰਕ ਕਰੋ",
  blogHeroTitle: "ਅਗਰੀਰੋਵਰ ਬਲੌਗ",
  blogHeroSub: "ਖੇਤੀਬਾੜੀ, ਰੋਬੋਟਿਕਸ ਅਤੇ ਸਾਡੀ ਸਟਾਰਟਅੱਪ ਯਾਤਰਾ ਤੇ ਜਾਣਕਾਰੀ।",
  blogLatestTitle: "ਨਵੀਨਤਮ ਲੇਖ",
  blogArt1Title: "ਖੇਤੀਬਾੜੀ ਵਿੱਚ AI ਦਾ ਭਵਿੱਖ", blogArt1Desc: "AI & ਰੋਬੋਟਿਕਸ ਆਧੁਨਿਕ ਖੇਤੀ ਬਦਲ ਰਿਹਾ ਹੈ।",
  blogArt2Title: "ਛੋਟੇ ਕਿਸਾਨਾਂ ਦੀਆਂ ਸਮੱਸਿਆਵਾਂ", blogArt2Desc: "ਉੱਚ ਲਾਗਤ, ਘੱਟ ਟੈਕ ਪਹੁੰਚ & ਮਜ਼ਦੂਰ ਦੀ ਕਮੀ।",
  blogArt3Title: "ਅਗਰੀਰੋਵਰ ਕਿਉਂ", blogArt3Desc: "ਅਸਲ ਖੇਤੀ ਸਮੱਸਿਆਵਾਂ ਹੱਲ ਕਰਨ ਲਈ ਬਣਾਇਆ।",
  blogArt4Title: "ਖੇਤੀਬਾੜੀ ਵਿੱਚ ਰੋਬੋਟਿਕਸ", blogArt4Desc: "ਕੁਸ਼ਲਤਾ & ਪੈਦਾਵਾਰ ਵਧਾਉਣ ਵਾਲਾ ਆਟੋਮੇਸ਼ਨ।",
  blogDevTitle: "ਵਿਕਾਸ ਅੱਪਡੇਟ",
  blogDev1Title: "ਪ੍ਰੋਟੋਟਾਈਪ ਵਿਕਾਸ", blogDev1Desc: "ਰਿਮੋਟ ਸਿਸਟਮ ਨਾਲ ਪਹਿਲਾ ਕੰਮ ਕਰਨ ਵਾਲਾ ਮਾਡਲ ਬਣਾਉਣਾ।",
  blogDev2Title: "₹50,000 ਗ੍ਰਾਂਟ ਮਿਲੀ", blogDev2Desc: "ਕਾਲਜ ਨਵੀਨਤਾ ਪ੍ਰੋਗਰਾਮ ਦੁਆਰਾ ਸਮਰਥਿਤ।",
  blogFollowTitle: "ਸਾਡੀ ਯਾਤਰਾ ਦਾ ਅਨੁਸਰਣ ਕਰੋ",
  blogFollowSub: "ਅਗਰੀਰੋਵਰ ਦੀ ਤਰੱਕੀ & ਨਵੀਨਤਾਵਾਂ ਨਾਲ ਅੱਪਡੇਟ ਰਹੋ",
  blogConnectBtn: "ਸਾਡੇ ਨਾਲ ਜੁੜੋ"
});

// ─────────────────────────────────────────────
// RUNTIME FUNCTIONS
// ─────────────────────────────────────────────

function getCurrentLanguage() {
  return localStorage.getItem('language') || 'en';
}

function htmlLangFromCode(lang) {
  if (lang === 'pa') return 'pa-Guru';
  return lang;
}

function syncLangToggleLabel() {
  const langBtn = document.querySelector('.lang-toggle');
  const lang = getCurrentLanguage();
  if (langBtn && languageNames[lang]) {
    langBtn.textContent = languageNames[lang];
  }
}

function closeLangDropdown() {
  const wrap = document.querySelector('.lang-dropdown');
  const toggle = document.querySelector('.lang-toggle');
  if (wrap) wrap.classList.remove('lang-dropdown--open');
  if (toggle) toggle.setAttribute('aria-expanded', 'false');
}

function changeLanguage(lang) {
  setLanguage(lang);
  closeLangDropdown();
}

function setLanguage(lang) {
  const code = translations[lang] ? lang : 'en';
  localStorage.setItem('language', code);
  document.documentElement.lang = htmlLangFromCode(code);
  updateTexts();
  syncLangToggleLabel();
}

function updateTexts() {
  const lang = getCurrentLanguage();
  const code = translations[lang] ? lang : 'en';
  const trans = { ...translations.en, ...translations[code] };

  document.querySelectorAll('[data-key]').forEach(el => {
    const key = el.getAttribute('data-key');
    if (trans[key] !== undefined && trans[key] !== '') {
      el.textContent = trans[key];
    }
  });

  document.querySelectorAll('[data-placeholder]').forEach(el => {
    const key = el.getAttribute('data-placeholder');
    if (trans[key] !== undefined && trans[key] !== '') {
      el.placeholder = trans[key];
    }
  });
}

function initLangDropdown() {
  const wrap = document.querySelector('.lang-dropdown');
  const toggle = document.querySelector('.lang-toggle');
  if (!wrap || !toggle) return;

  toggle.addEventListener('click', (e) => {
    e.preventDefault();
    e.stopPropagation();
    const open = wrap.classList.toggle('lang-dropdown--open');
    toggle.setAttribute('aria-expanded', open ? 'true' : 'false');
  });

  wrap.addEventListener('click', (e) => e.stopPropagation());
  document.addEventListener('click', () => closeLangDropdown());
  document.addEventListener('keydown', (e) => {
    if (e.key === 'Escape') closeLangDropdown();
  });
}

document.addEventListener('DOMContentLoaded', () => {
  const lang = getCurrentLanguage();
  document.documentElement.lang = htmlLangFromCode(translations[lang] ? lang : 'en');
  updateTexts();
  syncLangToggleLabel();
  initLangDropdown();
});
